### ISSUE TITLE
Unable to initialize third party plugin

### ISSUE THREAD

**Issue by virgilsky** [mopub/mopub-unity-sdk#10]
I am trying to upgrade the MoPub Unity SDK on an older project of mine. I went for Android first as I hopped it would be easier. I am using Unity 5.4.1 due to other dependencies.

I have successfully followed the steps described [here](https://www.mopub.com/resources/docs/unity-engine-integration/). I have also added the unity packages for AdMob, Facebook, Millenial and Unity custom events, resulting in the following folder tree in my project's `./Assets/Plugins/Android`: 
![image](https://user-images.githubusercontent.com/6013905/34699203-ae60d12a-f4e4-11e7-8e1f-a36f41c5e7cd.png)

I have also added the latest AudienceNetwork.aar and unity-ads.aar in the path `./Assets/Plugins/Android`.

Also, I was careful to call the following upon application's init:
`MoPub.loadBannerPluginsForAdUnits(allBannerAdUnits);
        MoPub.loadInterstitialPluginsForAdUnits(allInterstitialAdUnits);
        MoPub.loadRewardedVideoPluginsForAdUnits(allRewardedVideoAdUnits);`

But when I call `MoPub.createBanner(GetBannerID(), MoPubAdPosition.TopLeft);` I get the following error:

`AdUnit *** not found: no plugin was initialized`

What I am missing?

Thanks!

**Comment by virgilsky** [comment]
I believe I have narrowed it down to
`MoPub.loadBannerPluginsForAdUnits` -> `bannerPluginsDict.Add (bannerAdUnitId, new MPBanner (bannerAdUnitId))` -> `public MoPubAndroidBanner (string adUnitId)` -> `_bannerPlugin = new AndroidJavaObject ("com.mopub.unity.MoPubBannerUnityPlugin", adUnitId)`, which seems to fail.
I have checked, and the **mopub** folder contains the file **mopub-unity-plugins.jar** which contains the **MoPubBannerUnityPlugin.class** file, but it does not seem to actually be called...

Any thoughts?
Thanks

**Comment by virgilsky** [comment]
Solved it!

For some reason Unity was not including the **mopub/libs/*jars** in the apk. I have reimported the unitypackage and it worked.

**Comment by aornelas** [comment]
Glad you figured it out! Let us know if you have other issues 👍
