### ISSUE TITLE
On Device, when calling MoPub.RequestRewardedVideo with different ad unit simultaneously, it raise more EmitRewardedVideoLoadedEvent than expected.

### ISSUE THREAD

**Issue by yuewah** [mopub/mopub-unity-sdk#101]
On Device, when calling MoPub.RequestRewardedVideo with different ad unit simultaneously, it raise more EmitRewardedVideoLoadedEvent than expected.

MoPub SDK Version: 5.10
Device model and OS Version: Samsung Galaxy J2, OS 5.1.1
Unity Version: 2019.1.6f1
Ad Unit IDs used in reproducing the issue:
Launch the app
Once SDK is initialized, call MoPub.RequestRewardedVideo with 3 different ad unit simultaneously
(e.g. a779cd3f15994760988d06e8a4641630, 364e003259fa4311bb3b8de5f0f4a456, 6b9fd6a6ced145f3806821e294842a5f )
Expected behavior:
3 EmitRewardedVideoLoadedEvent
Observed behavior:
9 EmitRewardedVideoLoadedEvent

Evidence:
01-08 13:50:26.354: I/Unity(12046): [MoPub-Unity] [EmitSdkInitializedEvent] SDK initialized and ready to display ads.  Log Level: Debug
01-08 13:50:34.673: I/Unity(12046): [MoPub-Unity] [RequestRewardedVideo] Attempting to load ad a779cd3f15994760988d06e8a4641630
01-08 13:50:34.703: I/Unity(12046): [MoPub-Unity] [RequestRewardedVideo] Attempting to load ad 364e003259fa4311bb3b8de5f0f4a456
01-08 13:50:34.703: I/Unity(12046): [MoPub-Unity] [RequestRewardedVideo] Attempting to load ad 6b9fd6a6ced145f3806821e294842a5f
01-08 13:50:50.438: I/Unity(12046): [MoPub-Unity] [EmitRewardedVideoLoadedEvent] Ad loaded a779cd3f15994760988d06e8a4641630
01-08 13:50:50.538: I/Unity(12046): [MoPub-Unity] [EmitRewardedVideoLoadedEvent] Ad loaded 364e003259fa4311bb3b8de5f0f4a456
01-08 13:50:50.548: I/Unity(12046): [MoPub-Unity] [EmitRewardedVideoLoadedEvent] Ad loaded 6b9fd6a6ced145f3806821e294842a5f
01-08 13:50:50.568: I/Unity(12046): [MoPub-Unity] [EmitRewardedVideoLoadedEvent] Ad loaded a779cd3f15994760988d06e8a4641630
01-08 13:50:50.568: I/Unity(12046): [MoPub-Unity] [EmitRewardedVideoLoadedEvent] Ad loaded 364e003259fa4311bb3b8de5f0f4a456
01-08 13:50:50.568: I/Unity(12046): [MoPub-Unity] [EmitRewardedVideoLoadedEvent] Ad loaded 6b9fd6a6ced145f3806821e294842a5f
01-08 13:50:50.578: I/Unity(12046): [MoPub-Unity] [EmitRewardedVideoLoadedEvent] Ad loaded a779cd3f15994760988d06e8a4641630
01-08 13:50:50.578: I/Unity(12046): [MoPub-Unity] [EmitRewardedVideoLoadedEvent] Ad loaded 364e003259fa4311bb3b8de5f0f4a456
01-08 13:50:50.578: I/Unity(12046): [MoPub-Unity] [EmitRewardedVideoLoadedEvent] Ad loaded 6b9fd6a6ced145f3806821e294842a5f

**Comment by chauduyphanvu** [comment]
@yuewah, thanks for letting us know! I reproduced the issue and have let the rest of the team know.

Stay tuned for an update!

Vu Chau
MoPub Team

**Comment by chauduyphanvu** [comment]
@yuewah, we looked into this more, and this is working as intended. We are simply notifying `EmitRewardedVideoLoadedEvent` more often because the ad unit IDs you are using are mapped to the same network placement ID on the MoPub dashboard, and we don't know which ad unit the network's listener came back on.

Please ensure that you are setting up your ad unit IDs with unique network placements and give this another try!
