### ISSUE TITLE
Ad loading fails on Amazon Android App

### ISSUE THREAD

**Issue by sourav-paul** [mopub/mopub-unity-sdk#103]
Ads work fine with regular android devices. I made sure I have amazon supported ad networks such as Vungle, AdColony. In total 8/9 network adaptors are in the project. Want to use common source for multiple mobile platforms.

#### Steps to reproduce the behavior:
->Import Mopub for Unity 5.11.
-> Import adapters for AdColony, Vungle, Admob, Tapjoy, iron source, FAN, Unity, Mintegral.
-> Force resolve, (armv7 only)
-> Use Proguard for Minify ( else won't build for dex issue)
-> Load the scene in demo 
-> put a valid AD Unit Id in the mopub manager prefab. 
-> Add all network script components with "Add network configuration" 
-> Put real ids in the banner, interstitial, rewarded ids in the demo script, 
-> Put app ids in the mopub manager prefab's related script components
-> Build

#### Expected behavior:
Works fine in regular android. Can see some live ads, some are test ads though. Running on the Amazon fire tab 5 should work the same.

#### Observed behavior:
But when running on the Amazon fire tab 5, it runs properly but can't load any ads when request. all consent accepted, 

#### Evidence:
Upon attempting request ads Log says
Status label updated to : error: failed to load rewarded video ad unit xxxxxxxxx: no ads found

**Comment by chauduyphanvu** [comment]
@sourav-paul, thanks for letting us know! We do support Amazon devices, so do you have the full device logs that you could share so we can look into a possible cause? 

Are you able to also validate whether ad loading succeeds on another Amazon device besides the Fire Tab 5? Does MoPub's Marketplace (no mediation) work on the Fire Tab 5?

Vu Chau
MoPub Team
