### ISSUE TITLE
Can't play AdMob Test Ad with iOS AdvertisingID

### ISSUE THREAD

**Issue by psstevenchan** [mopub/mopub-unity-sdk#106]
Adding AdMobNetworkConfig TestDevices with the ios device AdvertisingID.
It play Live Ad instead of Test Ad.

#### Steps to reproduce the behavior:
1. Run MoPubDemo on device
2. Preload Rewarded VideoAd 
3. Play VideoAd

#### Expected behavior:
Play Test AdMobAd

#### Observed behavior:
Play Live AdMobAd

**Comment by chauduyphanvu** [comment]
@psstevenchan, it doesn't look like you can pass the device ID from Unity to iOS just yet. The function is there but it is not feature-complete (it will be in the future!).

For now, to activate test ads, you can use the AdMob test ad unit ID [available here](https://developers.google.com/admob/ios/test-ads). Let us know if you need anything else!

Vu Chau
MoPub Team
