### ISSUE TITLE
iOS build error - mopub.h file not found

### ISSUE THREAD

**Issue by sourav-paul** [mopub/mopub-unity-sdk#107]
iOS build error. `mopub.h file not found`

#### Steps to reproduce the behavior:
Import just Mopub Unity SDK 5.11.1. Load the demo scene provided. Build for iOS. It generates only *.xcodeproj file even though it's set to workspace in Cocoapods settings. So open that. Put creds on Xcode. Try building.

#### Expected behavior:
Build should be done. The demo scene should be appearing.

#### Observed behavior:
Fails with an error. Says "mopub.h file not found"

#### Evidence:
Please check attachment
![Screenshot 2020-02-25 at 11 08 29 PM](https://user-images.githubusercontent.com/6245802/75269894-dd698080-5823-11ea-9355-4b621673c69b.png)

**Comment by juho-lightneer** [comment]
Hey!
About your problem where *.xcworkapce file is not generated, only *.xcodeproj.
We noticed the same behavior after updating to the MoPub SDK version 5.11.1. Building with .xcodeproj doesn't work for us either but partly the reason is due other plugins we have. Anyway during Unity build phase we got an error:

> Analyzing dependencies

>[!] CocoaPods could not find compatible versions for pod "mopub-ios-sdk/Core":
>  In Podfile:
>    mopub-ios-sdk/Core (= 5.11.1)

>None of your spec sources contain a spec satisfying the dependency: mopub-ios-sdk/Core (= >5.11.1).

>You have either:
> * out-of-date source repos which you can update with pod repo update or with pod install -->repo-update.
> * mistyped the name or version.
> * not added the source repo that hosts the Podspec to your Podfile.

How we got this fixed: in the MoPubDependencies.xml the SDK adds iosPod dependency for mopub-ios-sdk version 5.11.1 but it seems that this version is not out yet. We got our builds fixed by changing the dependency back to 5.11.0 for now. 

Hope this helps with your problem :)

**Comment by dravyan** [comment]
@sourav-paul and @juho-lightneer, thank you for reporting the issue. As a workaround please update the iosPod for `mopub-ios-sdk` version to `5.11.0` in `MoPubDependencies.xml` file. We will notify this thread once the updated version of MoPub unity plugin is released. 

Thank you,
Dravya Nataraj
MoPub Team

**Comment by sourav-paul** [comment]
Thanks guys. The workaround works.

Is it safe to go for production with 5.11.0 for ios-sdk from 5.11.1 SDK?

**Comment by dravyan** [comment]
@sourav-paul, yes, 5.11.0 is the latest mopub-ios-sdk available.

**Comment by cody-greenhalge** [comment]
@dravyan I got this same issue and updated the version to 5.11.0 and now it creates the *.xcworkspace file. 
But when I try and build the project I still get the 'MoPub.h' file not found error that the OP showed.

Any other thoughts? I looks like its not picking up any of the frameworks that Unity has linked.

**Comment by sourav-paul** [comment]
@cody-greenhalge Do you have Cocoapods installed and updated? You should export from MacOS. Or else you have to generate these dependencies within the exported project manually.

**Comment by ttesla** [comment]
Damn! Strugling with this for a couple of hours. I guess nobody is testing their stuff in these days.

**Comment by sourav-paul** [comment]
> Damn! Strugling with this for a couple of hours. I guess nobody is testing their stuff in these days.

What seems to be the problem with your test?
Please follow the comments thoroughly. There is a solution described with steps that work just fine.

**Comment by ttesla** [comment]
> > Damn! Strugling with this for a couple of hours. I guess nobody is testing their stuff in these days.
> 
> What seems to be the problem with your test?
> Please follow the comments thoroughly. There is a solution described with steps that work just fine.

That solution worked for me as well. My complaint was for mopub sdk.

**Comment by wacamoe** [comment]
@ttesla hear you loud and clear - we have buffed up our testing in this area to ensure that this doesn't happen again.

For a bit more transparency, we released a hotfix on Android, and then on Android Unity, but it also applied the version update to the iOS podfile even though we did not update iOS. Our build scripts have been updated and we apologize for this issue!

**Comment by chauduyphanvu** [comment]
This should be fixed in the 5.12.0 SDK release. Let us know if you continue seeing the issue!

Vu Chau
MoPub Team

**Comment by FernandoMonroy** [comment]
Happened to me with version 5.13.1 MobPub unity SDK, exact same error.

**Comment by yuliang136** [comment]
Happened to me with version 5.14.1 MobPub unity SDK, exact same error.

**Comment by chauduyphanvu** [comment]
@yuliang136 - please create a new GitHub Issue for the behavior you are seeing so we can investigate it separately. Thank you!

**Comment by zenith-jacob** [comment]
5.16.1, exact same error

**Comment by dinukapj** [comment]
5.17.0 same error

**Comment by chauduyphanvu** [comment]
Please open a new GitHub Issue for 5.17.0 with the appropriate details and our team can take a look. Thank you!

**Comment by zenith-jacob** [comment]
So should we open for all versions? It's bugged in each of them.
We already made a hackfix in our code (as other developers probably too), it's the first thing we do when we integrate Mopub.
I think it would be smart from you guys to create the issue yourself and just simply fix it. It's getting ridiculous really. You will get rid of the issue forever once you fix it once.

**Comment by chauduyphanvu** [comment]
@zenith-jacob, I understand your concern and have let the rest of the team know about the issue. 

My proposal to open a new thread is so that we can collect new details and get more info needed to assess whether the issue might be triggered by different factors, and resolve it accordingly. If you have repro details, it'd be great if you can share them with us.

Thanks.
