### ISSUE TITLE
onInterstitialFailedEvent iOS/Android consistency

### ISSUE THREAD

**Issue by vbarthel-fr** [mopub/mopub-unity-sdk#11]
The event `onInterstitialFailedEvent` from `MoPubManager` takes a string as parameter:
https://github.com/mopub/mopub-unity-sdk/blob/63697e34eb2608ae3e576e29090057f6101e69bc/unity/MoPubUnityPlugin/Assets/MoPub/MoPubManager.cs#L60

The documentation does not give a lot of details about the string. From my understanding, on iOS this string is the **placement id** but on Android it is an **error message**:

- iOS
https://github.com/mopub/mopub-unity-sdk/blob/63697e34eb2608ae3e576e29090057f6101e69bc/mopub-ios-sdk-unity/mopub-ios-sdk-unity/MoPubManager.mm#L378-L381

- Android
https://github.com/mopub/mopub-unity-sdk/blob/63697e34eb2608ae3e576e29090057f6101e69bc/mopub-android-sdk-unity/src/main/java/com/mopub/unity/MoPubInterstitialUnityPlugin.java#L74-L79

This can be quite error prone from the perspective of a unity developer that wants to know which placement has just failed. 

```
MoPubManager.onInterstitialFailedEvent += placementId => {  }
```

VS

```
MoPubManager.onInterstitialFailedEvent += errorMessage => {  }
```

Having a more consistent `onInterstitialFailedEvent` on both platforms might be a nice improvement :)

**Comment by aornelas** [comment]
Thanks for reporting this issue! We'll try to make the Android event use the ad unit ID as well for the next release ;)

**Comment by aornelas** [comment]
We've fixed this in the latest release, thanks!
