### ISSUE TITLE
Mopub use old version of target uid for PBXProject (Export iOS error)

### ISSUE THREAD

**Issue by yuryshumovsky** [mopub/mopub-unity-sdk#111]
Mopub use old version of target uid for PBXProject

#### Steps to reproduce the behavior:
1. Create Unity project
2. Integrate mopub unitypackage
3. Export project for xCode

#### Expected behavior:
Export without errors

#### Observed behavior:
Export error. 
Please look at line /Users/builduser/buildslave/unity/build/External/XcodeAPI/Xcode/PBXProject.cs:168
I can't access to this file. maybe this file from any dll? 

```
Exception: Calling TargetGuidByName with name='Unity-iPhone' is deprecated. There are two targets now, call GetUnityMainTargetGuid() - for app or GetUnityFrameworkTargetGuid() - for source/plugins to get Guid instead.
UnityEditor.iOS.Xcode.PBXProject.TargetGuidByName (System.String name) (at /Users/builduser/buildslave/unity/build/External/XcodeAPI/Xcode/PBXProject.cs:168)
Google.IOSResolver.UpdateProjectDeps (UnityEditor.BuildTarget buildTarget, System.String pathToBuiltProject) (at /Users/smiles/dev/src/unity-jar-resolver/source/IOSResolver/src/IOSResolver.cs:2280)
Google.IOSResolver.OnPostProcessUpdateProjectDeps (UnityEditor.BuildTarget buildTarget, System.String pathToBuiltProject) (at /Users/smiles/dev/src/unity-jar-resolver/source/IOSResolver/src/IOSResolver.cs:2243)
```

**Comment by dravyan** [comment]
@yuryshumovsky, thank you for reporting this. We are aware of the issue. The fix has been applied and will be available in the next MoPub Unity SDK release. We will notify this thread once the SDK is available.

Meanwhile, the below workaround should help.

- Remove the Ads package from Package Manager Instructions to access Ads package is [here](https://docs.unity3d.com/Packages/com.unity.package-manager-ui@1.8/manual/index.html)

- Update the Jar resolver to at least 1.2.129

Thanks,
Dravya Nataraj
MoPub Team

**Comment by chauduyphanvu** [comment]
This should be fixed in the 5.12.0 SDK release. Let us know if you continue seeing the issue!

Vu Chau
MoPub Team

**Comment by bayasgalanl** [comment]
This issue appears Mopub SDK 5.15.0
iOS 
Unity 2019.4.14f1

**Comment by chauduyphanvu** [comment]
@bayasgalanl - we are aware of that issue and will issue a fix in the upcoming SDK release. Meanwhile, apply the following workaround and try rebuilding your app:

1. In Unity, locate the MoPubPostBuildiOS.cs file in the MoPub SDK.
2. Replace the `var target = project.TargetGuidByName("Unity-iPhone");` line with the following code and rebuild the project: 

    ```c#
    var target =

   #if UNITY_2019_3_OR_NEWER    
        project.GetUnityMainTargetGuid();
    #else    
        project.TargetGuidByName("Unity-iPhone");
    #endif
    ```
