### ISSUE TITLE
Cannot build iOS projects with Unity 2019.3.7

### ISSUE THREAD

**Issue by sanderson82** [mopub/mopub-unity-sdk#114]
Cannot build iOS projects with Unity 2019.3.7

- [x ] I am submitting a bug report for existing functionality
- [ x] I visited https://developers.mopub.com/ and found no answer
- [ x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
Unity MoPub 5.11.1

#### Device model and OS Version:
iPhone X iOS 13.4
XCode 11.4

#### Unity Version:
2019.3.7

#### Steps to reproduce the behavior:

1.  Clone the Sample Unity Mopub app from this repo
2.  Open in Unity 2019.3.7
3.  Export the project to XCode 
4.  Open the project in XCode and attempt to build it

#### Expected behavior:
Application compiles and can run on device.

#### Observed behavior:

XCode Compilation Error

Undefined symbols for architecture arm64:
  "_UnityPause", referenced from:
      -[MoPubManager willPresentModalViewForAd:] in libMoPub-SDK-Plugin.a(MoPubManager.o)
      -[MoPubManager didDismissModalViewForAd:] in libMoPub-SDK-Plugin.a(MoPubManager.o)
      -[MoPubManager adViewShouldClose:] in libMoPub-SDK-Plugin.a(MoPubManager.o)
      -[MoPubManager interstitialDidAppear:] in libMoPub-SDK-Plugin.a(MoPubManager.o)
      -[MoPubManager interstitialWillDisappear:] in libMoPub-SDK-Plugin.a(MoPubManager.o)
      -[MoPubManager interstitialDidDisappear:] in libMoPub-SDK-Plugin.a(MoPubManager.o)
      -[MoPubManager rewardedVideoAdDidAppearForAdUnitID:] in libMoPub-SDK-Plugin.a(MoPubManager.o)
      ...
  "_UnitySendMessage", referenced from:
      +[MoPubManager sendUnityEvent:withArgs:] in libMoPub-SDK-Plugin.a(MoPubManager.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I was able to build the sample app successfully with Unity 2019.2.21 & XCode 11.4

#### Evidence:
Device log files, Network log file, etc.

**Comment by dravyan** [comment]
@sanderson82, can you share the version of External Dependency Manager you are using?. Please force Resolve after updating the version and deleting Ads package manager in Assets > External DependencyManager > Force Resolve.

**Comment by chauduyphanvu** [comment]
This should be fixed in the 5.12.0 SDK release. Let us know if you continue seeing the issue!

Vu Chau
MoPub Team

**Comment by bahattin-alictus** [comment]
I am getting the same failure in 

- **Mopub 5.16.0** 
- Both in **Unity 2019.4.14** & **Unity 2019.4.20**

I have tried different External Dependency Manager versions, the result had not been different.

**Comment by lfg-ryan** [comment]
> I am getting the same failure in
> 
> * **Mopub 5.16.0**
> * Both in **Unity 2019.4.14** & **Unity 2019.4.20**
> 
> I have tried different External Dependency Manager versions, the result had not been different.

Were you able to find a workaround? Running into the same issue currently after resolving many other issues encountered.

**Comment by bahattin-alictus** [comment]
@lfg-ryan yes, it is related to this one [https://github.com/mopub/mopub-unity-sdk/issues/151](https://github.com/mopub/mopub-unity-sdk/issues/151)
