### ISSUE TITLE
Podfile is generated with absolute path

### ISSUE THREAD

**Issue by neanton** [mopub/mopub-unity-sdk#117]
Project is not portable to other build machine during CI. Google Play Services IOSResolver converts relative paths to absolute at https://github.com/googlesamples/unity-jar-resolver/blob/v1.2.153/source/IOSResolver/src/IOSResolver.cs#L147
Is there any way to not use `path` directive in `iosPod` of `MoPubDependencies.xml` maybe custom source repository? Or even publish MoPub-SDK-Plugin as a CocoaPod itself?

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.11.1
#### Device model and OS Version:
Not relevant
#### Unity Version:
Not relevant
#### Ad Unit IDs used in reproducing the issue:
Not relevant
#### Steps to reproduce the behavior:
Export Xcode project from Windows build machine

#### Expected behavior:
Podfile does not contain absolute path to MoPub-SDK-Plugin

#### Observed behavior:
Podfile contains absolute path to MoPub-SDK-Plugin

#### Evidence:
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'Unity-iPhone' do
  pod 'FBSDKCoreKit', '5.9.0'
  pod 'FBSDKLoginKit', '5.9.0'
  pod 'FBSDKShareKit', '5.9.0'
  pod 'Firebase/Analytics', '6.0.0'
  pod 'Firebase/Core', '6.0.0'
  pod 'Firebase/Performance', '6.0.0'
  pod 'FirebaseInstanceID', '4.0.0'
  pod 'MoPub-AdColony-Adapters', '4.1.4.0', :subspecs => ['Network']
  pod 'MoPub-AdMob-Adapters', '7.57.0.0', :subspecs => ['Network']
  pod 'MoPub-FacebookAudienceNetwork-Adapters', '5.8.0.0', :subspecs => ['Network']
  pod 'mopub-ios-sdk', '5.11.0', :subspecs => ['Core']
  pod 'MoPub-SDK-Plugin', :path => 'F:\Users\xxx\yyy\zzz\MoPub\Plugins\iOS'
  pod 'MoPub-UnityAds-Adapters', '3.4.2.0', :subspecs => ['Network']
  pod 'MoPub-Vungle-Adapters', '6.5.3.0', :subspecs => ['Network']
end
```

**Comment by chauduyphanvu** [comment]
@neanton, thanks for letting us know! We do have internal work scheduled to use relative paths wherever possible. More updates to come—stay tuned!

Vu Chau
MoPub Team,

**Comment by twomedia** [comment]
I'm also waiting for a fix on this, all other libs use source repositories instead of referencing them locally. This really does make my CI pipeline unnecessarily complicated...

**Comment by chauduyphanvu** [comment]
Thanks for the feedback, @twomedia. I've let the rest of the team know and we'll see what we can do here.

**Comment by twomedia** [comment]
For anyone having this issue what I've done for now is make a Unity Editor script to copy the podspec to a static location on the build machine (or make it a build dependency) and rewrite the podfile to reference that before the 'pod update' build step runs.

**Comment by Aksh627** [comment]
How i have solved the problem is basically by changing the xml file which contains the absolute path for the podspec file for moub. That path is actually absolute path and when post process of the build is complete that path is pasted in the podfile. So to fix that i have made changes to the xml and i am fixing the path there itself. So this way i dont have to manually change the podfile again and again. Also i have made this as a part of my preprocess build step so that i dont also have to manually run this method again and again. If i export xcode project from any machine this would work perfectly fine.

```
private const string MOPUB_DEPENDENCIES_FILE_PATH = "MoPubDependencies.xml"; //dependcy file path
private const string XML_ATTRIBUTE_PATH = "path";
private const string XML_ELEMENT_DEPENDENCIES = "dependecies";
private const string XML_ELEMENT_IOS_PODS = "iosPods";
private const string XML_ELEMENT_IOS_POD = "iosPod";
private const string MOPUB_PODSPEC_FILE_PATH = "MoPub/Plugins/iOS"; //mopub podspec file path

private void FixMopubPodspecPath()
 {
        XDocument xmlFile = XDocument.Load(MOPUB_DEPENDENCIES_FILE_PATH);
        var query = from c in xmlFile.Elements(XML_ELEMENT_DEPENDENCIES).Elements(XML_ELEMENT_IOS_PODS).Elements(XML_ELEMENT_IOS_POD)    
            select c;
        foreach (XElement book in query) 
        {
            if(book.Attribute(XML_ATTRIBUTE_PATH) == null){
                continue;
            }
            book.Attribute(XML_ATTRIBUTE_PATH).Value = Path.GetFullPath(MOPUB_PODSPEC_FILE_PATH);
        }
        xmlFile.Save(MOPUB_DEPENDENCIES_FILE_PATH);
}
```
