### ISSUE TITLE
Unity IOS :IOS framework addition failed due to a CocoaPods installation failure. This will will likely result in an non-functional Xcode project.

### ISSUE THREAD

**Issue by GITHUB243884919** [mopub/mopub-unity-sdk#119]
One line summary of the issue here

- [ ] I am submitting a bug report for existing functionality
- [ ] I visited https://developers.mopub.com/ and found no answer
- [ ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ ] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
1.Download mopub-unity-sdk and import to Unity Editor
2.add the mopub's MopubDemoScene in sdk to building setting
3.Use mopub sdk manager import admob and Facebook audience
4.Switch to IOS and build 
#### Expected behavior:
As concisely as possible, describe the expected behavior.

#### Observed behavior:
As concisely as possible, describe the observed behavior.
**I am sure I have installed cocoaPods.** If I type gem list then shows：
cocoapods (1.8.4)
cocoapods-core (1.8.4)
cocoapods-deintegrate (1.0.4)
cocoapods-downloader (1.3.0)
cocoapods-plugins (1.0.0)
cocoapods-search (1.0.0)
cocoapods-stats (1.1.0)
cocoapods-trunk (1.4.1)
cocoapods-try (1.1.0)

**I try to type"pod repo update" and add   "export LANG=en_US.UTF-8" to the ~/.profile But When I build this project，the Unity console shows** :
iOS framework addition failed due to a CocoaPods installation failure. This will will likely result in an non-functional Xcode project.
After the failure, "pod repo update" was executed and succeeded. "pod install" was then attempted again, and still failed. This may be due to a broken CocoaPods installation. See: https://guides.cocoapods.org/using/troubleshooting.html for potential solutions.
#### Evidence:
Device log files, Network log file, etc.
**The full Unity console log is** :
OS framework addition failed due to a CocoaPods installation failure. This will will likely result in an non-functional Xcode project.

After the failure, "pod repo update" was executed and succeeded. "pod install" was then attempted again, and still failed. This may be due to a broken CocoaPods installation. See: https://guides.cocoapods.org/using/troubleshooting.html for potential solutions.

pod install output:

Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "mopub-ios-sdk/NativeAds":
  In Podfile:
    MoPub-AdMob-Adapters/Network (= 7.59.0.0) was resolved to 7.59.0.0, which depends on
      mopub-ios-sdk/NativeAds (~> 5.8)

None of your spec sources contain a spec satisfying the dependency: `mopub-ios-sdk/NativeAds (~> 5.8)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

    [33mWARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
    Consider adding the following to ~/.profile:

    export LANG=en_US.UTF-8
    [0m

pod repo update output:

Updating spec repo `cocoapods`
  $ /usr/bin/git -C /Users/fanzhengyong/.cocoapods/repos/cocoapods fetch origin --progress
  $ /usr/bin/git -C /Users/fanzhengyong/.cocoapods/repos/cocoapods rev-parse --abbrev-ref HEAD
  master
  $ /usr/bin/git -C /Users/fanzhengyong/.cocoapods/repos/cocoapods reset --hard origin/master
  HEAD is now at 89435769b1d [Add] WNJShareKit 0.1.10

    [33mWARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
    Consider adding the following to ~/.profile:

    export LANG=en_US.UTF-8
    [0m
  remote: Enumerating objects: 1        
  remote: Enumerating objects: 89, done.        
  remote: Counting objects:   1% (1/89)        
  remote: Counting objects:   2% (2/89)        
  remote: Counting objects:   3% (3/89)        
  remote: Counting objects:   4% (4/89)        
  remote: Counting objects:   5% (5/89)        
  remote: Counting objects:   6% (6/89)        
  remote: Counting objects:   7% (7/89)        
  remote: Counting objects:   8% (8/89)        
  remote: Counting objects:  10% (9/89)        
  remote: Counting objects:  11% (10/89)        
  remote: Counting objects:  12% (11/89)        
  remote: Counting objects:  13% (12/89)        
  remote: Counting objects:  14% (13/89)        
  remote: Counting objects:  15% (14/89)        
  remote: Counting objects:  16% (15/89)        
  remote: Counting objects:  17% (16/89)        
  remote: Counting objects:  19% (17/89)        
  remote: Counting objects:  20% (18/89)        
  remote: Counting objects:  21% (19/89)        
  remote: Counting objects:  22% (20/89)        
  remote: Counting objects:  23% (21/89)        
  remote: Counting objects:  24% (22/89)        
  remote: Counting objects:  25% (23/89)        
  remote: Counting objects:  26% (24/89)        
  remote: Counting objects:  28% (25/89)        
  remote: Counting objects:  29% (26/89)        
  remote: Counting objects:  30% (27/89)        
  remote: Counting objects:  31% (28/89)        
  remote: Counting objects:  32% (29/89)        
  remote: Counting objects:  33% (30/89)        
  remote: Counting objects:  34% (31/89)        
  remote: Counting objects:  35% (32/89)        
  remote: Counting objects:  37% (33/89)        
  remote: Counting objects:  38% (34/89)        
  remote: Counting objects:  39% (35/89)        
  remote: Counting objects:  40% (36/89)        
  remote: Counting objects:  41% (37/89)        
  remote: Counting objects:  42% (38/89)        
  remote: Counting objects:  43% (39/89)        
  remote: Counting objects:  44% (40/89)        
  remote: Counting objects:  46% (41/89)        
  remote: Counting objects:  47% (42/89)        
  remote: Counting objects:  48% (43/89)        
  remote: Counting objects:  49% (44/89)        
  remote: Counting objects:  50% (45/89)        
  remote: Counting objects:  51% (46/89)        
  remote: Counting objects:  52% (47/89)        
  remote: Counting objects:  53% (48/89)        
  remote: Counting objects:  55% (49/89)        
  remote: Counting objects:  56% (50/89)        
  remote: Counting objects:  57% (51/89)        
  remote: Counting objects:  58% (52/89)        
  remote: Counting objects:  59% (53/89)        
  remote: Counting objects:  60% (54/89)        
  remote: Counting objects:  61% (55/89)        
  remote: Counting objects:  62% (56/89)        
  remote: Counting objects:  64% (57/89)        
  remote: Counting objects:  65% (58/89)        
  remote: Counting objects:  66% (59/89)        
  remote: Counting objects:  67% (60/89)        
  remote: Counting objects:  68% (61/89)        
  remote: Counting objects:  69% (62/89)        
  remote: Counting objects:  70% (63/89)        
  remote: Counting objects:  71% (64/89)        
  remote: Counting objects:  73% (65/89)        
  remote: Counting objects:  74% (66/89)        
  remote: Counting objects:  75% (67/89)        
  remote: Counting objects:  76% (68/89)        
  remote: Counting objects:  77% (69/89)        
  remote: Counting objects:  78% (70/89)        
  remote: Counting objects:  79% (71/89)        
  remote: Counting objects:  80% (72/89)        
  remote: Counting objects:  82% (73/89)        
  remote: Counting objects:  83% (74/89)        
  remote: Counting objects:  84% (75/89)        
  remote: Counting objects:  85% (76/89)        
  remote: Counting objects:  86% (77/89)        
  remote: Counting objects:  87% (78/89)        
  remote: Counting objects:  88% (79/89)        
  remote: Counting objects:  89% (80/89)        
  remote: Counting objects:  91% (81/89)        
  remote: Counting objects:  92% (82/89)        
  remote: Counting objects:  93% (83/89)        
  remote: Counting objects:  94% (84/89)        
  remote: Counting objects:  95% (85/89)        
  remote: Counting objects:  96% (86/89)        
  remote: Counting objects:  97% (87/89)        
  remote: Counting objects:  98% (88/89)        
  remote: Counting objects: 100% (89/89)        
  remote: Counting objects: 100% (89/89), done.        
  remote: Compressing objects:   3% (1/29)        
  remote: Compressing objects:   6% (2/29)        
  remote: Compressing objects:  10% (3/29)        
  remote: Compressing objects:  13% (4/29)        
  remote: Compressing objects:  17% (5/29)        
  remote: Compressing objects:  20% (6/29)        
  remote: Compressing objects:  24% (7/29)        
  remote: Compressing objects:  27% (8/29)        
  remote: Compressing objects:  31% (9/29)        
  remote: Compressing objects:  34% (10/29)        
  remote: Compressing objects:  37% (11/29)        
  remote: Compressing objects:  41% (12/29)        
  remote: Compressing objects:  44% (13/29)        
  remote: Compressing objects:  48% (14/29)        
  remote: Compressing objects:  51% (15/29)        
  remote: Compressing objects:  55% (16/29)        
  remote: Compressing objects:  58% (17/29)        
  remote: Compressing objects:  62% (18/29)        
  remote: Compressing objects:  65% (19/29)        
  remote: Compressing objects:  68% (20/29)        
  remote: Compressing objects:  72% (21/29)        
  remote: Compressing objects:  75% (22/29)        
  remote: Compressing objects:  79% (23/29)        
  remote: Compressing objects:  82% (24/29)        
  remote: Compressing objects:  86% (25/29)        
  remote: Compressing objects:  89% (26/29)        
  remote: Compressing objects:  93% (27/29)        
  remote: Compressing objects:  96% (28/29)        
  remote: Compressing objects: 100% (29/29)        
  remote: Compressing objects: 100% (29/29), done.        
  remote: Total 63 (delta 40), reused 49 (delta 29), pack-reused 0        
  From https://github.com/CocoaPods/Specs
     f61685eeca9..89435769b1d  master     -> origin/master

UnityEngine.Debug:LogError(Object)
Google.Logger:Log(String, LogLevel) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/Logger.cs:103)
Google.IOSResolver:Log(String, Boolean, LogLevel) (at /Users/smiles/dev/src/unity-jar-resolver/source/IOSResolver/src/IOSResolver.cs:967)
Google.IOSResolver:OnPostProcessInstallPods(BuildTarget, String) (at /Users/smiles/dev/src/unity-jar-resolver/source/IOSResolver/src/IOSResolver.cs:2209)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
![Lark20200602-180311](https://user-images.githubusercontent.com/17681628/83507714-81398b00-a4fb-11ea-9cf2-67bfd01fd7df.png)

**Comment by hmertkahraman** [comment]
Hi @GITHUB243884919 ,

Thanks for reaching out to us about this. We'd like to request some additional details from you:

- The podfile that you try to execute install on
- A screenshot of the MoPub Manager that outlines the version information.

Thanks,
MoPub Team

**Comment by GITHUB243884919** [comment]
> * podfile



> Hi @GITHUB243884919 ,
> 
> Thanks for reaching out to us about this. We'd like to request some additional details from you:
> 
> * The podfile that you try to execute install on
> * A screenshot of the MoPub Manager that outlines the version information.
> 
> Thanks,
> MoPub Team



> Hi @GITHUB243884919 ,
> 
> Thanks for reaching out to us about this. We'd like to request some additional details from you:
> 
> * The podfile that you try to execute install on
> * A screenshot of the MoPub Manager that outlines the version information.
> 
> Thanks,
> MoPub Team
Thanks for you reply.
 I havn't excute podfile ,I just import Admob  and Facebook  audience by SDK manager. Should I need to do this ? and how to do this ?
![Lark20200602-225642](https://user-images.githubusercontent.com/17681628/83535737-e6ee3d00-a524-11ea-9b6c-fd743ea3701b.png)

**Comment by hmertkahraman** [comment]
Hi @GITHUB243884919 ,

Thanks for this information.

**Regarding the repro steps # 1:**
_1.Download mopub-unity-sdk and import to Unity Editor_
A fresh clone of this this should download the project with 5.12.1 the latest available. You mention your version is 5.10. We wonder how is this possible. Did you try pulling a fresh version, if not can you please retry with that?

**Regarding Podfile**
After selecting iOS as build target, under Build Settings, you would see the option to **Build** only. If you can use that, it will generate an XCode project on the designated destination. It will have a podfile in it that is not used yet at that point (`pod install` command has not been used on it yet), and so the pods shouldn't be installed, and xcode workspace should not be available yet.
Can you please share that podfile to us?

Thanks,
Mert

**Comment by hmertkahraman** [comment]
Hi @GITHUB243884919 ,

We **don't support Native ads on Unity** yet. That’s why CocoaPods complains 
```
None of your spec sources contain a spec satisfying the dependency: mopub-ios-sdk/NativeAds (~> 5.8).
```

Also, you're using MoPub SDK 5.10, which isn’t compatible with newer adapters you've installed because in 5.11.0, we separated Native Ads into its own CocoaPods component, [please see here](https://github.com/mopub/mopub-ios-sdk/commit/3f696fe2f8c6b529fa5e8c0587a98e9f62b9f8ad#diff-71ea80aabaa7320711c9cce9e8b4d3ecR56). Since newer adapters have a separate dependency on that native ad component, CocoaPods produces the error on MoPub SDK 5.10.

The quickest solution would be to upgrade to the MoPub SDK 5.11.0 (or newer).

Could you please upgrade and try again?

Thanks,
Mert

**Comment by GITHUB243884919** [comment]
> Hi @GITHUB243884919 ,
> 
> We **don't support Native ads on Unity** yet. That’s why CocoaPods complains
> 
> ```
> None of your spec sources contain a spec satisfying the dependency: mopub-ios-sdk/NativeAds (~> 5.8).
> ```
> 
> Also, you're using MoPub SDK 5.10, which isn’t compatible with newer adapters you've installed because in 5.11.0, we separated Native Ads into its own CocoaPods component, [please see here](https://github.com/mopub/mopub-ios-sdk/commit/3f696fe2f8c6b529fa5e8c0587a98e9f62b9f8ad#diff-71ea80aabaa7320711c9cce9e8b4d3ecR56). Since newer adapters have a separate dependency on that native ad component, CocoaPods produces the error on MoPub SDK 5.10.
> 
> The quickest solution would be to upgrade to the MoPub SDK 5.11.0 (or newer).
> 
> Could you please upgrade and try again?
> 
> Thanks,
> Mert

Thanks for your reply.
I upgraded mopub to 5.12.1 and import admob , Facebook again. but still error.
<img width="548" alt="107C6B9A80C1BA4D5EC6ABA743094A9F" src="https://user-images.githubusercontent.com/17681628/83613909-07ff6e00-a5b7-11ea-8652-292e6302ef24.png">
<img width="688" alt="B1C2E477BDB8963A9B7BEC8A04B2962D" src="https://user-images.githubusercontent.com/17681628/83613925-0f267c00-a5b7-11ea-975a-e0c6c518c20f.png">
<img width="714" alt="BE30BE82CA040F42FC711713EA6EB34B" src="https://user-images.githubusercontent.com/17681628/83613943-18174d80-a5b7-11ea-98a7-ad72f66149fc.png">

**Comment by GITHUB243884919** [comment]
I think maybe I cann't download them by cocoapods。 So I try to download admob and facebook audience SDK from web page.
1.I downloaded them from https://developers.google.com/admob/ios/download and https://developers.facebook.com/docs/audience-network/guides/adding-sdk/ios.
![Lark20200603-224528](https://user-images.githubusercontent.com/17681628/83651508-22077380-a5ec-11ea-9a2f-61688297e3ad.png)
![Lark20200603-224538](https://user-images.githubusercontent.com/17681628/83651547-2df33580-a5ec-11ea-9110-9e565011f7f6.png)

2.I modified the files AdMobDependencies.xml and AdMobPackageConfig.cs about admob version to  7.60.0. because the version of the download admob sdk  is 7.60.0 not 7.59
3.I seted the  IOS Resolver not to work
![Lark20200603-224603](https://user-images.githubusercontent.com/17681628/83651764-6dba1d00-a5ec-11ea-98f5-f4702a66a602.png)

ok~ The Unity build to ios zero error.
![Lark20200603-224621](https://user-images.githubusercontent.com/17681628/83652332-12d4f580-a5ed-11ea-9092-d4bf150c66d6.png)
 
**But I cann't build it in Xcode. There are many error about mopub.**
I try to test mopub sdk 5.10.0 and 5.12.1. but I meet the same error.

![Lark20200603-224630](https://user-images.githubusercontent.com/17681628/83652037-beca1100-a5ec-11ea-8142-6beb07e93399.png)

**Comment by GITHUB243884919** [comment]
I think my problem is why mopub is not support arm64? I need setting something? hope your reply

**Comment by hmertkahraman** [comment]
Hi @GITHUB243884919 ,

Thanks for all the info you sent. Here are our responses below:

**Note**
Firstly, we understand you also opened #120 , which is actually an extension of this issue. Let's continue our conversation here instead of #120 so we can be on the same page.

**Recap of your issue / responses to your questions**
_You should be able to have MoPub work flawlessly:_
1. Download mopub-unity-sdk and import to Unity Editor
3. Use Mopub SDK manager import AdMob and Facebook audience
4. Switch to IOS and build

Then you [mentioned](https://github.com/mopub/mopub-unity-sdk/issues/119#issuecomment-638253894):
"I think maybe I cann't download them by cocoapods。 So I try to download admob and facebook audience SDK from web page."
Which should not be necessary at all. 

**ARM 64**
Moreover, these are the architectures we support, [you can find it here](https://github.com/mopub/mopub-ios-sdk/blob/01105fa081855b1b71316791d03c927be7ebc92b/MoPubSDK/MoPubSDK.xcconfig#L12):
```
// Valid Architectures
VALID_ARCHS = arm64 arm64e armv7 armv7s i386 x86_64
VALID_ARCHS[sdk=iphoneos*] = arm64 arm64e armv7 armv7s
VALID_ARCHS[sdk=iphonesimulator*] = i386 x86_64
```
You can see that `arm64` is supported. So the issue about arm64 should be from something else. But let's focus on integrating AdMob and FAN properly from Cocoapods.

**Our Recommendation**
We'd like to walk you through properly installing networks and adapters through Cocoapods without changing any dependency settings and XMLs.

**Directions**
1- Can you please setup a fresh clone of our [Unity sample app](https://github.com/mopub/mopub-unity-sdk/tree/master/unity-sample-app).
Then let's just concentrate on running that version, without installing AdMob and Facebook, on your iOS device. We should ensure the main MoPub SDK works fine, and then focus on the networks later.

2- After you clone, go to build settings, select iOS, set the scene to demo scene, uncheck options, and only hit **Build**. This will export an Xcode project without any Cocoapods content (so not Xcode workspace which contains pods).
<img width="635" alt="Screenshot 2020-06-04 at 14 49 19" src="https://user-images.githubusercontent.com/47573140/83753261-a4d31180-a672-11ea-8e6d-09c30d6f43e8.png">

3- After this, navigate to the folder you exported this xcode project. Find the Podfile in its root. 
![image](https://user-images.githubusercontent.com/47573140/83753377-d3e98300-a672-11ea-825d-7b9e6b9b48f1.png)

4- Open a terminal command at that directory. Run the command: `pod install`

You should see:
```
Fetching podspec for `MoPub-SDK-Plugin` from `/Users/hmertkahraman/mopub-unity-sdk/unity-sample-app/Assets/MoPub/Plugins/iOS`
Downloading dependencies
Using MoPub-SDK-Plugin (5.12.1)
Using mopub-ios-sdk (5.12.1)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 2 dependencies from the Podfile and 2 total pods installed.
```

5- After doing this you should open the Xcode Workspace that has the pods in it (not Xcode project that doesn't have the pods in it). So open this one:
![image](https://user-images.githubusercontent.com/47573140/83753686-68ec7c00-a673-11ea-9f85-f5922549ef7e.png)

6- Then run it on a device and test if this works.

7- Go back to Unity, only install one of AdMob or FAN. Then redo the steps.

**If you can't do these, please let us know at what step you failed. Send us the details, especially the terminal output on pod installation**

-----------

Something to note here is that, on your podfile, there should be the entry for our plugin like this:
`pod 'MoPub-SDK-Plugin', :path => '/Users/hmertkahraman/mopub-unity-sdk/unity-sample-app/Assets/MoPub/Plugins/iOS'`
This points to the Podspec file that contains iOS plugin info. For my example, it is located here:
![image](https://user-images.githubusercontent.com/47573140/83753634-55d9ac00-a673-11ea-8c62-a5316f56deb6.png)
Can you also double check if yours is located on the correct path, and also send us the file so we can double check?

Thanks,
Mert

**Comment by GITHUB243884919** [comment]
> Hi @GITHUB243884919 ,
> 
> Thanks for all the info you sent. Here are our responses below:
> 
> **Note**
> Firstly, we understand you also opened #120 , which is actually an extension of this issue. Let's continue our conversation here instead of #120 so we can be on the same page.
> 
> **Recap of your issue / responses to your questions**
> _You should be able to have MoPub work flawlessly:_
> 
> 1. Download mopub-unity-sdk and import to Unity Editor
> 2. Use Mopub SDK manager import AdMob and Facebook audience
> 3. Switch to IOS and build
> 
> Then you [mentioned](https://github.com/mopub/mopub-unity-sdk/issues/119#issuecomment-638253894):
> "I think maybe I cann't download them by cocoapods。 So I try to download admob and facebook audience SDK from web page."
> Which should not be necessary at all.
> 
> **ARM 64**
> Moreover, these are the architectures we support, [you can find it here](https://github.com/mopub/mopub-ios-sdk/blob/01105fa081855b1b71316791d03c927be7ebc92b/MoPubSDK/MoPubSDK.xcconfig#L12):
> 
> ```
> // Valid Architectures
> VALID_ARCHS = arm64 arm64e armv7 armv7s i386 x86_64
> VALID_ARCHS[sdk=iphoneos*] = arm64 arm64e armv7 armv7s
> VALID_ARCHS[sdk=iphonesimulator*] = i386 x86_64
> ```
> 
> You can see that `arm64` is supported. So the issue about arm64 should be from something else. But let's focus on integrating AdMob and FAN properly from Cocoapods.
> 
> **Our Recommendation**
> We'd like to walk you through properly installing networks and adapters through Cocoapods without changing any dependency settings and XMLs.
> 
> **Directions**
> 1- Can you please setup a fresh clone of our [Unity sample app](https://github.com/mopub/mopub-unity-sdk/tree/master/unity-sample-app).
> Then let's just concentrate on running that version, without installing AdMob and Facebook, on your iOS device. We should ensure the main MoPub SDK works fine, and then focus on the networks later.
> 
> 2- After you clone, go to build settings, select iOS, set the scene to demo scene, uncheck options, and only hit **Build**. This will export an Xcode project without any Cocoapods content (so not Xcode workspace which contains pods).
> <img alt="Screenshot 2020-06-04 at 14 49 19" width="635" src="https://user-images.githubusercontent.com/47573140/83753261-a4d31180-a672-11ea-8e6d-09c30d6f43e8.png">
> 
> 3- After this, navigate to the folder you exported this xcode project. Find the Podfile in its root.
> ![image](https://user-images.githubusercontent.com/47573140/83753377-d3e98300-a672-11ea-825d-7b9e6b9b48f1.png)
> 
> 4- Open a terminal command at that directory. Run the command: `pod install`
> 
> You should see:
> 
> ```
> Fetching podspec for `MoPub-SDK-Plugin` from `/Users/hmertkahraman/mopub-unity-sdk/unity-sample-app/Assets/MoPub/Plugins/iOS`
> Downloading dependencies
> Using MoPub-SDK-Plugin (5.12.1)
> Using mopub-ios-sdk (5.12.1)
> Generating Pods project
> Integrating client project
> Sending stats
> Pod installation complete! There are 2 dependencies from the Podfile and 2 total pods installed.
> ```
> 
> 5- After doing this you should open the Xcode Workspace that has the pods in it (not Xcode project that doesn't have the pods in it). So open this one:
> ![image](https://user-images.githubusercontent.com/47573140/83753686-68ec7c00-a673-11ea-9f85-f5922549ef7e.png)
> 
> 6- Then run it on a device and test if this works.
> 
> 7- Go back to Unity, only install one of AdMob or FAN. Then redo the steps.
> 
> **If you can't do these, please let us know at what step you failed. Send us the details, especially the terminal output on pod installation**
> 
> Something to note here is that, on your podfile, there should be the entry for our plugin like this:
> `pod 'MoPub-SDK-Plugin', :path => '/Users/hmertkahraman/mopub-unity-sdk/unity-sample-app/Assets/MoPub/Plugins/iOS'`
> This points to the Podspec file that contains iOS plugin info. For my example, it is located here:
> ![image](https://user-images.githubusercontent.com/47573140/83753634-55d9ac00-a673-11ea-8c62-a5316f56deb6.png)
> Can you also double check if yours is located on the correct path, and also send us the file so we can double check?
> 
> Thanks,
> Mert

Thank you very much for your patience and detailed reply。At #120 I can run app without Admob and Facebook. I will try to import Admob and Facebook SDKs. I will come here tell you result.
