### ISSUE TITLE
Unity IOS=>XCode :undfined symbols for architecture arm64 Or library not found for -lMoPub-SDK-Plugin

### ISSUE THREAD

**Issue by GITHUB243884919** [mopub/mopub-unity-sdk#120]
One line summary of the issue here

- [ ] I am submitting a bug report for existing functionality
- [ ] I visited https://developers.mopub.com/ and found no answer
- [ ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ ] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.
1.Download mopub-unity-sdk and import to Unity Editor
2.Add the mopub's MopubDemoScene in sdk to building setting
3.let IOS Reslover not work
![Lark20200603-224603](https://user-images.githubusercontent.com/17681628/83706168-66752c80-a649-11ea-973d-a808689ae13f.png)

4.IOS Build il2cpp To XCode successed
![Lark20200604-100601](https://user-images.githubusercontent.com/17681628/83706823-0da69380-a64b-11ea-8f54-ca84f9f9135b.png)
5.Build in XCode : Many build error about arm64
6.Remove arm64 from XCode buildsetting：Build successed。
![Lark20200604-012758](https://user-images.githubusercontent.com/17681628/83706319-bf44c500-a649-11ea-9b02-a94d46eb9492.png)
7.In step 3, I let IOS Resolver to work and build in XCode, it will be meet: library not found for -lMoPub-SDK-Plugin
![Lark20200604-111206](https://user-images.githubusercontent.com/17681628/83710990-a097fb80-a654-11ea-9765-469ba3a2a6b0.png)

![Lark20200604-111547](https://user-images.githubusercontent.com/17681628/83711061-ca512280-a654-11ea-9cfd-8b8b4ca7f84d.png)

#### Expected behavior:
As concisely as possible, describe the expected behavior.

#### Observed behavior:
As concisely as possible, describe the observed behavior.
There is many link error about mopub arm64。I have  tested mopub sdk 5.10.0 and 5.12.1，same error。It seems like admob is not builded to arm64? how to do this? 
![Lark20200603-224630](https://user-images.githubusercontent.com/17681628/83706390-e7ccbf00-a649-11ea-80b3-e723f9842eda.png)

#### Evidence:
Device log files, Network log file, etc.
![Lark20200604-003847](https://user-images.githubusercontent.com/17681628/83706411-f5824480-a649-11ea-99fc-37b99788c547.png)

**Comment by GITHUB243884919** [comment]
Oh I resolved this problem.
I need to open Unity-iPhone.xcworkspace, is not Unity-iPhone.xcodeproj.
![Lark20200604-113759](https://user-images.githubusercontent.com/17681628/83712253-e4d8cb00-a657-11ea-8872-b6cb16e85bc2.png)
But when I open app in my ipad, If I checked Quest Reward  then show error .
![Lark20200604-114514](https://user-images.githubusercontent.com/17681628/83712681-e22aa580-a658-11ea-846f-6c65e3a26452.jpeg)

**Comment by chauduyphanvu** [comment]
This issue is resolved. The new issue is tracked on https://github.com/mopub/mopub-unity-sdk/issues/119.
