### ISSUE TITLE
FAN Banner displays wrong when using ScreenWidthHeight90

### ISSUE THREAD

**Issue by PhucDuy** [mopub/mopub-unity-sdk#121]
One-line summary of the issue here
I have some trouble with a FAN banner displaying after we integrate Mopub unity SDK to our game. 
Please see attachments
- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.12.0
#### Device model and OS Version:
iPhone X 
Android devices with resolution 18:9 (The screenshots was taken in Redmi 8a)
Android devices with resolution 18:10 
#### Unity Version:
2018.4.21f1

#### Ad Unit IDs used in reproducing the issue:
iOs: d1f4b33f60e740e1a49af153fbb0aa8c
Android: 550f461444f943cc96b591d636ac8f5f

#### Steps to reproduce the behavior:
I requested banners with “MoPub.AdPosition.BottomCenter” and “MoPub.MaxAdSize.ScreenWidthHeight90”
I've used 4 ad network Unity, Admob, FAN, Marketplace. FAN banners were stretched. It's only occurred in FAN Banner.

#### Expected behavior:
FAN banners should display well. 

#### Observed behavior:
FAN banners were stretched or cropped.

#### Evidence:
![Image from iOS](https://user-images.githubusercontent.com/6514068/83770020-c2bc6880-a6aa-11ea-841f-c69e833c5923.jpeg)
![Image from iOS (2)-2](https://user-images.githubusercontent.com/6514068/83770032-c6e88600-a6aa-11ea-9139-7f43dce85207.jpeg)
![Image from iOS (1)](https://user-images.githubusercontent.com/6514068/83770042-cb14a380-a6aa-11ea-86e8-4a0ecae5d083.jpeg)
Tested on Mopub sample app.
![98616039_2687194821605482_2245298238221451264_n](https://user-images.githubusercontent.com/6514068/83770143-e97a9f00-a6aa-11ea-9b22-c4bc9048aed9.jpeg)

**Comment by chauduyphanvu** [comment]
@PhucDuy, thanks for letting us know! 

What you are seeing is an expected behavior. You are requesting banners using the `ScreenWidthHeight90` size, which is the max ad size. The creative that Facebook returns to you (in your screenshot) is still within that size constraint (even though it looks cropped to the human eyes, it still displays in its entirety).

This is what I got from my console logs (you can compare with logs from your devices):

```
Unity: [MoPub-Unity] [RequestBanner] Size requested: 411.4286x90
Unity: [MoPub-Unity] [EmitAdLoadedEvent] Size received: 411x90
```

Looking at the [Facebook adapter code](https://github.com/mopub/mopub-android-mediation/blob/master/FacebookAudienceNetwork/src/main/java/com/mopub/mobileads/FacebookBanner.java#L225-L226), we map the `ScreenWidthHeight90` you request to `BANNER_HEIGHT_90` from Facebook.

If this is not an ideal UI for your app, we recommend using `ScreenWidthHeight50` for your ad requests with Facebook line items. Let us know if you have any questions!

Vu Chau
MoPub Team

**Comment by PhucDuy** [comment]
Actually, after I changed to 'ScreenWidthHeight50' the banner is still cropped.
It is a screenshot of iPhone 7Plus. I occurred after the banner changed from 300x50 banner to FAN Banner.
![IMG_1788](https://user-images.githubusercontent.com/6514068/83931893-6439dc00-a7c9-11ea-9be6-5d630c454a11.PNG)

In addition, the banner is still cropped in iPad.
![IMG_1957](https://user-images.githubusercontent.com/6514068/83931930-9ea37900-a7c9-11ea-8bcc-2e632e2cf989.PNG)
![IMG_1956](https://user-images.githubusercontent.com/6514068/83931942-b844c080-a7c9-11ea-985e-551dfd062ea8.PNG)

Here is my setup code.
`      
if (IsIpad() || isIphoneX() || isSpecialResolution()) {
        MoPub.RequestBanner(adUnitId, MoPub.AdPosition.BottomCenter, MoPub.MaxAdSize.ScreenWidthHeight90);
      } else {
        MoPub.RequestBanner(adUnitId, MoPub.AdPosition.BottomCenter, MoPub.MaxAdSize.ScreenWidthHeight50);
      }
`

**Comment by chauduyphanvu** [comment]
@PhucDuy, 

Do you have console logs from the MoPub SDK that tell you the size requested vs. the size received? Similar to how it is for me:

```
Unity: [MoPub-Unity] [RequestBanner] Size requested: 411.4286x90
Unity: [MoPub-Unity] [EmitAdLoadedEvent] Size received: 411x90
```

<img width="413" alt="Screen Shot 2020-06-08 at 6 31 27 PM" src="https://user-images.githubusercontent.com/25616035/84086693-7331b180-a9b6-11ea-947a-667daeca3221.png">

Looking at your code snippet, would `ScreenWidthHeight50` be a better fit when `isSpecialResolution()` is the case? Also, according to [Facebook's documentation](https://developers.facebook.com/docs/audience-network/guides/ad-formats/banner/ios#load), 250 is the best ad size to use. Would you be able to try with 250?

**Comment by chauduyphanvu** [comment]
Closing for now as this is not reproducible on our end. Let us know if you still need any assistance.
