### ISSUE TITLE
 Unity IOS：Step by Step by #120, pod can install admob ,but can not install facebook.

### ISSUE THREAD

**Issue by GITHUB243884919** [mopub/mopub-unity-sdk#122]
One line summary of the issue here

- [ ] I am submitting a bug report for existing functionality
- [ ] I visited https://developers.mopub.com/ and found no answer
- [ ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ ] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.
1.Download mopub-unity-sdk and import to Unity Editor
2.Use Mopub SDK manager import AdMob and Facebook audience
3.Switch to IOS and build Unity console shows error
<img width="527" alt="截屏2020-06-07 下午1 12 39" src="https://user-images.githubusercontent.com/17681628/83960891-a2fe8d80-a8c0-11ea-88f1-e95246279235.png">
4.Enter the folder of export XCode and type : pod install 
<img width="585" alt="截屏2020-06-07 下午1 15 30" src="https://user-images.githubusercontent.com/17681628/83960937-0092da00-a8c1-11ea-8dec-f2a156ea940b.png">
5.If I modify the podfile to disable about Facebook then It's ok
<img width="664" alt="截屏2020-06-07 下午1 58 30" src="https://user-images.githubusercontent.com/17681628/83961565-0390c900-a8c7-11ea-8836-67601f5bc94b.png">
<img width="565" alt="截屏2020-06-07 下午1 31 11" src="https://user-images.githubusercontent.com/17681628/83961571-0c819a80-a8c7-11ea-83be-e6e8f74a8909.png">

6.It's seem like I cann't use pod to install Facebook SDK。But I can download 
https://developers.facebook.com/resources/FBAudienceNetwork-5.9.0.zip  by Chrome.
This url is I copy from pod command output. What should I do？
<img width="691" alt="截屏2020-06-07 下午1 21 03" src="https://user-images.githubusercontent.com/17681628/83961026-ed343e80-a8c1-11ea-9b97-4c9a7e0a8a3d.png">
<img width="327" alt="截屏2020-06-07 下午1 21 24" src="https://user-images.githubusercontent.com/17681628/83961034-f9200080-a8c1-11ea-9344-dd090cc8b2bd.png">

#### Expected behavior:
As concisely as possible, describe the expected behavior.

#### Observed behavior:
As concisely as possible, describe the observed behavior.

#### Evidence:
Device log files, Network log file, etc.

**Comment by GITHUB243884919** [comment]
OMG！！！ I  resolved this problem.  This is not a bug of mopub or facebook. This is about how to use VPN. Let cocoapods work right need to let our Mac could use VPN from command and git also. In fact， I can use cocoapods build mopub+admob without VPN。That is why I can use cocoapods get admob。
I am an old friend of mopub。 I meet a problem about half years ago. Our platform is Android at that time。At last， that problem also about how to use VPN。I remmber   your guy chauduyphanvu help me。Nice to meet you～ Thank you very much～ 
<img width="595" alt="截屏2020-06-07 下午8 05 28" src="https://user-images.githubusercontent.com/17681628/83968227-428c4200-a8fa-11ea-97fa-4518f45a227d.png">

**Comment by hmertkahraman** [comment]
Thank you for your response. We will also close the original issue #119
