### ISSUE TITLE
Unity(iOS) linker error

### ISSUE THREAD

**Issue by BacheyG** [mopub/mopub-unity-sdk#123]
I added mopub sdk using the sdk manager to my unity project. When I attempt to build my project in xcode I get these linker errors:
How do I fix these @chauduyphanvu ?

`Undefined symbols for architecture arm64:
  "__moPubShowRewardedVideo", referenced from:
      _MoPubiOSAdUnit__moPubShowRewardedVideo_m45032B00D3FADDC5AF1DBAFED18B385DEE2AD75D in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOSAdUnit__moPubShowRewardedVideo_m45032B00D3FADDC5AF1DBAFED18B385DEE2AD75D)
  "__moPubIsInterstitialReady", referenced from:
      _MoPubiOSAdUnit_IsInterstitialReady_m9F60767759CDB174ED06CC231A891977C89D42C1 in Assembly-CSharp1.o
      _MoPubiOSAdUnit__moPubIsInterstitialReady_mC3EB6A0DC406AE9048BFDC710C582CFACE8E06C6 in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOSAdUnit__moPubIsInterstitialReady_mC3EB6A0DC406AE9048BFDC710C582CFACE8E06C6)
  "__moPubForceRefresh", referenced from:
      _MoPubiOSAdUnit_ForceRefresh_m049A49C4D3A6935444993FD8AA34D555DE5BD174 in Assembly-CSharp1.o
      _MoPubiOSAdUnit__moPubForceRefresh_m4B27C2C99051D2E1C947A4C797540BCB1044B11E in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOSAdUnit__moPubForceRefresh_m4B27C2C99051D2E1C947A4C797540BCB1044B11E)
  "__moPubSetAutorefreshEnabled", referenced from:
      _MoPubiOSAdUnit_SetAutorefresh_mF975D63C4047BDFEFEF735E901B9903A0C69645D in Assembly-CSharp1.o
      _MoPubiOSAdUnit__moPubSetAutorefreshEnabled_m59F6029B3B53FFA8A1CDC360DFF5A5E5D9837EF2 in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOSAdUnit__moPubSetAutorefreshEnabled_m59F6029B3B53FFA8A1CDC360DFF5A5E5D9837EF2)
  "__moPubRefreshBanner", referenced from:
      _MoPubiOSAdUnit__moPubRefreshBanner_mF190BFF4B7BD8ECE7F9230715862B871351B4F10 in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOSAdUnit__moPubRefreshBanner_mF190BFF4B7BD8ECE7F9230715862B871351B4F10)
  "__moPubRequestBanner", referenced from:
      _MoPubiOSAdUnit_RequestBanner_mB42E8A3668EF301239CA6E245ECC8E4F2E1DD6C5 in Assembly-CSharp1.o
      _MoPubiOSAdUnit__moPubRequestBanner_mDE74B22732C9D6584962E98107E13DED37517A3D in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOSAdUnit__moPubRequestBanner_mDE74B22732C9D6584962E98107E13DED37517A3D)
  "__moPubIsPluginReady", referenced from:
      _MoPubiOSAdUnit_IsPluginReady_mAECC0C180B00373D8818A5871ABD3AEE23A62515 in Assembly-CSharp1.o
      _MoPubiOSAdUnit__moPubIsPluginReady_m023BBE9043A56CD0A5E69B2725CF4ECDAD356EF0 in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOSAdUnit__moPubIsPluginReady_m023BBE9043A56CD0A5E69B2725CF4ECDAD356EF0)
  "__moPubPreviouslyConsentedVendorListVersion", referenced from:
      _MoPubiOS_get_PreviouslyConsentedVendorListVersion_mEAFA4100D3D9E54D9076D03128B8B6650A264F2F in Assembly-CSharp1.o
      _MoPubiOS__moPubPreviouslyConsentedVendorListVersion_m4188F4B2463EE5A9EC42A8D92B7AE1D1F604350C in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOS__moPubPreviouslyConsentedVendorListVersion_m4188F4B2463EE5A9EC42A8D92B7AE1D1F604350C)
  "__moPubPreviouslyConsentedPrivacyPolicyVersion", referenced from:
      _MoPubiOS_get_PreviouslyConsentedPrivacyPolicyVersion_m295DD1124DEDF7332CCAD2212B8B532147493150 in Assembly-CSharp1.o
      _MoPubiOS__moPubPreviouslyConsentedPrivacyPolicyVersion_m99ADAA9E444391D1259E3CAF705C7C9209FE10FD in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOS__moPubPreviouslyConsentedPrivacyPolicyVersion_m99ADAA9E444391D1259E3CAF705C7C9209FE10FD)
  "__moPubPreviouslyConsentedIabVendorListFormat", referenced from:
      _MoPubiOS_get_PreviouslyConsentedIabVendorListFormat_mC17E8F040D90E6116DE8C039489C2B3B878289F3 in Assembly-CSharp1.o
      _MoPubiOS__moPubPreviouslyConsentedIabVendorListFormat_m6228722C98EB1E46DAEABEECEC41DD4A80951006 in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOS__moPubPreviouslyConsentedIabVendorListFormat_m6228722C98EB1E46DAEABEECEC41DD4A80951006)
  "__moPubCurrentConsentVendorListVersion", referenced from:
      _MoPubiOS_get_CurrentConsentVendorListVersion_m95523ED917D1132214F95A6E02F44619CE2526C3 in Assembly-CSharp1.o
      _MoPubiOS__moPubCurrentConsentVendorListVersion_m3A82CB74089A80B175AF8562616E176EF1B3530D in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOS__moPubCurrentConsentVendorListVersion_m3A82CB74089A80B175AF8562616E176EF1B3530D)
  "__moPubCurrentConsentIabVendorListFormat", referenced from:
      _MoPubiOS_get_CurrentConsentIabVendorListFormat_m0EFA5895BDC3F722D820BA884141035289FF0257 in Assembly-CSharp1.o
      _MoPubiOS__moPubCurrentConsentIabVendorListFormat_m9DAC1B1AF96810F46478A90F6E7E7DAE101AD410 in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOS__moPubCurrentConsentIabVendorListFormat_m9DAC1B1AF96810F46478A90F6E7E7DAE101AD410)
  "__moPubDestroyInterstitialAd", referenced from:
      _MoPubiOSAdUnit_DestroyInterstitialAd_m31AD83B89EEB6689F889C433086AA7B952A36BA4 in Assembly-CSharp1.o
      _MoPubiOSAdUnit__moPubDestroyInterstitialAd_m5B4856E91C5C31CC55A69088BC20F0EED119B831 in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOSAdUnit__moPubDestroyInterstitialAd_m5B4856E91C5C31CC55A69088BC20F0EED119B831)
  "__moPubCurrentConsentPrivacyPolicyUrl", referenced from:
      _MoPubiOS__moPubCurrentConsentPrivacyPolicyUrl_m6A1FCC108B8096C1A6CD38A4E05B7663BEAB3B7C in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOS__moPubCurrentConsentPrivacyPolicyUrl_m6A1FCC108B8096C1A6CD38A4E05B7663BEAB3B7C)
  "__mopubHasRewardedVideo", referenced from:
      _MoPubiOSAdUnit_HasRewardedVideo_mEB2CB25E73AC2E81CE4F8868A1072BE9D3ABFB96 in Assembly-CSharp1.o
      _MoPubiOSAdUnit__mopubHasRewardedVideo_mCA0290887CAAEDD89DEE6AF6F8689CAC2086EB40 in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOSAdUnit__mopubHasRewardedVideo_mCA0290887CAAEDD89DEE6AF6F8689CAC2086EB40)
  "__moPubRequestRewardedVideo", referenced from:
      _MoPubiOSAdUnit__moPubRequestRewardedVideo_m73EF77C5FF3610CF15762A03E0DF65BA90B93419 in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOSAdUnit__moPubRequestRewardedVideo_m73EF77C5FF3610CF15762A03E0DF65BA90B93419)
  "__moPubIsSdkInitialized", referenced from:
      _MoPubiOS_get_IsSdkInitialized_m7F0F284FDC734EF6A070F13A3583738AE17DABBA in Assembly-CSharp1.o
      _MoPubiOS__moPubIsSdkInitialized_m61763E8FCA8E009461159D9C9C92AF01FC12C6B9 in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOS__moPubIsSdkInitialized_m61763E8FCA8E009461159D9C9C92AF01FC12C6B9)
  "__moPubGetSDKVersion", referenced from:
      _MoPubiOS_get_SdkName_m15AAEC7157DFA0F3558DE9DF801F1FAB0F328666 in Assembly-CSharp1.o
      _MoPubiOS__moPubGetSDKVersion_m022D3329E5F54AAEED5CB35334DCCDC60CF7311E in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOS__moPubGetSDKVersion_m022D3329E5F54AAEED5CB35334DCCDC60CF7311E)
  "__moPubForceGDPRApplicable", referenced from:
      _MoPubiOS_ForceGdprApplicable_mCCE931A8EE82361F6C6566D0A12704A18D5FADD4 in Assembly-CSharp1.o
      _MoPubiOS__moPubForceGDPRApplicable_mE1E857E9851A860946E96EACE220F40FCEBCA95C in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOS__moPubForceGDPRApplicable_mE1E857E9851A860946E96EACE220F40FCEBCA95C)
  "__moPubDestroyBanner", referenced from:
      _MoPubiOSAdUnit_DestroyBanner_m2DC6D555DF8F2C03DAB3F9C318EED323EF30BC18 in Assembly-CSharp1.o
      _MoPubiOSAdUnit__moPubDestroyBanner_mBEF6C8788D53849E03E0736304305F18C89D0889 in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOSAdUnit__moPubDestroyBanner_mBEF6C8788D53849E03E0736304305F18C89D0889)
  "__moPubEnableLocationSupport", referenced from:
      _MoPubiOS_EnableLocationSupport_mBC76CAB4D27C13EBB95D1E0B413C02EDF6D4A30D in Assembly-CSharp1.o
      _MoPubiOS__moPubEnableLocationSupport_mD197AF819952E6099E285909B531EDEFC4C971B5 in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOS__moPubEnableLocationSupport_mD197AF819952E6099E285909B531EDEFC4C971B5)
  "__moPubAllowLegitimateInterest", referenced from:
      _MoPubiOS_get_AllowLegitimateInterest_mC13DA082B29A559547F4FB86AFF7D76CCBB875BE in Assembly-CSharp1.o
      _MoPubiOS__moPubAllowLegitimateInterest_mD2D810C1AEE5257C2FD8B09C838979291297E9C8 in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOS__moPubAllowLegitimateInterest_mD2D810C1AEE5257C2FD8B09C838979291297E9C8)
  "__moPubSetAllowLegitimateInterest", referenced from:
      _MoPubiOS_set_AllowLegitimateInterest_mF763C347F36D409B866C2D4564F06A0B82D926F7 in Assembly-CSharp1.o
      _MoPubiOS__moPubSetAllowLegitimateInterest_m1B5FC0136E519EA0370C55DACF10CD3AB9B834DD in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOS__moPubSetAllowLegitimateInterest_m1B5FC0136E519EA0370C55DACF10CD3AB9B834DD)
  "__moPubShowConsentDialog", referenced from:
      _MoPubiOS_ShowConsentDialog_m5C3BE4BC987EF42A8B4743D9CA2D2FC1F031C504 in Assembly-CSharp1.o
      _MoPubiOS__moPubShowConsentDialog_m4B95450F07B44C410ED0D5269651B0FBDB26A55A in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOS__moPubShowConsentDialog_m4B95450F07B44C410ED0D5269651B0FBDB26A55A)
  "__moPubShowInterstitialAd", referenced from:
      _MoPubiOSAdUnit_ShowInterstitialAd_m9EA1F92492B0B1378CCB4FCA1107A5F902B2BE87 in Assembly-CSharp1.o
      _MoPubiOSAdUnit__moPubShowInterstitialAd_m854C8F0A141D52A026F45E9DC11E201610AB1438 in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOSAdUnit__moPubShowInterstitialAd_m854C8F0A141D52A026F45E9DC11E201610AB1438)
  "__moPubLoadConsentDialog", referenced from:
      _MoPubiOS_LoadConsentDialog_m2377071A030C7143F6866FC5E3B95C5F5FC99537 in Assembly-CSharp1.o
      _MoPubiOS__moPubLoadConsentDialog_m5FA6C2CAD851BCE45EE67ED873BE7481FFE9D85A in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOS__moPubLoadConsentDialog_m5FA6C2CAD851BCE45EE67ED873BE7481FFE9D85A)
  "__moPubIsGDPRApplicable", referenced from:
      _MoPubiOS_get_IsGdprApplicable_mB57AA5A479E9BF3AC0E8258EB8BE9D1EE689B444 in Assembly-CSharp1.o
      _MoPubiOS__moPubIsGDPRApplicable_m771CAFCF7AE808C95F9763BFA3A455500749178B in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOS__moPubIsGDPRApplicable_m771CAFCF7AE808C95F9763BFA3A455500749178B)
  "__moPubCurrentConsentStatus", referenced from:
      _MoPubiOS_get_CurrentConsentStatus_m55E719F1BFDCC264AA8722C51D938FD7CE45F56A in Assembly-CSharp1.o
      _MoPubiOS__moPubCurrentConsentStatus_mBD59EFC1D7C919C6978E8955BD940CD32A5B04B8 in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOS__moPubCurrentConsentStatus_mBD59EFC1D7C919C6978E8955BD940CD32A5B04B8)
  "__moPubForceWKWebView", referenced from:
      _MoPubiOS_ForceWKWebView_mBA7895DF35370DDD4EA37DDBD760B142E7984064 in Assembly-CSharp1.o
      _MoPubiOS__moPubForceWKWebView_mF83BB798C223DCC631777BF80274EF0FAB79ECA2 in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOS__moPubForceWKWebView_mF83BB798C223DCC631777BF80274EF0FAB79ECA2)
  "__moPubCurrentConsentPrivacyPolicyVersion", referenced from:
      _MoPubiOS_get_CurrentConsentPrivacyPolicyVersion_mCE68CE5C7C9FF1F00CAC9A2B7A8C4025504D9030 in Assembly-CSharp1.o
      _MoPubiOS__moPubCurrentConsentPrivacyPolicyVersion_m6044485F7101C1EF7E89687BD060224875B9FE8C in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOS__moPubCurrentConsentPrivacyPolicyVersion_m6044485F7101C1EF7E89687BD060224875B9FE8C)
  "__moPubCurrentConsentVendorListUrl", referenced from:
      _MoPubiOS__moPubCurrentConsentVendorListUrl_mAF2F0D71E0C1D5C912E919D7838545914B473307 in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOS__moPubCurrentConsentVendorListUrl_mAF2F0D71E0C1D5C912E919D7838545914B473307)
  "__moPubRequestInterstitialAd", referenced from:
      _MoPubiOSAdUnit__moPubRequestInterstitialAd_mD53BF2657CA9B0F147A2238B9377AF3F69F6F4BF in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOSAdUnit__moPubRequestInterstitialAd_mD53BF2657CA9B0F147A2238B9377AF3F69F6F4BF)
  "__moPubGrantConsent", referenced from:
      _MoPubiOS_GrantConsent_mFF9D80376AC3809EE8D381E70706C2C9CA92888B in Assembly-CSharp1.o
      _MoPubiOS__moPubGrantConsent_mF6467CCC0DD6F83E84A18B398B6CE36294F6DB18 in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOS__moPubGrantConsent_mF6467CCC0DD6F83E84A18B398B6CE36294F6DB18)
  "__moPubCanCollectPersonalInfo", referenced from:
      _MoPubiOS_get_CanCollectPersonalInfo_m8AFA56DBF67F6DAE6B6D03F9120F93CA33B04099 in Assembly-CSharp1.o
      _MoPubiOS__moPubCanCollectPersonalInfo_mC58A4F607D53162ACA428D1C80F6C079626CCA6A in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOS__moPubCanCollectPersonalInfo_mC58A4F607D53162ACA428D1C80F6C079626CCA6A)
  "__moPubRevokeConsent", referenced from:
      _MoPubiOS_RevokeConsent_m359E17666430182528984758FECB653440D8C915 in Assembly-CSharp1.o
      _MoPubiOS__moPubRevokeConsent_m7F75A26C3A8B1B52F1408582111D0BC669A39CDF in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOS__moPubRevokeConsent_m7F75A26C3A8B1B52F1408582111D0BC669A39CDF)
  "__moPubSetEngineInformation", referenced from:
      _MoPubiOS__moPubSetEngineInformation_mF3CCC24BD66BF20D8AB8D9E86FF968A9287F8DCB in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOS__moPubSetEngineInformation_mF3CCC24BD66BF20D8AB8D9E86FF968A9287F8DCB)
  "__moPubGetLogLevel", referenced from:
      _MoPubiOS_get_SdkLogLevel_mA36E46E9E88C565ADEF5CCA08E7101C4F33EEC82 in Assembly-CSharp1.o
      _MoPubiOS__moPubGetLogLevel_m9796CFCBE07BED2063C1AA0110BC4A8AC8EB0034 in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOS__moPubGetLogLevel_m9796CFCBE07BED2063C1AA0110BC4A8AC8EB0034)
  "__moPubShowBanner", referenced from:
      _MoPubiOSAdUnit_ShowBanner_m6DC9F67DAD5D56872F0C99D03EF6D8C11DBB31E2 in Assembly-CSharp1.o
      _MoPubiOSAdUnit__moPubShowBanner_m607E28889138C6C915F2E7EA518C743ABDF2BCB1 in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOSAdUnit__moPubShowBanner_m607E28889138C6C915F2E7EA518C743ABDF2BCB1)
  "__moPubInitializeSdk", referenced from:
      _MoPubiOS__moPubInitializeSdk_m053F6FC317E3F9F0CFD88FB85F9A87AC7BB73189 in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOS__moPubInitializeSdk_m053F6FC317E3F9F0CFD88FB85F9A87AC7BB73189)
  "__moPubReportApplicationOpen", referenced from:
      _MoPubiOS_ReportApplicationOpen_m4104DCEDF12046CEBD17DC9B1E2D1D846F5EADB3 in Assembly-CSharp1.o
      _MoPubiOS__moPubReportApplicationOpen_m333C8CF029AD834D4561FF9AAC8D08F71F270026 in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOS__moPubReportApplicationOpen_m333C8CF029AD834D4561FF9AAC8D08F71F270026)
  "__mopubGetAvailableRewards", referenced from:
      _MoPubiOSAdUnit__mopubGetAvailableRewards_m342C0D5E9284490737F1F59742D67840F91F4E32 in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOSAdUnit__mopubGetAvailableRewards_m342C0D5E9284490737F1F59742D67840F91F4E32)
  "__moPubIsConsentDialogReady", referenced from:
      _MoPubiOS_get_IsConsentDialogReady_m580A31DA59DC1B1636E2E539AE713281B468EB53 in Assembly-CSharp1.o
      _MoPubiOS__moPubIsConsentDialogReady_mB9086B2FC26928A9BA7ABF76D7F3E417D79D7074 in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOS__moPubIsConsentDialogReady_mB9086B2FC26928A9BA7ABF76D7F3E417D79D7074)
  "__moPubShouldShowConsentDialog", referenced from:
      _MoPubiOS_get_ShouldShowConsentDialog_m20EB2A128D1AB87A76FD78DAB64E8FA02FD1143A in Assembly-CSharp1.o
      _MoPubiOS__moPubShouldShowConsentDialog_m446AC6A5119AB65C36D8C4C18FBD4C1BE20E028B in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOS__moPubShouldShowConsentDialog_m446AC6A5119AB65C36D8C4C18FBD4C1BE20E028B)
  "__moPubSetLogLevel", referenced from:
      _MoPubiOS_set_SdkLogLevel_m934BBB0A6450D2F10842B548FA99C37CC667EAD8 in Assembly-CSharp1.o
      _MoPubiOS__moPubSetLogLevel_m4A6EFE72B0E75490BD9B3D2444D13FC59AB37B88 in Assembly-CSharp1.o
     (maybe you meant: _MoPubiOS__moPubSetLogLevel_m4A6EFE72B0E75490BD9B3D2444D13FC59AB37B88)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

**Comment by dravyan** [comment]
@BacheyG, this looks similar to the one resolved in [#119](https://github.com/mopub/mopub-unity-sdk/issues/119) and [#120](https://github.com/mopub/mopub-unity-sdk/issues/120). Confirm the steps and make sure you are using Unity-iPhone.xcworkspace. Let us know how that goes.

Thanks,
MoPub Team.

**Comment by BacheyG** [comment]
Thank you! Using xcworkspace fixed the issue. The test ad ID loads on ios now!
