### ISSUE TITLE
Vungle Interstitial Crash (Android)

### ISSUE THREAD

**Issue by FunBinge** [mopub/mopub-unity-sdk#124]
After updating the android Vungle adapter from version 1.1.1 to 1.2.2 I get crashes when playing Vungle interstitial ads. This is the last logs before the crash (full log attached bellow).

```
06-26 19:54:21.391 17108 17108 I MoPub   : [com.mopub.mobileads.MoPubInterstitial$MoPubInterstitialView][loadCustomEvent] Ad Log - Loading custom event interstitial adapter.

06-26 19:54:21.391 17108 17108 I MoPub   : [com.mopub.mobileads.CustomEventInterstitialAdapter][<init>] SDK Log - Attempting to invoke custom event: com.mopub.mobileads.VungleInterstitial

06-26 19:54:21.391 17108 17108 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.mopub.mobileads.VungleInterstitial>

06-26 19:54:21.391 17108 17394 I System.out: (HTTPLog)-Static: isSBSettingEnabled false

06-26 19:54:21.391 17108 17394 I System.out: (HTTPLog)-Static: isSBSettingEnabled false

06-26 19:54:21.391 17108 17108 D AndroidRuntime: Shutting down VM

...

06-26 19:54:21.401 17108 17108 I GameAnalytics: # Stacktrace: java.lang.NoClassDefFoundError: com.mopub.mobileads.VungleInterstitial
```

#### MoPub SDK Version:

5.13.0

#### Device model and OS Version:

Android Note 5

#### Unity Version:

2018.3.14f1

#### Ad Unit IDs used in reproducing the issue:

Interstitial: 2fc606294425440993701a50e8577eb3
Rewarded: c1b7b70335834960bb1eca00f0812452

#### Evidence:
[vungle-interstitial-crashlog.txt](https://github.com/mopub/mopub-unity-sdk/files/4836582/vungle-interstitial-crashlog.txt)

**Comment by dravyan** [comment]
@FunBinge, thank you for reporting. I am not getting an ad fill for the interstitial adunit shared above.  With our internal test adunit, I am not able to reproduce the crash on our end. Are you able to see this crash consistently? are there any specific specific steps to reproduce the issue?. Can you try testing with our latest Vungle adapter package 1.2.3?

Thanks,
MoPub Team

**Comment by FunBinge** [comment]
Hi @dravyan, thanks for your help. Just tried 1.2.3 and I get the same crash. I can consistently replicate it on my end, happens after a few minutes of starting up the game, usually at around the time when the first interstitial is loaded. Sometimes the game doesn't crash immediately, it just stops responding to input (banner keeps playing) and after a few seconds it crashes. I reverted back to 1.1.1 and the crashes are gone.

Device log for crash using Vungle adapter 1.2.3:
[vungle-interstitial-crashlog-1.2.3.txt](https://github.com/mopub/mopub-unity-sdk/files/4840009/vungle-interstitial-crashlog-1.2.3.txt)

**Comment by dravyan** [comment]
@FunBinge, Could you see if you can reproduce the issue with [MoPub Unity sample app](https://github.com/mopub/mopub-unity-sdk/tree/master/unity-sample-app)?. Can you confirm whether the crash is noticed when playing an interstitial ad or banner ad?. 
Looking at the `Stacktrace: java.lang.NoClassDefFoundError: com.mopub.mobileads.VungleInterstitial`, it looks to me like proguard rules messing around with your app build and removing `VungleInterstitial` class? If you are using proguard, can you add keep logic for `com.mopub.mobileads.* ` package?

Thanks,
MoPub Team
