### ISSUE TITLE
sample project crashes unity 2019.4.1 

### ISSUE THREAD

**Issue by MrMechanical** [mopub/mopub-unity-sdk#129]

**Comment by MrMechanical** [comment]
I see sample project is in 2018 unity version. Can it be updated to 2019.4?

**Comment by chauduyphanvu** [comment]
@MrMechanical, yes, you can use MoPub with Unity 2019.x. 

What is the crash you are seeing? Are you able to provide a stack trace? Thanks!

Vu Chau
MoPub Team

**Comment by LongLostPenPal** [comment]
> @MrMechanical, yes, you can use MoPub with Unity 2019.x.
> 
> What is the crash you are seeing? Are you able to provide a stack trace? Thanks!
> 
> Vu Chau
> MoPub Team

#272

**Comment by chauduyphanvu** [comment]
Duplicate. Closing.
