### ISSUE TITLE
Black screen since SDK 5.13.0

### ISSUE THREAD

**Issue by tontonpiero** [mopub/mopub-unity-sdk#131]
I consistently get a black ad instead of the expected interstitial vast ad since Mopub SDK version 5.13.0 (5.12.1 is fine)

#### MoPub SDK Version:
5.13.0

#### Device model and OS Version:
Samsung Galaxy S8 on Android 9

#### Unity Version:
2019.2.17

#### Ad Unit IDs used in reproducing the issue:
d79e7319d51440ecaa3b88a497b6a0f4

#### Steps to reproduce the behavior:
Load interstitial and display it

#### Expected behavior:
A interstitial/vast ad is displayed

#### Observed behavior:
A black screen with only the close button

#### Evidence:
I got some logcat when I displayed the ad:
`07-09 16:51:13.974 16646 16853 I Unity   : [MoPub-Unity] [ShowInterstitialAd] Attempting to show ad
07-09 16:51:13.976 16646 16646 I MoPub   : [com.mopub.mobileads.MoPubInterstitial][show] Attempting to show ad
07-09 16:51:13.977 16646 16646 I MoPub   : [com.mopub.mobileads.FullscreenAdAdapter][show] Attempting to show ad
07-09 16:51:13.977 16646 16646 I MoPub   : [com.mopub.mobileads.MoPubFullscreen][show] Adapter MoPubFullscreen attempting to show ad
07-09 16:51:13.982  3879  3989 E Parcel  : Class not found when unmarshalling: com.mopub.mobileads.AdData
07-09 16:51:13.982  3879  3989 E Parcel  : java.lang.ClassNotFoundException: com.mopub.mobileads.AdData
07-09 16:51:13.982  3879  3989 E Parcel  : Caused by: java.lang.ClassNotFoundException: com.mopub.mobileads.AdData
07-09 16:51:13.983  3879  3989 W Bundle  : android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.mopub.mobileads.AdData
07-09 16:51:13.984  3879  3989 I ActivityManager: START u0 {act=null typ=null flg=0x10000000 cmp=ComponentInfo{com.marketluck.bravospeed/com.mopub.mobileads.MoPubFullscreenActivity}} from uid 11307
07-09 16:51:13.995  3313  3313 I SurfaceFlinger: id=114232 createSurf (5920x5920),2 flag=4, AppWindowToken{8030e58 token=Token{16f173b ActivityRecord{b41f9ca u0 com.marketluck.bravospeed/com.mopub.mobileads.MoPubFullscreenActivity t52818}}}#0
07-09 16:51:14.089  3879 11010 D GameManagerService: handleForegroundChange(). pkgName: com.marketluck.bravospeed, clsName: com.mopub.mobileads.MoPubFullscreenActivity,FgActivityName:com.marketluck.bravospeed/com.mopub.mobileads.MoPubFullscreenActivity,userID:0
07-09 16:51:14.104  3879  3879 D Telecom:SamsungPrebindingServiceImpl: onTopActivityChanged : ComponentInfo{com.marketluck.bravospeed/com.mopub.mobileads.MoPubFullscreenActivity}
07-09 16:51:14.125 16646 16646 I MoPub   : [com.mopub.mobileads.MoPubFullscreenActivity][safedk_MoPubFullscreenActivity_onCreate_13c6f1d2af1c3a2d960e7384387473f7] Ad shown
07-09 16:51:14.155  3313  3313 I SurfaceFlinger: id=114233 createSurf (5920x5920),2 flag=4, 49b32b3 com.marketluck.bravospeed/com.mopub.mobileads.MoPubFullscreenActivity#0
07-09 16:51:14.158 16646 16646 D ViewRootImpl@e48827[MoPubFullscreenActivity]: setView = DecorView@b73b1c2[MoPubFullscreenActivity] TM=true MM=false
07-09 16:51:14.169 16646 16646 D ViewRootImpl@e48827[MoPubFullscreenActivity]: dispatchAttachedToWindow
07-09 16:51:14.173  3879 13160 V WindowManager: Relayout Window{49b32b3 u0 com.marketluck.bravospeed/com.mopub.mobileads.MoPubFullscreenActivity}: viewVisibility=0 req=1080x2220 {(0,0)(fillxfill) sim={adjust=resize forwardNavigation} layoutInDisplayCutoutMode=never ty=BASE_APPLICATION wanim=0x10302fe sysuil=true
07-09 16:51:14.174  3879 13160 V WindowManager: Resize reasons for w=Window{49b32b3 u0 com.marketluck.bravospeed/com.mopub.mobileads.MoPubFullscreenActivity}:  contentInsetsChanged=false [0,63][0,126] visibleInsetsChanged=false [0,0][0,0] stableInsetsChanged=false [0,63][0,126] outsetsChanged=false [0,0][0,0] surfaceResized=false configChanged=true dragResizingChanged=false reportOrientationChanged=false displayCutoutChanged=false nextForceRelayoutToClient=false
07-09 16:51:14.179  3313  3313 I SurfaceFlinger: id=114234 createSurf (1080x2220),1 flag=404, com.marketluck.bravospeed/com.mopub.mobileads.MoPubFullscreenActivity[16646]#0
07-09 16:51:14.180  3879 13160 D WindowManager: makeSurface duration=2 name=com.marketluck.bravospeed/com.mopub.mobileads.MoPubFullscreenActivity[16646]
07-09 16:51:14.181  3879 13160 V WindowManager: Changing focus from null to Window{49b32b3 u0 com.marketluck.bravospeed/com.mopub.mobileads.MoPubFullscreenActivity} Callers=com.android.server.wm.WindowManagerService.relayoutWindow:2558 com.android.server.wm.Session.relayoutForTranslate:302 android.view.IWindowSession$Stub.onTransact:518 com.android.server.wm.Session.onTransact:186
07-09 16:51:14.181  3879  3897 D WindowManager: setSystemUiVisibility: vis= 0x131e, fullscreenVis= 0x0, dockedVis= 0x0, win=Window{49b32b3 u0 com.marketluck.bravospeed/com.mopub.mobileads.MoPubFullscreenActivity}
07-09 16:51:14.182  3879  3906 D WindowManager: reportFocusChangedSerialized, focused=true, inTouchMode=true, win=Window{49b32b3 u0 com.marketluck.bravospeed/com.mopub.mobileads.MoPubFullscreenActivity}
07-09 16:51:14.183 16646 16646 D ViewRootImpl@e48827[MoPubFullscreenActivity]: Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x7 surface={valid=true 2498349056} changed=true
07-09 16:51:14.197 16646 16646 I MoPub   : [com.mopub.mobileads.MoPubInterstitial][onAdShown] Ad shown`

**Comment by dravyan** [comment]
@tontonpiero, thank you for the report. It seems like server side hiccup has triggered this behavior. Please test it out again and let us know if you still notice the issue.

Thanks,
MoPub Team

**Comment by tontonpiero** [comment]
Hi @dravyan , thank you it's working fine now!
