### ISSUE TITLE
Manual Mediation with all networks in unity for android Error.

### ISSUE THREAD

**Issue by BledyEdge** [mopub/mopub-unity-sdk#133]
![2](https://user-images.githubusercontent.com/65586660/88063392-69899500-cb83-11ea-82c4-67aa54f70801.PNG)
One line summary of the issue here

-Manually\Mediation Manually\Temp\gradleOut\launcher\build\intermediates\merged_manifests\release\AndroidManifest.xml:115: AAPT: error: resource style/mintegral_transparent_theme (aka com.DefaultCompany.MediationManually:style/mintegral_transparent_theme) not found.

UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
when i hit build, it gives error.

#### Steps to reproduce the behavior:
1) Imported mopub sdk
2)Paste all the file get from extracted mopub-android-mediation-master in   Assets / Plugins / Android.
3)Force Resolved
4)Try to build now.you will se error.

#### Expected behavior:
It should simply build the APK.

#### Observed behavior:
I got error what i mentioned in upper line.

#### Evidence:
Device log files, Network log file, etc.
![1](https://user-images.githubusercontent.com/65586660/88055470-8076ba00-cb78-11ea-9d15-a03551a4163f.PNG)

**Comment by chauduyphanvu** [comment]
@BledyEdge, could you confirm that you have also added the mediation network SDKs in your Unity project? If you use only the files from `mopub-android-mediation`, you have only the adapters without the network SDKs. That results in the compilation error you are seeing.

Vu Chau
MoPub Team

**Comment by BledyEdge** [comment]
@chauduyphanvu  Thankyou so much respoding, i have read the documentation and i think i should start with Auto adopters download and import thmem, i am going to  close this issue, i will let you know if i will face any issue with that way,
