### ISSUE TITLE
MoPub SDK Version:5.13.1  chartboost 1.1.20 crash on ios 13.5.1

### ISSUE THREAD

**Issue by simon002** [mopub/mopub-unity-sdk#135]
One line summary of the issue here

- [ ] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
when i upgrade MoPub SDK from 5.12.1 to 5.13.1, chartboost from 1.1.17 to 1.1.20, run app in iphonese it crash. I upgrade the sdk through Mopub SDK Manager. 
<img width="424" alt="9E12335B-2F2F-4384-8C6A-C710FB471FFE" src="https://user-images.githubusercontent.com/10241848/89264060-e2e5b500-d664-11ea-8793-94ed529887ef.png">

#### Expected behavior:
As concisely as possible, describe the expected behavior.

#### Observed behavior:
As concisely as possible, describe the observed behavior.

#### Evidence:
the xcode log info : Chartboost (V) | No saved data use consent values to restore
<img width="735" alt="C81DFF87-933E-498F-83F2-265B3FDFB8D5" src="https://user-images.githubusercontent.com/10241848/89264145-0577ce00-d665-11ea-8582-dfb12d4c9f5b.png">

**Comment by hmertkahraman** [comment]
Hi @simon002 ,

We're investigating this issue and will get back to you.

Meanwhile, for the XCode error is this a Crash? If so, can you please provide the crash stack trace from XCode Logs?

Thanks,
MoPub Team

**Comment by simon002** [comment]
> Hi @simon002 ,
> 
> We're investigating this issue and will get back to you.
> 
> Meanwhile, for the XCode error is this a Crash? If so, can you please provide the crash stack trace from XCode Logs?
> 
> Thanks,
> MoPub Team

yes the error is a crash. today i find the chartboost version is upgrade to 1.1.21 in MoPub SDK Manager , but it still crash. 
The crash stack:
<img width="883" alt="E17522DF-5C05-492A-8DE1-F5B6AD931FDD" src="https://user-images.githubusercontent.com/10241848/89484678-92d83100-d7d1-11ea-91a8-faf72aa10fc1.png">

**Comment by hmertkahraman** [comment]
Hi @simon002 ,

Thanks for the information provided. This issue seems to be Chartboost SDK specific, which is mediation related. So I'm carrying this issue to our mediation related GH repository: [github.com/mopub/mopub-unity-mediation](github.com/mopub/mopub-unity-mediation).

[Here is the new issue link](https://github.com/mopub/mopub-unity-mediation/issues/45), and I [responded with an update](https://github.com/mopub/mopub-unity-mediation/issues/45#issuecomment-670574656) as well. Can you please respond there?

Thanks,
Mert
