### ISSUE TITLE
Banner ads not loading

### ISSUE THREAD

**Issue by BacheyG** [mopub/mopub-unity-sdk#137]
I would like to use AdColony, Vungle and UnityAds  via MoPub mediation for showing a banner in my Unity game app. My issue is that I can't get my banner ads get to work. I've tried updating MoPub version to latest and also added Vungle and AdColony via the built in SDK manager. The Unity Ads SDK is already prebuilt with the newer versions of Unity.

I tried the test ad ID and that one works well, it loads the MoPub placeholder banner. I also tried verbose logging and it also works well as intended. My question is that I wonder what I'm missing to make my banner ads visible, I released my game "Jello Ballo" with my MoPub banner and they don't show.

I created a Unity project with exactly the same settings and banner ad script but with a dummy scene. I am happy to share the github repository of it with you to show how exactly everything is set up. Just let me know your username and I'll add you as a contributor.

I tried so many things, no luck so far.

#### MoPub SDK Version:
MoPub Version 5.13.1
#### Unity Version:
2019.4.1f
#### Ad Unit IDs used in reproducing the issue:
iOS: d6be5a3cac074777a74d035a24ebcc50
Android: c46911f89200470a95fe19e712b71e2a
#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.

#### Expected behavior:
Show banner ads.

#### Observed behavior:
No banner ad shown.

Thank you and have a nice day!

**Comment by dravyan** [comment]
@BacheyG, thank you for reaching out. It seems like you have not set up line items for Vungle, AdColony and UnityAds for the adunits shared above. Please refer to our documentation on [managing line items](https://developers.mopub.com/publishers/ui/manage-line-items/) or reach out to https://developers.mopub.com/support/.

Thanks,
MoPub Team

**Comment by BacheyG** [comment]
Thank you! Now I added an order and a line item. I could display a custom banner with an uploaded image in my app.
But how do I get the Vungle/AdColony/UnityAds html snipped in it when adding creative? I only have placement ids for it, no html provided.

**Comment by BacheyG** [comment]
Ok, I added a marketplace line item, but still no luck.

**Comment by BacheyG** [comment]
I've added an invite to access to dravyan to my Banner Test repository, which reproduces the issue.

**Comment by dravyan** [comment]
@BacheyG , could you share the link to the Banner Test repository again?. We are not able to see your GitHub repo. thanks!

**Comment by BacheyG** [comment]
@dravyan You can access the repository here: https://github.com/BacheyG/BannerTest
Please let me know if you have further questions. Thank you!

**Comment by p158276** [comment]
Hi @BacheyG ,
Thanks for waiting. I've checked your project and the logic.
I am able to get the marketplace and adcolony ad from my side. So it more like a no fill problem.
![F9BC91FA-2D17-44CC-B809-7D97BEF6ABF2](https://user-images.githubusercontent.com/2937047/92227813-6cdda380-eed9-11ea-88b2-10f0bc888c6c.PNG)
![IMG_3883](https://user-images.githubusercontent.com/2937047/92228763-f80b6900-eeda-11ea-9927-dfd8959c423c.PNG)

One thing to remind is you may need to implement [GDPR](https://developers.mopub.com/publishers/unity/gdpr/) if you plan to launch your App in EU region. 

Please share the log with us if you still encounter the problem here.

Thanks,
Yoyo Lin 
MoPub Team

**Comment by BacheyG** [comment]
Yes, you are right, it was the consent missing! 
![118792233_357875731912963_8836716684341684548_n](https://user-images.githubusercontent.com/10908673/92252667-d73d1680-eece-11ea-94f3-0566613db2c5.jpg)
I got my AdColony ad working, thank you! I really appreciate your help. I am displaying debug test ads via AdColony, I guess final ones only work with released game?

**Comment by p158276** [comment]
Hi @BacheyG ,
Glad to hear that!  Feel free to raise any question (issue) if you encounter any problem.
