### ISSUE TITLE
Crash in MPVastModel.m (iOS)

### ISSUE THREAD

**Issue by LucileBillard** [mopub/mopub-unity-sdk#138]
One line summary of the issue here

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.

#### Expected behavior:
The app should not crash.

#### Observed behavior:
The app crashes inside the function **hasPropertyNamed**  (l.368) due to **className** being nil (in file MPVastModel.m)

#### Evidence:
<img width="1063" alt="Screenshot 2020-08-24 at 14 28 40" src="https://user-images.githubusercontent.com/5479803/91048012-4ab36e00-e61b-11ea-8b38-499d49bc2c15.png">

**Comment by chauduyphanvu** [comment]
@LucileBillard, how consistent are you running into this crash? I'm trying with your ad unit ID but haven't gotten any issues.

If you can reproduce it in-house, would you be willing to share the ad response with us? You can capture that either via a proxy tool like Charles, or via Xcode's console log (with debug log level enabled). Thanks!

Vu Chau
MoPub Team

**Comment by LucileBillard** [comment]
Thank you @chauduyphanvu ,  It happens randomly and I can't reproduce easily locally. It seems to be caused by some heap corruption.

Logs from crashlytics:

Crashed: com.apple.root.default-qos
0  libsystem_kernel.dylib         0x1cb18f0dc __pthread_kill + 8
1  libsystem_pthread.dylib        0x1cb208094 pthread_kill$VARIANT$mp + 380
2  libsystem_c.dylib              0x1cb0e7ea8 abort + 140
3  libsystem_malloc.dylib         0x1cb1e2684 _malloc_put + 562
4  libsystem_malloc.dylib         0x1cb1e283c malloc_report + 60
5  libsystem_malloc.dylib         0x1cb1d549c free + 532
6  CoreFoundation                 0x1cb629ed0 mdict_rehashd + 288
7  CoreFoundation                 0x1cb4e7a48 -[__NSDictionaryM setObject:forKeyedSubscript:] + 428
8  bravospeed                     0x1007fe660 -[MPVASTModel hasPropertyNamed:] + 369 (MPVASTModel.m:369)
9  bravospeed                     0x1007fdf28 __34-[MPVASTModel initWithDictionary:]_block_invoke + 272 (MPVASTModel.m:272)
10 CoreFoundation                 0x1cb4de2d0 -[__NSDictionaryI enumerateKeysAndObjectsWithOptions:usingBlock:] + 168
11 bravospeed                     0x1007fde80 -[MPVASTModel initWithDictionary:] + 306 (MPVASTModel.m:306)
12 bravospeed                     0x1007fd948 -[MPClassMapper mappedObjectFromSourceObject:] + 174 (MPVASTModel.m:174)
13 bravospeed                     0x1007fdb70 -[MPNSArrayMapper mappedObjectFromSourceObject:] + 217 (MPVASTModel.m:217)
14 bravospeed                     0x1007fe06c __34-[MPVASTModel initWithDictionary:]_block_invoke + 294 (MPVASTModel.m:294)
15 CoreFoundation                 0x1cb4de2d0 -[__NSDictionaryI enumerateKeysAndObjectsWithOptions:usingBlock:] + 168
16 bravospeed                     0x1007fde80 -[MPVASTModel initWithDictionary:] + 306 (MPVASTModel.m:306)
17 bravospeed                     0x1007fa780 -[MPVASTInline initWithDictionary:] + 17 (MPVASTInline.m:17)
18 bravospeed                     0x1007fd948 -[MPClassMapper mappedObjectFromSourceObject:] + 174 (MPVASTModel.m:174)
19 bravospeed                     0x1007fe06c __34-[MPVASTModel initWithDictionary:]_block_invoke + 294 (MPVASTModel.m:294)
20 CoreFoundation                 0x1cb4de2d0 -[__NSDictionaryI enumerateKeysAndObjectsWithOptions:usingBlock:] + 168
21 bravospeed                     0x1007fde80 -[MPVASTModel initWithDictionary:] + 306 (MPVASTModel.m:306)
22 bravospeed                     0x1007f6b10 -[MPVASTAd initWithDictionary:] + 18 (MPVASTAd.m:18)
23 bravospeed                     0x1007fd948 -[MPClassMapper mappedObjectFromSourceObject:] + 174 (MPVASTModel.m:174)
24 bravospeed                     0x1007fdb70 -[MPNSArrayMapper mappedObjectFromSourceObject:] + 217 (MPVASTModel.m:217)
25 bravospeed                     0x1007fe06c __34-[MPVASTModel initWithDictionary:]_block_invoke + 294 (MPVASTModel.m:294)
26 CoreFoundation                 0x1cb4de2d0 -[__NSDictionaryI enumerateKeysAndObjectsWithOptions:usingBlock:] + 168
27 bravospeed                     0x1007fde80 -[MPVASTModel initWithDictionary:] + 306 (MPVASTModel.m:306)
28 bravospeed                     0x1007fbd68 +[MPVASTManager parseVASTResponseFromData:depth:completion:] + 80 (MPVASTManager.m:80)
29 bravospeed                     0x1007fb948 __46+[MPVASTManager fetchVASTWithData:completion:]_block_invoke + 62 (MPVASTManager.m:62)
30 libdispatch.dylib              0x1cb030a38 _dispatch_call_block_and_release + 24
31 libdispatch.dylib              0x1cb0317d4 _dispatch_client_callout + 16
32 libdispatch.dylib              0x1cafd5c80 _dispatch_queue_override_invoke + 684
33 libdispatch.dylib              0x1cafe2030 _dispatch_root_queue_drain + 372
34 libdispatch.dylib              0x1cafe28d4 _dispatch_worker_thread2 + 128
35 libsystem_pthread.dylib        0x1cb2121b4 _pthread_wqthread + 464
36 libsystem_pthread.dylib        0x1cb214cd4 start_wqthread + 4

**Comment by chauduyphanvu** [comment]
Thank you for the stack trace. We'll check it out internally and get back to you if there's an update.

**Comment by chauduyphanvu** [comment]
Just to let you know, we have prepared a fix for this internally. It should be released with the upcoming SDK. Stay tuned!

**Comment by LucileBillard** [comment]
Thanks for the update @chauduyphanvu

**Comment by chauduyphanvu** [comment]
This issue was fixed in [v5.14.1](https://github.com/mopub/mopub-unity-sdk/commit/0f1eb02d1d9cbb5ada8830f91d130ec30c6a3d1e). Let us know if you continue seeing the issue!
