### ISSUE TITLE
Unable to close ad on iOS

### ISSUE THREAD

**Issue by LucileBillard** [mopub/mopub-unity-sdk#139]
The user cannot close an ad on iOS.

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.

#### Expected behavior:
The ad should close

#### Observed behavior:
(1) Unable to close an ad because no x button on the screen on iOS --> the user has to kill the app. (however clicking on the corner makes the ad close properly , but the user can't know since there is no x  )

(2) A second problem occurs when a user clicks on the link on the ad and then goes back to the app --> the user remains stuck on the ad forever and the timer does not progress anymore (this time even clicking on the corner does not work) 

#### Evidence:

![IMG_5003](https://user-images.githubusercontent.com/5479803/91156950-ffee3080-e6c4-11ea-9513-b2c7acf26d58.PNG)
![IMG_5004](https://user-images.githubusercontent.com/5479803/91156944-fd8bd680-e6c4-11ea-9133-3396ea6e7a9a.PNG)

**Comment by chauduyphanvu** [comment]
@LucileBillard, this issue has been fixed internally and will be released in an upcoming SDK version. Stay tuned!

Vu Chau
MoPub Team

**Comment by chauduyphanvu** [comment]
This issue was fixed in [v5.14.1](https://github.com/mopub/mopub-unity-sdk/commit/0f1eb02d1d9cbb5ada8830f91d130ec30c6a3d1e). Let us know if you continue seeing the issue!
