### ISSUE TITLE
Cant Load the Consent Dialog

### ISSUE THREAD

**Issue by mertkurum** [mopub/mopub-unity-sdk#14]
Hi, 

I am trying load consent dialog but I always fail. I have also tested with sample project and got the same result.

**Comment by aornelas** [comment]
Hi there!

Can you confirm that GDPR applies to your location? You can see that via the `Is GDPR applicable` label in our sample app.

When GDPR does NOT apply, the consent dialog will not load. Apologies for the confusion! We'll make this clearer in the next release.

**Comment by mertkurum** [comment]
I was testing with VPN. I know that you had issues on your servers but it fixed now. Anyway Thanks!

**Comment by aornelas** [comment]
Glad you got it working 👍
