### ISSUE TITLE
Admob plugin crashes Android app

### ISSUE THREAD

**Issue by Seiryu32** [mopub/mopub-unity-sdk#141]
So seems like this is a fairly common occurrence but I'm having problems with the GoogleMobileAd plugin for Unity causing the app the fail to launch. I've had this problem for a couple of weeks. I'm currently using Unity2018.3.10 and the most recent version of the plugin. 

Steps to re-produce
1. Start new project.
2. Import GoogleAdmobPlugin.
3. Go to Assets>Google Mobile Ads>Settings. Enable Google Admob and enter App ID.
4. Go to Build Settings>Player Settings>Other Settings.
 Package Name: com.Company.Product. 
Version: 0.1. 
Bundle Version: 1. 
Scripting Runtime Version: .NET 3.5 Equivalent. 
Scripting Backend: IL2CPP
Api Compatibility Level: Net 2.0
C++ Complier Configuration: Release
5. Go to  Publishing Settings. Create New keystore.

The app builds and installs with no errors in the Console but won't launch even with an empty scene. It builds and runs normally without the plugin. How do I fix this issue?

**Comment by chauduyphanvu** [comment]
@Seiryu32, we are not the author of this plugin. You will need to check with the AdMob team at https://groups.google.com/forum/#!forum/google-admob-ads-sdk.

Let us know if you need anything else!

Vu Chau
MoPub Team
