### ISSUE TITLE
Banner auto-refresh, custom keywords.

### ISSUE THREAD

**Issue by Blinkq** [mopub/mopub-unity-sdk#142]
Hello. I want to set up keywords every auto-refresh, but there are no functionality to just set up keywords, RefreshBanner and RequestBanner calls LoadAd, that not the case, because this way I am loosing fetched bids.
Maybe there are some ways to get to mMoPubView in 
https://github.com/mopub/mopub-unity-sdk/blob/master/mopub-android-sdk-unity/src/main/java/com/mopub/unity/MoPubBannerUnityPlugin.java so I could work with that instance in Unity ?

**Comment by p158276** [comment]
Hi @Blinkq ,
Thanks for reaching out. 
We are supporting [Banner keyword passing](https://github.com/mopub/mopub-unity-sdk/blob/0f1eb02d1d9cbb5ada8830f91d130ec30c6a3d1e/mopub-android-sdk-unity/src/main/java/com/mopub/unity/MoPubBannerUnityPlugin.java#L59-L60) in 5.14.1 Unity SDK.
You can also pass the keyword when calling the [RefreshBanner](https://developers.mopub.com/publishers/reference/unity/Banners/#public-static-void-refreshbannerstring-adunitid-string-keywords-string-userdatakeywords)

Yoyo Lin
MoPub Team
