### ISSUE TITLE
AndroidJavaException: java.lang.NoClassDefFoundError:  com/mopub/common/privacy/ConsentStatusChangeListener

### ISSUE THREAD

**Issue by mikotomioo** [mopub/mopub-unity-sdk#144]
One line summary of the issue here

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### Exception Log:
`AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mopub/common/privacy/ConsentStatusChangeListener;`

First, use 'Mopub SDK Manager' update to 5.14.1 and other Networks SDKs.

Second, use the Migrate button removed components :
`mopub-sdk-base.aar`
`mopub-sdk-banner.aar`
`mopub-sdk-fullscreen.aar`
`mopub-sdk-native-static.aar`
`mopub-volley-2.0.0.jar`

Go to unity, get the error `Assets/MoPub/Scripts/Internal/AbstractNativeAd.cs(206,13): error CS0305: Using the generic type 'IEnumerator<T>' requires 1 type arguments`
Third, disable MoPub native ads(BETA)

Run in unity editor, is ok 
But build apk and run in android device, get the AndroidJavaException

Use Android Studio check the mopub-unity-wrappers.aar, only find com.mopub.unity class.
Check the mopub-sdk-base.aar, it can find com.mopub.common.privacy.ConsentStatusChangeListener function

Finaly, I add all components into proj, it can run the ad video.
I checked the docs and followed that, I don't know which step make wrong

**Comment by aornelas** [comment]
Hello, do you have a custom Gradle template? if so, please try disabling it to see if that helps.

**Comment by mikotomioo** [comment]
Exprot android proj and check build.gradle, nothing special
'build.gradle' about it⬇️

buildscript 
    repositories 
        google()
        ...
    dependencies 
        classpath 'com.android.tools.build:gradle:3.4.0'

allprojects 
    repositories 
        flatDir 
            dirs libs

        google()
        ...

dependencies 
    implementation 'androidx.multidex:multidex:2.0.0'
    implementation('jar', 'aar'...)
    ...
    implementation(name: 'mopub-sdk-banner', ext:'aar')
    implementation(name: 'mopub-sdk-base', ext:'aar')
    implementation(name: 'mopub-sdk-interstitial', ext:'aar')
    implementation(name: 'mopub-sdk-native-static', ext:'aar')
    implementation(name: 'mopub-sdk-rewardedvideo', ext:'aar')
    implementation(name: 'mopub-unity-wrappers', ext:'aar')
    implementation project(':MoPub.plugin')

android 
    compileSdkVersion 28
    buildToolsVersion 29.0.3

    compileOptions 
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 28
        multiDexEnabled true
        ndk 
            abiFilters 'armeabi-v7a', 'arm64-v8a'

    packagingOptions 
        doNotStrip '*/armeabi-v7a/*.so'
        doNotStrip '*/arm64-v8a/*.so'
        doNotStrip '*/x86/*.so'

    aaptOptions 
        noCompress '.unity3d', '.ress', '.resource', '.obb'

    signingConfigs 
        release 
            ...

    buildTypes
        release 
            siging config...

    afterEvaluate
        set someting with dex...

    bundle
        ...

**Comment by aornelas** [comment]
Sorry, I meant if you had the option checked under **Player Settings > Publishing Settings > Build > Custom Gradle Template**. When checked, that will generate a `mainTemplate.gradle` which is then used to build the project, and we have seen stale templates cause similar issues -- specifically, when including an outdated gradle build tools version.

**Comment by mikotomioo** [comment]
Yep, we use custom gradle template and modified some config.
And it can't disable custom gradle, that will build apk with error

Do not remove aar/jar components is ok? It make anything wrong? We check the ad video play ok.

**Comment by chauduyphanvu** [comment]
@mikotomioo, could you confirm if you are still seeing the issue? I'm unclear if you were able to get things to work when you said:

> Finaly, I add all components into proj, it can run the ad video.
I checked the docs and followed that, I don't know which step make wrong

If the issue persists, would you be able to share with us your project and the complete stack trace of the Exception? Thank you!

Vu Chau
MoPub Team

**Comment by MrMechanical** [comment]
Hi I'm having the same issue except I have **Custom Gradle Properties Template** checked.

**Comment by MrMechanical** [comment]
<img width="1170" alt="Screen Shot 2020-10-17 at 3 47 16 PM" src="https://user-images.githubusercontent.com/28378318/96352274-0af38a80-1090-11eb-8cec-e2723ab67b24.png">

**Comment by MrMechanical** [comment]
I'm using the Mopub Unity sample with all SDKs except Verizon and Pangle.

**Comment by mikotomioo** [comment]
I do not use the Migrate Btn. I just put aar & jar back to Assets/MoPub/Plugins/Android/

**Comment by MrMechanical** [comment]
I've figured it out: The Facebook SDK has its own PlayServicesResolver stuff that should be unchecked when importing. This fixes the problem.

**Comment by chauduyphanvu** [comment]
@MrMechanical, thanks for the tip! 

@mikotomioo, are you using Facebook or any other dependencies that have their own PlayServicesResolver? If so, try the suggestion from https://github.com/mopub/mopub-unity-sdk/issues/144#issuecomment-712996402.

**Comment by mikotomioo** [comment]
It can fix.

**Comment by chauduyphanvu** [comment]
@mikotomioo, thank you for the confirmation. I'm closing this issue now as this isn't an issue with the MoPub SDK per se, but more about how Google's PlayServicesResolver interacts with the app.
