### ISSUE TITLE
Chartboost not initializing "Needs SDK to be integrated" issue (Android only Unity app)

### ISSUE THREAD

**Issue by MrMechanical** [mopub/mopub-unity-sdk#146]
The Chartboost dashboard indicates that the SDK has not been initialized and therefor the app can not be submitted for review for Chartboost.

- [X] I am submitting a bug report for existing functionality
- [X] I visited https://developers.mopub.com/ and found no answer
- [X] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [X] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.14.1
#### Device model and OS Version:
Mac OS 10.15.4 Macbook Air 2020

#### Unity Version:
Unity 2019.4.13f1

#### Observed behavior:
As concisely as possible, describe the observed behavior.
After running the app with Unity Mopub automatic initialization the Chartboost dashboard indicates that the sdk has not been initialized despite the SDK key being inserted in Chartboost network config. My app is only published on Android so I left the iOS configurations blank, however, I presume this shouldn't be an issue.
#### Evidence:
Device log files, Network log file, etc.
<img width="420" alt="Screen Shot 2020-11-01 at 2 19 05 PM" src="https://user-images.githubusercontent.com/28378318/97812121-35774300-1c4d-11eb-828f-12401d1bebf7.png">

**Comment by MrMechanical** [comment]
I have removed the config script for Chartboost for Unity automatic initialization (I realized it's optional), but I still have the same issue.

**Comment by chauduyphanvu** [comment]
@MrMechanical, what is the issue you are facing now? Is it still about the "Needs SDK to be integrated"?

Vu Chau
MoPub Team

**Comment by MrMechanical** [comment]
Thank you for your help. Right now when I integrate everything with User ID/User signature and App ID / App signature the issue is in the Chartboost dashboard it says "Needs SDK to be integrated" and I cannot submit the app for review after running the app.

**Comment by chauduyphanvu** [comment]
Chartboost has a team that can help take a look at this issue: https://answers.chartboost.com/en-us/articles/115001489971. 

> The Chartboost Adapter is not initializing during the bootup. If you are using a mediation SDK which does not initialize Chartboost Adapter during the bootup of your application we recommend you to temporarily put Chartboost on the top of your waterfall. If you do not wish to put Chartboost on the top of your waterfall globally, you can limit it to the Netherlands only. After doing this, let us know as soon as possible so we can do the necessary checks and you can reverse the changes afterwards to the desired ones. If you are uncertain how to make these changes or would like additional options, please follow-up with us via app.review@chartboost.com and mention your mediation platform.

I recommend reaching out to them via app.review@chartboost.com with the specific circumstance of your app. Let us know how it goes!

**Comment by MrMechanical** [comment]
Thank you for the tip! I will try to put Chartboost on top of the waterfall and I will also try to shoot app.review@chartboost.com an email. I will let you know how it goes. Thank you for your help!

**Comment by MrMechanical** [comment]
@chauduyphanvu, perhaps I need to add something special to my Android Manifest for Chartboost to work (I have not added anything to the manifest for Chartboost)? I sent an email describing the situation to app review, but after prioritizing Chartboost in the waterfall they have not been able to get Chartboost to show any impressions.

**Comment by chauduyphanvu** [comment]
@MrMechanical, not that I know of, but you could always reference [our Chartboost page](https://developers.mopub.com/publishers/mediation/networks/chartboost/) for more information. Could you show your console/device logs?

Here are some test ad unit IDs if you want to test with them (good way to check if the problem is related to ad unit ID setup or app integrations):

* **Banner**: 7e1f9bbadd7c44eaaa354ed7058a8a4b
* **Interstitial**: 376366b49d324dedae3d5edb360c27b4
* **Rewarded Video**: 008c4b3de4b649d48ff69c63508d3489
