### ISSUE TITLE
$0.00 CPMs displayed in dashboard after integrating and running live impressions. Is there something going wrong?

### ISSUE THREAD

**Issue by MrMechanical** [mopub/mopub-unity-sdk#148]
One line summary of the issue here

- [X] I am submitting a bug report for existing functionality
- [X] I visited https://developers.mopub.com/ and found no answer
- [X] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [X] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.14.1
#### Device model and OS Version:
Mac OS 10.15.4 Macbook Air 2020
#### Unity Version:
Unity 2019.4.13f1

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.
Make complete integration with all networks supported networks in dashboard, publish app live to appstore.
#### Expected behavior:
As concisely as possible, describe the expected behavior.
CPMs which are a not zero value.
#### Observed behavior:
CPMs which are labelled as zero.

Thank you greatly for the help!

#### Evidence:
Device log files, Network log file, etc.

<img width="887" alt="Screen Shot 2020-11-04 at 1 40 57 PM" src="https://user-images.githubusercontent.com/28378318/98155754-c431cd00-1ea4-11eb-9fd6-642a83bb457a.png">
<img width="853" alt="Screen Shot 2020-11-04 at 1 40 28 PM" src="https://user-images.githubusercontent.com/28378318/98155773-cac04480-1ea4-11eb-90f5-a84d8eb3c8ae.png">
<img width="986" alt="Screen Shot 2020-11-04 at 1 38 09 PM" src="https://user-images.githubusercontent.com/28378318/98155790-d0b62580-1ea4-11eb-923a-a66d60b80b24.png">

**Comment by estherchoix** [comment]
Hi @MrMechanical - 

Please make sure that you are going through our [support portal](https://www.mopub.com/en/contact) for non-SDK related issues like this one. 

This is related to our Auto CPM product, which you can read more about [here](https://developers.mopub.com/publishers/ui/networks/#understand-auto-cpm). If you hover over the dotted line underlinng the rate, there are messages as to why the CPM is currently set that way. Looking at your screenshot provided, it looks like there isn't enough network data for auto cpm to generate an appropriate rate. We would recommend setting your own rates and disabling auto cpm until there is enough network data.

**Comment by MrMechanical** [comment]
Thank you so much for the tip! So in summary is this behaviour expected for low impression count? I want to make sure I am not doing anything wrong.

My apologies for posting in the wrong area. For future support shall I fill out the form for "Get in touch with the MoPub team"? What is the best contact for non-SDK related issues?

Thank you so much for your help.

**Comment by estherchoix** [comment]
Hi @MrMechanical  - This is expected behavior for low impression count and revenue. Our best practice for setting a manual CPM is by setting the same CPM value as what is in the mediated demand source's UI. And with enough data, enabling auto cpm thereafter will automate this process. 

If you have any follow up questions regarding this inquiry or any non-related SDK questions and issues, please use our support portal here: https://www.mopub.com/en/contact
