### ISSUE TITLE
Chartboost not initializing "Failed resolution of Lcom/google/android/gms/common/GoogleApiAvailability"

### ISSUE THREAD

**Issue by MrMechanical** [mopub/mopub-unity-sdk#149]
Issue with Chartboost intializing related to "Failed resolution of Lcom/google/android/gms/common/GoogleApiAvailability". Thank you for the help.

- [X] I am submitting a bug report for existing functionality
- [X] I visited https://developers.mopub.com/ and found no answer
- [X] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [X] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.14.1
#### Device model and OS Version:
Mac OS Macbook Air 2020
#### Unity Version:
2019.4.13f1
#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.

#### Expected behavior:
As concisely as possible, describe the expected behavior.
Chartboost intializes
#### Observed behavior:
As concisely as possible, describe the observed behavior.
Error in Android logcat.

#### Evidence:
Device log files, Network log file, etc.
2020/11/06 19:31:39.203 29593 29593 Verbose CBRequest Request failure: https://live.chartboost.com/api/install status: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/GoogleApiAvailability;
2020/11/06 19:31:39.204 29593 29593 Verbose CBRequest Request failure: https://live.chartboost.com/webview/v2/prefetch status: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/GoogleApiAvailability;
2020/11/06 19:31:39.202 29593 29593 Verbose CBRequest Request failure: https://live.chartboost.com/api/config status: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/GoogleApiAvailability;
<img width="1361" alt="Screen Shot 2020-11-06 at 7 40 22 PM" src="https://user-images.githubusercontent.com/28378318/98426710-ec1d5e00-2067-11eb-9ab5-e3856793b0e7.png">

**Comment by chauduyphanvu** [comment]
@MrMechanical, could you confirm if you have included the following two dependencies in your Unity build?

* `com.google.android.gms.play-services-ads-base`
* `com.google.android.gms.play-services-ads-identifier`

More information is available on the Chartboost page at https://developers.mopub.com/publishers/mediation/networks/chartboost/#download-and-integrate. Let us know if the issue persists.

Vu Chau
MoPub Team

**Comment by MrMechanical** [comment]
My apologies for the late response, the dependencies are in the project.

**Comment by chauduyphanvu** [comment]
@MrMechanical, thanks for the confirmation! Having those dependencies declared should be sufficient, so if you are still encountering the `NoClassDefFoundError` errors for those dependencies, do you by chance have Proguard or some post-build processes that might remove the classes in question?

You can also reverse engineer the APK to ensure that the classes successfully make their way to the APK.

**Comment by chauduyphanvu** [comment]
No repro. Closing.
