### ISSUE TITLE
Admob Consent

### ISSUE THREAD

**Issue by mertkurum** [mopub/mopub-unity-sdk#15]
NPA setting for Admob is implemented for Android & iOS sdks. When will Unity SDK be updated for this setting?

**Comment by aornelas** [comment]
Hi there,

Do you mean that the setting is implemented for the MoPub Android and iOS SDKs? could you point to the relevant code?

Also, have you looked at our meditation repo already? (https://github.com/mopub/mopub-unity-mediation)

Thanks!

**Comment by mertkurum** [comment]
https://github.com/mopub/mopub-android-mediation/commit/0d43ef879728d31f492d5eb33f310a56bc63673e

There should be a way to set this value through Unity. Maybe it can be added to OnConsentStatus changed event.

**Comment by aornelas** [comment]
Ah thanks for the link. We'll look into it and prioritize accordingly.

Thanks!

**Comment by aornelas** [comment]
This has been fixed in the [5.1.0 release](https://github.com/mopub/mopub-unity-sdk/releases/tag/v5.1.0).

Thanks again for reporting!
