### ISSUE TITLE
iOS won't build with `use_frameworks!` in `Podfile`

### ISSUE THREAD

**Issue by manelizzard** [mopub/mopub-unity-sdk#151]
iOS won't build with `use_frameworks!` in `Podfile`

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.15.0
#### Device model and OS Version:
N/A
#### Unity Version:
2019.4.13f1
#### Ad Unit IDs used in reproducing the issue:
N/A
#### Steps to reproduce the behavior:
Try to build an iOS project from a Unity game/app with Facebook SDK (this adds `use_frameworks!` directive to `Podfile`) and MoPub SDK (with some mediated network, ie: FAN).

#### Expected behavior:
Build and run without issues on an iOS device

#### Observed behavior:
XCode build fails with: `MoPub.h file not found` in `MoPubManager.h`

Might be related or be interesting for https://github.com/mopub/mopub-unity-sdk/issues/117: Having a public pod instead of the _local_ library would help

#### Evidence:
Sample project and screenshot.

[MoPubAndFacebook.zip](https://github.com/mopub/mopub-unity-sdk/files/5575970/MoPubAndFacebook.zip)

![image (4)](https://user-images.githubusercontent.com/895589/99844472-6a532780-2b73-11eb-9c5f-1729e5cff2f7.png)

#### Workaround:
1. Remove `<iosPod name="MoPub-SDK-Plugin" minTargetSdk="10.0" path="Assets/MoPub/Plugins/iOS"/>` from `MoPubDependencies.xml`
2. Delete *Assets/MoPub/Plugins/iOS/MoPub-SDK-Plugin.podspec*
3. Check *iOS* as platform for plugin for all files inside *Assets/MoPub/Plugins/iOS*
<img width="343" alt="Captura de pantalla 2020-11-20 a las 21 08 28" src="https://user-images.githubusercontent.com/895589/99845249-9fac4500-2b74-11eb-9f95-2439f8e4c346.png">

**Comment by chauduyphanvu** [comment]
@manelizzard, thanks for the info! The team is investigating this issue. We'll share an update soon.

Vu Chau
MoPub Team

**Comment by aornelas** [comment]
hi @manelizzard, thanks for reporting; i tried reproducing the issue and noticed that the FAN SDK includes an older version of the External Dependency Manager (f.k.a. Unity Jar Resolver), which collides with the version we include. i was able to successfully build the project by unchecking the PlayServicesResolver directory when importing the FAN SDK:
<img width="791" alt="Screen Shot 2020-11-23 at 5 15 42 PM" src="https://user-images.githubusercontent.com/286010/100033743-96f38300-2daf-11eb-9513-a88ab3fad5fd.png">

could you please give that a try and let us know if that solves the issue for you?

thanks!

**Comment by manelizzard** [comment]
He'll @aornelas. I also tried updating EDM4U to its latest version. You say it is building, can I see the generates Podfile? Please notice the bug is XCode not building. Unity builds without issues

**Comment by chauduyphanvu** [comment]
@manelizzard, thanks for the clarification.

Looking at the [best practices](https://stackoverflow.com/questions/33492873/using-cocoapods-without-use-frameworks-in-swift/49347198#49347198), it appears `use_frameworks!` is not needed anymore for Swift frameworks. Are you able to build your app without `use_frameworks!` (if allowed by the CocoaPods version you use)?

**Comment by manelizzard** [comment]
Hello @chauduyphanvu, thanks for the reference. Well yes, seems `use_frameworks!` should not be longer used, but Facebook SDK for Unity does (https://github.com/facebook/facebook-sdk-for-unity/blob/55ee928b1c3a875dd17cd402495dfd623f63fe66/Facebook.Unity.Editor/FacebookPostprocess.cs#L47), and the sample project won't compile without `use_frameworks!` directive.

Guess here is something Facebook needs to fix, but at least you are aware of this incompatibility.

Thanks for your time!

**Comment by chauduyphanvu** [comment]
@manelizzard - thanks! Let us know if you need additional assistance. As far as I know, frameworks shouldn't deliberately inject `use_frameworks!` into users' Podfile like that, so it's best if you check with Facebook and inquire why they need to do it.

**Comment by tontonpiero** [comment]
I don't want to wait for Facebook or Mopub to fix this issue, and I don't like to edit XCode settings everytime I want to build my app so I wrote a workaround that basically removes the 'use_frameworks!' line and reinstall the pods in a Unity post process build script:

```
[PostProcessBuild(int.MaxValue)]
private static void ProcessPodfile(BuildTarget buildTarget, string path)
{
    if (buildTarget == BuildTarget.iOS)
    {
        // remove use_frameworks! in Podfile
        using (var proc = new Process())
        {
            string directory = Directory.GetCurrentDirectory();
            string currentdirectory = Directory.GetCurrentDirectory();
            proc.StartInfo.WorkingDirectory = path;
            proc.StartInfo.FileName = @"sed";
            proc.StartInfo.Arguments = "-i '' \"s/use_frameworks\\!/ /g\" Podfile";
            proc.StartInfo.UseShellExecute = false;
            proc.StartInfo.CreateNoWindow = true;
            proc.StartInfo.RedirectStandardOutput = true;
            proc.Start();
            while (!proc.StandardOutput.EndOfStream)
            {
                string line = proc.StandardOutput.ReadLine();
            }
        }

        // update pods
        using (var proc = new Process())
        {
            string directory = Directory.GetCurrentDirectory();
            string currentdirectory = Directory.GetCurrentDirectory();
            proc.StartInfo.WorkingDirectory = path;
            proc.StartInfo.FileName = @"pod";
            proc.StartInfo.Arguments = "update";
            proc.StartInfo.UseShellExecute = false;
            proc.StartInfo.CreateNoWindow = true;
            proc.StartInfo.RedirectStandardOutput = true;
            proc.Start();
            while (!proc.StandardOutput.EndOfStream)
            {
                string line = proc.StandardOutput.ReadLine();
            }
        }
    }
}
```

I'm not sure if this is the best approach but at least it's working...
