### ISSUE TITLE
Ad failed to show: (-1401) Rewarded ad is not ready to be presented.

### ISSUE THREAD

**Issue by brunodp** [mopub/mopub-unity-sdk#152]
When closing a Rewarded Video before the end, the SDK gets in a weird state where it cycles between bailing out with "Ad failed to show: (-1401) Rewarded ad is not ready to be presented." and showing one properly

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.15.0

#### Device model and OS Version:
iPhone X - iOS 14.2

#### Unity Version:
2018.4.28

#### Xcode Version:
12.2

#### Ad Unit IDs used in reproducing the issue:
e659e1d114b1447ab5de0ffcd497dae1

#### Steps to reproduce the behavior:
1. Load and display a Rewarded Video that provides option of closing before its done
2. Close it before it finishes
3. Try to load and display a new one (it should bail out)
4. Try to load and display a new one (it should work)
5. Goto 3

#### Expected behavior:
I'm getting the OnRewardedVideoLoadedEvent callback, so I'd expect to either get a failure at that point and not actually getting the OnRewardedVideoFailedToPlayEvent callback when trying to display, if the issue was that it actually is failing .

#### Evidence:
This is an iOS build off a Unity Project. Android works properly.

[MoPubAbstractAd]:OnRewardedVideoLoadedEvent -- Rewarded Ad Loaded
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
GameBakeSystems.Adverts.MoPubAbstractAd:OnRewardedVideoLoadedEvent(String)
System.Action`1:Invoke(T)
MoPubManager:EmitRewardedVideoLoadedEvent(String)

....

2020-11-24 09:11:04.777887+0000 [13510:1840235] bailing out on showing rewarded video since it has not been loaded yet.
2020-11-24 09:11:04.778216+0000 [13510:1842021] 
	[MoPub][MPRewardedVideoAdManager][e659e1d114b1447ab5de0ffcd497dae1] Attempting to show ad
2020-11-24 09:11:04.778478+0000 [13510:1842021] 
	[MoPub][MPRewardedVideoAdManager][e659e1d114b1447ab5de0ffcd497dae1] Ad failed to show: (-1401) Rewarded ad is not ready to be presented.
[MoPubAbstractAd]:OnRewardedVideoFailedToPlayEvent -- Failed to Play

**Comment by chauduyphanvu** [comment]
@brunodp, thanks for letting us know! Did you see that happen in our Unity sample project as well? Could you paste the actual code snippet you are using to request and show ads?

Thanks!
Vu Chau
MoPub Team

**Comment by brunodp** [comment]
I've tried to reproduce with a simpler project. The project I'm currently working on has an over engineered Ad management system, that'd take me pasting 4 or 5 classes to show all the code that's running just to show an Ad. Anyway, I'll try and replicate tomorrow, and will post an update here.

**Comment by brunodp** [comment]
Ok, @chauduyphanvu , I've managed to replicate this within a simple project. It might come down to being an adapter issue that's not happening anymore with the latest versions, as I ended up getting the same versions of the adapters I'm running on the actual project before I was able to actually trigger the issue. 

I'm attaching the Unity Project and the entire xcode log, from app launch, to display RV and close it before it ends and then try to display a new one and get the failed to display callback.

[xcode-log.txt](https://github.com/mopub/mopub-unity-sdk/files/5601364/xcode-log.txt)
[MoPub Bug Hunt.zip](https://github.com/mopub/mopub-unity-sdk/files/5601366/MoPub.Bug.Hunt.zip)

**Comment by chauduyphanvu** [comment]
Ah, this was due to an outdated adapter. Your project was using [v7.68.0.0](https://github.com/mopub/mopub-ios-mediation/blob/master/AdMob/CHANGELOG.md), and we added a fix in v7.68.0.1 to handle fullscreen ad dismissal with MoPub 5.15.0.

Once I've updated the adapter to v7.68.0.1/7.68.0.2, the issue on longer occurred. 

Closing this issue now. Let us know if you have any questions.
