### ISSUE TITLE
iOS build error - mopub.h file not found (Occurred again in 5.14.1)

### ISSUE THREAD

**Issue by devmchoi** [mopub/mopub-unity-sdk#154]
(iOS) Xcode Build Error:  'MoPub.h' file not found

#### Steps to reproduce the behavior:
Import Mopub Unity SDK 5.14.1. and make it's Cocoapods settings as workspace. Build for iOS. So open that. Put creds on Xcode. Try building.

#### Expected behavior:
Build should be done without errors.

#### Observed behavior:
Fails with error.  'MoPub.h' file not found'

#### Evidence:
Please see attached screenshot. 

![Screen Shot 2020-12-09 at 5 03 45 PM](https://user-images.githubusercontent.com/1491204/101601875-89412d00-3a40-11eb-97df-08eedcbaca26.png)

**Comment by hmertkahraman** [comment]
Hi @devmchoi ,

Thanks for reaching out. We have several questions for you to understand the issue better:

- How did you integrate MoPub on Unity, did you use our [MoPub SDK Manager Plugin](https://developers.mopub.com/publishers/unity/integrate/#option-1-use-the-sdk-manager-recommended)? Or did you [manually integrate](https://developers.mopub.com/publishers/unity/integrate/#option-2-integrate-manually)?

- Can you please share your Cocoapods entries of your exported iOS project relating to MoPub? Did you check if they point to valid places in your project structure that contains MoPub podspec?

To fully verify: Please try again with a fresh clone from scratch, try SDK Manager Plugin to install latest version of MoPub, Build to iOS (don't run),  execute `pod install` at first and then `pod update` commands on your exported iOS project. Ensure cocoapods installs mopub correctly.  Then open the Workspace file, not the project file. Clean and build the project.

Thanks,
MoPub Team

**Comment by devmchoi** [comment]
I've tested it for only just imported 5.14.1 sdk only on unity 2019.4.5 and It succeeded.
for build that i mentioned here with error that sdk with 3rd party sdk so i guess it's closed. Sorry confusing issue again.
