### ISSUE TITLE
MoPub iOS 5.15.0 build size is bigger 5.14.x, related to ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = YES

### ISSUE THREAD

**Issue by psstevenchan** [mopub/mopub-unity-sdk#155]
MoPub iOS 5.15.0 app build size (31 MB) is bigger 5.14.x app build size (18 MB) a lot , related to ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = YES

**Comment by p158276** [comment]
Hi @psstevenchan , 

In [5.15](https://github.com/mopub/mopub-ios-sdk/blob/master/CHANGELOG.md), the iOS SDK now contains Swift code. This will increase the shipped binary size for the project which supporting older versions of iOS (< 12.4) if the codebase doesn’t already contain Swift code.

Yoyo Lin
MoPub Team

**Comment by psstevenchan** [comment]
Is that mean if iOS min version become 13.0, it don't need to embed swift standard library ?

**Comment by p158276** [comment]
That's right. For the user who uses the 12.3 iOS version and below, the download size will become bigger.
