### ISSUE TITLE
If multiple AdUnitID RewardedAd are loaded, OnRewardedVideoShownEvent is triggered with wrong AdUnitId

### ISSUE THREAD

**Issue by psstevenchan** [mopub/mopub-unity-sdk#158]
If multiple AdUnitID RewardedAd are loaded, OnRewardedVideoShownEvent is triggered with wrong AdUnitId

#### Ad Unit IDs used in reproducing the issue:
6679779b49724de897baaba2e86862f9, efd4d35268e94305b4c51e16d0634082
use IronSource Network

#### Steps to reproduce the behavior:
1. Load 6679779b49724de897baaba2e86862f9
2. Load efd4d35268e94305b4c51e16d0634082
3. Play 6679779b49724de897baaba2e86862f9
4. Close Ad after finished

#### Expected behavior:
OnRewardedVideoShownEvent - adUnitId:6679779b49724de897baaba2e86862f9

#### Observed behavior:
OnRewardedVideoShownEvent - adUnitId:efd4d35268e94305b4c51e16d0634082

#### Evidence:
default	12:15:24.398144+0800	myvegas	[MoPub-Unity] [InitializeSdk] SDK initialization started
MoPubLog:Log(String, String, Object[])
MoPub:InitializeSdk(SdkConfiguration)
MoPubDemoGUI:Awake()
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
default	12:15:24.435698+0800	myvegas	
	[MoPub][MPViewabilityManager] Initialized OM SDK version: 1.3.4-Mopub
default	12:15:24.518898+0800	myvegas	2 RewardedVideo AdUnits loaded for plugins:
6679779b49724de897baaba2e86862f9, efd4d35268e94305b4c51e16d0634082
MoPub:LoadPluginsForAdUnits(String[], String)
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
default	12:15:27.771219+0800	myvegas	[MoPub-Unity] [EmitSdkInitializedEvent] SDK initialized and ready to display ads.  Log Level: Info
MoPubLog:Log(String, String, Object[])
MoPubManager:EmitSdkInitializedEvent(String)
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
default	12:15:27.776205+0800	myvegas	OnSdkInitializedEvent - adUnitId:6679779b49724de897baaba2e86862f9
System.Action`1:Invoke(T)
MoPubManager:EmitSdkInitializedEvent(String)
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
default	12:15:28.525369+0800	myvegas	[AppLovinSdk] DEBUG [AppLovinSdk] 
========================================
AppLovin SDK
Version: 6.14.9
Plugin Version: 
Ad Review Version: 
OS: iOS 12.4.6
IDFA: <Enable verbose logging to see the IDFA to use for test devices - https://monetization-support.applovin.com/hc/en-us/articles/236114328-How-can-I-expose-verbose-logging-for-the-SDK>
SDK Key: tTcq5yQKuAfdTl2tyZk32pTW-_Q_GaJ83wy8sNSlX6N0sPtpzas_NKWLJyLaWeiZTfhP199ZFWZ6wQvu0mtO4O
Model: iPad4,4
Locale: en_HK
Simulator: 0
Bundle ID: com.playstudios.myvegas
Has AppLovinSDKResources: true
Test Mode On: false
Verbose Logging On: false
Mediation Provider: (null)
TG: 87
===Privacy States===
Please review AppLovin MAX documentation to be compliant with regional privacy policies.

Age Restricted User - No value set
Has User Consent - No value set
"Do Not Sell" - No value set
===App Tracking Transparency===
Authorization Status: Unavailable (-1)
NSUserTrackingUsageDescription Exists: true
========================================
default	12:15:31.939436+0800	myvegas	requesting rewarded video with AdUnit: 6679779b49724de897baaba2e86862f9
MoPubDemoGUI:CreateRewardedVideosSection()
MoPubDemoGUI:OnGUI()
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
default	12:15:31.939528+0800	myvegas	Status Label updated to: Requesting 6679779b49724de897baaba2e86862f9
MoPubDemoGUI:CreateRewardedVideosSection()
MoPubDemoGUI:OnGUI()
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
default	12:15:31.939619+0800	myvegas	[MoPub-Unity] [RequestRewardedVideo] Attempting to load ad
MoPubLog:Log(String, String, Object[])
MoPub:RequestRewardedVideo(String, List`1, String, String, Double, Double, String)
MoPubDemoGUI:CreateRewardedVideosSection()
MoPubDemoGUI:OnGUI()
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
default	12:15:31.939709+0800	myvegas	
	[MoPub][MPRewardedVideoAdManager][6679779b49724de897baaba2e86862f9] Attempting to load ad
default	12:15:32.950839+0800	myvegas	
	[MoPub][MPRewardedVideoAdManager] Rewarded video ad is fetching ad type: custom
default	12:15:33.935946+0800	myvegas	[MoPub-Unity] [EmitRewardedVideoLoadedEvent] Ad loaded
MoPubLog:Log(String, String, Object[])
MoPubManager:EmitRewardedVideoLoadedEvent(String)
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
default	12:15:33.936295+0800	myvegas	OnRewardedVideoLoadedEvent - adUnitId:6679779b49724de897baaba2e86862f9
MoPubDemoGUI:OnRewardedVideoLoadedEvent(String)
System.Action`1:Invoke(T)
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
default	12:15:33.944205+0800	myvegas	
	[MoPub][MPRewardedVideoAdManager][6679779b49724de897baaba2e86862f9] Ad loaded
default	12:15:33.946293+0800	myvegas	GetAvailableRewards found 1 rewards for ad unit 6679779b49724de897baaba2e86862f9
MoPub:GetAvailableRewards(String)
MoPubDemoGUI:OnRewardedVideoLoadedEvent(String)
System.Action`1:Invoke(T)
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
default	12:15:33.946387+0800	myvegas	Status Label updated to: Loaded 6679779b49724de897baaba2e86862f9
MoPubDemoGUI:OnRewardedVideoLoadedEvent(String)
System.Action`1:Invoke(T)
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
default	12:15:45.303560+0800	myvegas	
	[MoPub][MPRewardedVideoAdManager] Rewarded video ad is fetching ad type: custom
default	12:29:35.668262+0800	myvegas	Status Label updated to: 
MoPubDemoGUI:CreateRewardedVideosSection()
MoPubDemoGUI:OnGUI()
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
default	12:29:35.668366+0800	myvegas	showing rewarded video with AdUnit: 6679779b49724de897baaba2e86862f9
MoPubDemoGUI:CreateRewardedVideosSection()
MoPubDemoGUI:OnGUI()
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
default	12:29:35.668454+0800	myvegas	[MoPub-Unity] [ShowRewardedVideo] Attempting to show ad
MoPubLog:Log(String, String, Object[])
MoPub:ShowRewardedVideo(String, String)
MoPubDemoGUI:CreateRewardedVideosSection()
MoPubDemoGUI:OnGUI()
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
default	12:29:35.669709+0800	myvegas	
	[MoPub][MPRewardedVideoAdManager][6679779b49724de897baaba2e86862f9] Attempting to show ad
default	12:30:18.676697+0800	myvegas	[MoPub-Unity] [EmitRewardedVideoShownEvent] Ad shown
MoPubLog:Log(String, String, Object[])
MoPubManager:EmitRewardedVideoShownEvent(String)
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
default	12:30:18.679075+0800	myvegas	OnRewardedVideoShownEvent - adUnitId:efd4d35268e94305b4c51e16d0634082
System.Action`1:Invoke(T)
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
default	12:30:18.682305+0800	myvegas	OnImpressionTrackedEvent - adUnitId:efd4d35268e94305b4c51e16d0634082 with impression data: 
MoPubDemoGUI:OnImpressionTrackedEvent(String, ImpressionData)
System.Action`2:Invoke(T1, T2)
MoPubManager:EmitImpressionTrackedEventHandler(String, Boolean)
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
default	12:30:18.682499+0800	myvegas	Status Label updated to: Impression tracked for efd4d35268e94305b4c51e16d0634082 with impression data: 
MoPubDemoGUI:OnImpressionTrackedEvent(String, ImpressionData)
System.Action`2:Invoke(T1, T2)
MoPubManager:EmitImpressionTrackedEventHandler(String, Boolean)
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
default	12:30:18.688082+0800	myvegas	OnRewardedVideoReceivedRewardEvent - adUnitId:efd4d35268e94305b4c51e16d0634082, label:MPMoPubRewardedVideoRewardCurrencyTypeUnspecified, amount:0
MoPubDemoGUI:OnRewardedVideoReceivedRewardEvent(String, String, Single)
System.Action`3:Invoke(T1, T2, T3)
MoPubManager:EmitRewardedVideoReceivedRewardEvent(String)
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
default	12:30:18.688129+0800	myvegas	OnRewardedVideoClosedEvent - adUnitId:efd4d35268e94305b4c51e16d0634082
MoPubDemoGUI:OnRewardedVideoClosedEvent(String)
System.Action`1:Invoke(T)
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
default	12:30:18.689858+0800	myvegas	Status Label updated to: Dismissed efd4d35268e94305b4c51e16d0634082
MoPubDemoGUI:AdDismissed(String)
System.Action`1:Invoke(T)
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
default	12:30:18.689919+0800	myvegas	Status Label updated to: 
System.Action`1:Invoke(T)
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

**Comment by hmertkahraman** [comment]
Hi @psstevenchan ,

Our SDK currently doesn't support multiple RV caching. Our RV Manager works in a Singleton architecture and will only allow you to cache and show one RV at a time. It will show the latest cached RV. 

Please only request and show one RV ad unit at a time.

Thanks,
Mert

**Comment by psstevenchan** [comment]
the MoPub Unity SDK API MoPub.HasRewardedVideo(adUnitId) doesn't make sense if it only cache the latest RV.
In the MoPub documentation, it doesn't mention this limitation.
https://developers.mopub.com/publishers/unity/rewarded-video/#known-limitations

**Comment by hmertkahraman** [comment]
Hi @psstevenchan,

Thanks for the feedback!

`HasRewardedVideo` can be used to check if the RV was successfully loaded and ready to show. Several of our adapters use this method to make sure ad is available before show attempt.

Hope this helps.

Mert
