### ISSUE TITLE
[Feature Request] OnRewardedVideoLoadedEvent contain mediation network name.

### ISSUE THREAD

**Issue by psstevenchan** [mopub/mopub-unity-sdk#159]
When Request Video Ad, there is Log message that showing what Ad network name is loaded, is it possible to pass that into OnRewardedVideoLoadedEvent or other new API to get loaded Ad network name ?

**Comment by p158276** [comment]
Hi @psstevenchan ,
Thanks for providing the feedback. 
Could you share with us more details about the use case and why this feature is needed? 

Yoyo Lin
MoPub Team

**Comment by psstevenchan** [comment]
when mopub sdk request Ad with error e.g. no fill, we want to know which Ad network has problem, so that we can troubleshoot easily.

**Comment by p158276** [comment]
Hi @psstevenchan ,

Thanks for the feedback. We don't have the network name in our ad fill callback at this moment. We'll circle back to our team and see how we can work in our future release. At this moment, you can check the log which will show the loaded ad's custom event class name.
