### ISSUE TITLE
No ad config.. Caused by: null

### ISSUE THREAD

**Issue by ageofpearl** [mopub/mopub-unity-sdk#162]
Admob Ads won't load on unity (android), but working well on ios.
Admob support speach - "Its on mopub side error".

We done everythink already(change pc, change plugin version, ndk, sdk, jdk..), but ads wont work even on empty project on many different unity versions, same error all time.
Another networks work well, without problem.
Thanks.

#### MoPub SDK Version:
5.15.0 (1.9,2 admob)

#### Device model and OS Version:
In any device or android versions

#### Unity Version:
2019+

#### Ad Unit IDs used in reproducing the issue:
07b6a15468e048f1936aae3e82bab468

#### Evidence:

[onRewardedAdFailedToLoad][ca-app-pub-9306779210875415/3147066614] Adapter GooglePlayServicesRewardedVideo failed to load ad: (null) null
12-22 15:58:14.993: I/MoPub(17129): [com.mopub.mobileads.GooglePlayServicesRewardedVideo$1][onRewardedAdFailedToLoad][ca-app-pub-9306779210875415/3147066614] Adapter GooglePlayServicesRewardedVideo Log - Failed to load Google rewarded video with message: No ad config.. Caused by: null

Log:
[fulllog.txt](https://github.com/mopub/mopub-unity-sdk/files/5814053/fulllog.txt)

Some extra info:
![ev2_manifest](https://user-images.githubusercontent.com/17089547/104584808-33315c00-5674-11eb-9a80-53164478b1b3.JPG)
![ev1_settings](https://user-images.githubusercontent.com/17089547/104584812-33c9f280-5674-11eb-9752-3cecb11c42a6.JPG)

Issue:
![StrangeError](https://user-images.githubusercontent.com/17089547/104585337-ea2dd780-5674-11eb-96a4-23a9df5609c3.png)

Rest:

[mainTemplate.txt](https://github.com/mopub/mopub-unity-sdk/files/5814202/mainTemplate.txt)
[baseProjectTemplate.txt](https://github.com/mopub/mopub-unity-sdk/files/5814203/baseProjectTemplate.txt)
[gradleTemplate.txt](https://github.com/mopub/mopub-unity-sdk/files/5814204/gradleTemplate.txt)
[launcherTemplate.txt](https://github.com/mopub/mopub-unity-sdk/files/5814205/launcherTemplate.txt)

**Comment by chauduyphanvu** [comment]
@ageofpearl, this seems like an ad unit setup issue. Do any other ad unit IDs with AdMob work for you? Here's one that works for me: **faef74616c604395bbf155138b9d0185**.

If that ad unit ID works for you too, then it means something is not properly configured for your ad unit ID. If that ad unit ID does not work for you, my suggestion is for you to try your ad unit IDs in our [Unity sample app](https://github.com/mopub/mopub-unity-sdk/tree/master/unity-sample-app) on this repository. The purpose is to narrow down the causes so we can further help you debug the issue.

Vu Chau
MoPub Team
