### ISSUE TITLE
iOS build crashes on launch

### ISSUE THREAD

**Issue by istvanContXtual** [mopub/mopub-unity-sdk#164]
Terminating app due to uncaught exception 'GADInvalidInitializationException', reason: 'The Google Mobile Ads SDK was initialized without an application ID.

Unity SDK seems to behave as expected in editor, getting all expected logs such as initialized, loaded, simulating presenting an ad etc.
I seen similar issues reported, recommended fix to edit pList. We are using unity cloud build so ideally should be buildable without editing the generated Xcode project.

Thank you,
I

#### MoPub SDK Version:
5.15.0

#### Device model and OS Version:
iPhone XR, 14.2

#### Unity Version:
2020.2.1f1

#### Ad Unit IDs used in reproducing the issue:
e013490de3794948a9eaa3e49b4db803

#### Steps to reproduce the behavior:
build for iOS and run in Xcode. 
It crashes in launch w error:b GADInvalidInitializationException

#### Expected behavior:
Initialize plugin as expected

#### Observed behavior:
As concisely as possible, describe the observed behavior.

#### Evidence:
2021-01-27 11:54:01.053535-0800 ******* [2608:551920] *** Terminating app due to uncaught exception 'GADInvalidInitializationException', reason: 'The Google Mobile Ads SDK was initialized without an application ID. Google AdMob publishers, follow instructions at https://googlemobileadssdk.page.link/admob-ios-update-plist to set a valid application ID. Google Ad Manager publishers, follow instructions at https://googlemobileadssdk.page.link/ad-manager-ios-update-plist.'
*** First throw call stack:
(0x18f6ec878 0x1a3c42c50 0x18f5f45c8 0x104f8cbbc 0x104f3a570 0x18f2df24c 0x18f2e0db0 0x18f2e3ddc 0x18f2f193c 0x18f2f2120 0x1d8b047c8 0x1d8b0b75c)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'GADInvalidInitializationException', reason: 'The Google Mobile Ads SDK was initialized without an application ID. Google AdMob publishers, follow instructions at https://googlemobileadssdk.page.link/admob-ios-update-plist to set a valid application ID. Google Ad Manager publishers, follow instructions at https://googlemobileadssdk.page.link/ad-manager-ios-update-plist.'
terminating with uncaught exception of type NSException

**Comment by chauduyphanvu** [comment]
@istvanContXtual, please follow the [instructions](https://developers.google.com/admob/android/quick-start#update_your_androidmanifestxml) here to initialize the AdMob SDK.

Vu Chau
MoPub Team

**Comment by istvanbbartha** [comment]
Hi Vu Chau,

Thank you for the quick reply.

The instructions you sent are not very useful as I am not building for android devices.

The issue i am having is with the MoPub UNITY Sdk - published for iOS. I am getting the issue in xCode - not sure how the androidmanifest will help me solving it 

Thank you,
Istvan

**Comment by chauduyphanvu** [comment]
@istvanbbartha, the iOS instructions are at https://developers.google.com/admob/ios/quick-start#update_your_infoplist (it is linked in the crash log).

**Comment by istvanContXtual** [comment]
Hi,

thanks again.

Is there a way to build a unity project and have a working Xcode project that builds without errors?
We are using unity cloud build and can't edit the generated Xcode project.

Best,
I

**Comment by chauduyphanvu** [comment]
Hello, we currently do not have recommendations for achieving that directly from Unity. You might have to build custom scripts that inject the ID to the info.plist in your workflow.

Google requires this ID to be present upon app launch (before MoPub initializes), so you don't have the ability to forward/register this ID via MoPub's APIs.
