### ISSUE TITLE
How to set FacebookAudienceNetwork's setAdvertiserTrackingEnabled?

### ISSUE THREAD

**Issue by zenith-jacob** [mopub/mopub-unity-sdk#166]
Facebook updated it's Facebook Audience Network to 9.0.0 alongside with the adapters to 6.2.0 (Android) and 6.2.1 (iOS).

There's a guide on their website on how to set `setAdvertiserTrackingEnabled `but it only applies to native apps. There's a Unity section but it's for apps using FAN as a main network if I'm not mistaken - not for the case when FAN is being used as a mediation adapter.

Here's that guide:
https://developers.facebook.com/docs/audience-network/guides/advertising-tracking-enabled/

We're unable to find `AudienceNetwork.AdSettings` classes anyway anywhere in the Mopub's files/unity classes so I guess we're right.

What's the current state on that? Is that implemented and we can call it somehow through Unity?
We were thinking on implementing that call ourselves in the XCode project, but we're unsure where to put it. 
Maybe somewhere in `FacebookAdapterConfiguration.m` in `initializeNetworkWithConfiguration`?

- [X] I am submitting a bug report for existing functionality
- [X] I visited https://developers.mopub.com/ and found no answer
- [X] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [X] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.15

#### Device model and OS Version:
All kinds of Iphones & Androids

#### Unity Version:
2020.2.1f1

#### Ad Unit IDs used in reproducing the issue:
---

**Comment by chauduyphanvu** [comment]
@zenith-jacob, you are correct that that API is not currently supported by MoPub, and that publishers will have to call it directly from their apps.

I would not recommend manually modifying the adapters to make that call, as your change will be wiped out when you update to the next adapter version. Let us know if you are able to call it via a Unity script. If that proves to be cumbersome, we can explore exposing a setter in the adapters that can help forward the flag on your behalf.

Vu Chau
MoPub Team

**Comment by zenith-jacob** [comment]
@chauduyphanvu Well since there's a way of calling Java methods through reflection API directly from Unity, I believe there's the same way of doing it in Objective-C/Swift but I'm currently too busy to try to test it out.

I will probably leave it like that and just replace it manually for now. 
You'll probably need to support this eventually since it might be enforced in March by Facebook alongside the privacy changes/IDFA and other stuff.

**Comment by zenith-jacob** [comment]
Also, just as a side-note. I'm unsure in what state of development the Mopub Unity SDK currently is but just so you know - it's impossible to build atm because of the issue below:

https://github.com/mopub/mopub-unity-sdk/issues/161

We had to make additional changes to the SDK to be able to compile properly on iOS.
So you know - you can kill two birds with one stone 🥇

**Comment by chauduyphanvu** [comment]
@zenith-jacob, sounds good, we can look into supporting this in the mediation adapters. Stay tuned!

**Comment by chauduyphanvu** [comment]
@zenith-jacob, thanks for your patience. We have decided to _not_ support this use case in the adapters, as it is a contract between Facebook Audience Network and the publishers, so you must be passing it directly from your code. 

While we do not have any recommendations or custom solutions, we have heard from other publishers that they were able to do this from Unity via custom native plugins.

Let us know if there are any questions.

**Comment by firatagdas** [comment]
If you are willing to maintain the changes, I would recommend the custom solution for this.

First you need to extend Facebook class of MoPub.

```
    public class FacebookCustomAdapter : MoPub.SupportedNetwork.Facebook
    {
        public FacebookCustomAdapter(bool? trackingEnabled)
        {
            if (trackingEnabled != null)
            {
                NetworkConfiguration = new Dictionary<string, string> {
                    { "tracking_enabled", trackingEnabled.Value ? "true" : "false" }
                };
            }
        }
    }

```

then add following code after this line:

https://github.com/mopub/mopub-ios-mediation/blob/master/FacebookAudienceNetwork/FacebookAdapterConfiguration.m#L83

```
static NSString * const kFacebookTrackingEnabled = @"tracking_enabled";
```

add following code before this line:

https://github.com/mopub/mopub-ios-mediation/blob/master/FacebookAudienceNetwork/FacebookAdapterConfiguration.m#L83

```
NSString *trackingEnabled = configuration[kFacebookTrackingEnabled];
if (trackingEnabled != nil) {
	if ([trackingEnabled isEqualToString:@"true"]) {
		NSLog(@"Facebook advertising tracking value enabled.");
		[FBAdSettings setAdvertiserTrackingEnabled:YES];
	} else {
		NSLog(@"Facebook advertising tracking value disabled.");
		[FBAdSettings setAdvertiserTrackingEnabled:NO];
	}
}
```

Finally put your custom FacebookCustomAdapter class in use, 

```

...
    MoPub.InitializeSdk(
        new MoPub.SdkConfiguration {
            ...
            MediatedNetworks = new MoPubBase.MediatedNetwork[] {
                new FacebookCustomAdapter(trackingEnabled: false)
            }
        }
    );
...
```

**Comment by firatagdas** [comment]
Hello, 

Just create a file called "FacebookNativeAccess.mm" in "Assets/Plugins/iOS"

Put following code in it:

```
#import <Foundation/Foundation.h>
#import <FBAudienceNetwork/FBAudienceNetwork.h>

extern "C" {
    void _FBAdSetting_setAdvertiserTrackingEnabled(bool value) {
        NSLog(@"[FacebookAdSettings] Advetising Tracking Enabled: %@", value ? @"YES" : @"NO");
        [FBAdSettings setAdvertiserTrackingEnabled:value ? YES : NO];
    }
}
```

Select the "FacebookNativeAccess.mm" in Unity Editor and make sure iOS platform is the only target in the "Inspector"

Then create a C# class.

```
public static class FBAdSettingsNativeAccess
{
        public static void SetAdvertiserTrackingEnabled(bool value)
        {
            UnityEngine.Debug.Log("Trying to set setAdvertiserTrackingEnabled value on Facebook.");
            _FBAdSetting_setAdvertiserTrackingEnabled(value);
        }

#if UNITY_IOS && !UNITY_EDITOR		
		[DllImport("__Internal")]
		private static extern void _FBAdSetting_setAdvertiserTrackingEnabled(bool value);
#else
        private static void _FBAdSetting_setAdvertiserTrackingEnabled(bool value)
        {
            UnityEngine.Debug.LogWarning("This method only works on real iOS device.");
        }
#endif            
}
```

That is it!

**Comment by zenith-jacob** [comment]
I love you @firatagdas 
<3

**Comment by manelizzard** [comment]
Hello,

After implementing this solution, I am getting the following error:

```
Uncaught exception: FBFinalClassViolationException: FBAdSettings is a final class and cannot be subclassed
```

Anyone experienced this also? Thank you!

**Comment by firatagdas** [comment]
May be you didn't implement the code as suggested. If you change FBAdSettingsNativeAccess class name to FBAdSettings, then you might get this exception since that class already exists and used by Facebook SDK itself.

**Comment by manelizzard** [comment]
> May be you didn't implement the code as suggested. If you change FBAdSettingsNativeAccess class name to FBAdSettings, then you might get this exception since that class already exists and used by Facebook SDK itself.

No, it's exact the same than the solution proposed. It also happens with FB official proposed solution: https://developers.facebook.com/docs/audience-network/setting-up/platform-setup/ios/advertising-tracking-enabled

**Comment by firatagdas** [comment]
Can you post your version of implementation and can you also include the paths of the sources?
