### ISSUE TITLE
Admob banner Disappears

### ISSUE THREAD

**Issue by Cascade-Habib** [mopub/mopub-unity-sdk#168]
Admob banner shows upon first request but it disappears after few seconds[refresh interval]

- [ ] I am submitting a bug report for existing functionality
- [ ] I visited https://developers.mopub.com/ and found no answer
- [ ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ ] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.15
#### Device model and OS Version:
samsung A21
#### Unity Version:
2018.4.30
#### Ad Unit IDs used in reproducing the issue:
01a7eb6b22df47e4accb5c167fcc5663
#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.
Development environment: [use these settings please for testing the sample app as i reproduced many times using these settings]
    unity 2018.4.30
    Gradle used: gradle-6.8.1
    Used custom gradle template file [see it below]

[mainTemplate.txt](https://github.com/mopub/mopub-unity-sdk/files/6014032/mainTemplate.txt)

here is the sample app where you can reproduce the issue
https://www.dropbox.com/s/8vpfyftw9i9e3ly/unity-sample-app.zip?dl=0
if it requires NDK, then just go to build settings and then under "other settings" change the option"Scripting Background" to Mono. It will not require NDK then.

#### Expected behavior:
Admob banner once shown on the screen, it should refresh it automatically and should keep showing 
#### Observed behavior:
admob banner stays on the screen for few seconds upon first request, after few seconds admob banner disappears from screen and never show again automatically

#### Evidence:
here is the device log , admob app id is already added in manifest file, you can check in the above provided sample project
02-17 15:14:51.226 22636  9989 E Ads     : Ad size will not fit on screen
02-17 15:14:51.231 22636 22668 I Icing   : Usage reports ok 0, Failed Usage reports 0, indexed 0, rejected 0
02-17 15:14:51.244  9510  9510 I MoPub   : [com.mopub.mobileads.GooglePlayServicesBanner$AdViewListener][onAdFailedToLoad][ca-app-pub-8536546060048734/3809594094] Adapter GooglePlayServicesBanner failed to load ad: (10,000) Native Network or ad adapter was configured incorrectly.
02-17 15:14:51.246  9510  9510 I MoPub   : [com.mopub.mobileads.GooglePlayServicesBanner$AdViewListener][onAdFailedToLoad][ca-app-pub-8536546060048734/3809594094] Adapter GooglePlayServicesBanner Log - Failed to load Google banners with message: Error building request URL.. Caused by: null
02-17 15:14:51.248  9510  9510 I Ads     : Ad failed to load : 1
02-17 15:14:51.249  9510  9510 I MoPub   : [com.mopub.mobileads.AdViewController][loadFailUrl] SDK Log With Throwable - Load failed., Native Network or ad adapter was configured incorrectly.

**Comment by chauduyphanvu** [comment]
@Cascade-Habib, thanks for the report! We will take a look at the info provided and get back to you.

Vu Chau
MoPub Team

**Comment by chauduyphanvu** [comment]
@Cascade-Habib, I've reproduced the issue now. This seems to happen only when the game is in landscape orientation. If the game is in portrait orientation, I do not see the issue.

I'll investigate this further and get back to you.

**Comment by Cascade-Habib** [comment]
any solution for this please?

**Comment by chauduyphanvu** [comment]
@Cascade-Habib, the team is still investigating the issue. I will update this thread once I have more information. Stay tuned!

**Comment by Cascade-Habib** [comment]
We have more than 100 Games, and all of them need an urgent update.
We have been facing this issue since two months on more than 100 games, Our revenue loss is more than $50,000 because of this issue.
Is it our mistake that we chose mopub?
Could you please give us a solution as soon as possible.

**Comment by chauduyphanvu** [comment]
@Cascade-Habib, I have bumped the priority of this issue internally and will follow up with you once I hear back. Thank you for your patience.

**Comment by chauduyphanvu** [comment]
@Cascade-Habib, we've identified the cause of the issue and fixed it internally. If all looks good, the fix should be shipped with the upcoming SDK release. When there's more information, I will make sure to keep you updated.

Thanks!

**Comment by Cascade-Habib** [comment]
Thanks for the update.
1. Could you please let me know the approximate date for the upcoming SDK release?
2. If the next SDK release is not planned to be released within a week or so, Could you please let me know if i can do something to fix the issue while using sdk 5.15?

Thanks
