### ISSUE TITLE
Unity build failed with Admob Adapter

### ISSUE THREAD

**Issue by vinkens** [mopub/mopub-unity-sdk#170]
One line summary of the issue here

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ ] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
project:5.15.0
also tried 5.16.1 with sample project
#### Unity Version:
2019.4.18f1
#### Ad Unit IDs used in reproducing the issue:
test admob Id and test mopub Id

#### Steps to reproduce the behavior:
1,create a blank project 
2,import mopub unity pakage
3,install admob adapter in Mopub Manager
4,Force Resolve
5, build and failed

#### Expected behavior:
build success

#### Observed behavior:
build failed in "build gradle project" step

##### Log1
> Configure project :launcher
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2019.4.18f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\build-tools\28.0.3\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2019.4.18f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platform-tools\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2019.4.18f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platforms\android-29\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2019.4.18f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\tools\package.xml. Probably the SDK is read-only

> Task :launcher:preBuild UP-TO-DATE
> Task :unityLibrary:preBuild UP-TO-DATE
> Task :unityLibrary:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:checkReleaseManifest UP-TO-DATE
> Task :unityLibrary:MoPub.plugin:preBuild UP-TO-DATE
> Task :unityLibrary:MoPub.plugin:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:MoPub.plugin:checkReleaseManifest
> Task :unityLibrary:unity-android-resources:preBuild UP-TO-DATE
> Task :unityLibrary:unity-android-resources:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:processReleaseManifest
> Task :unityLibrary:unity-android-resources:checkReleaseManifest
> Task :unityLibrary:MoPub.plugin:processReleaseManifest
> Task :unityLibrary:MoPub.plugin:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:packageReleaseRenderscript NO-SOURCE
> Task :launcher:prepareLintJar UP-TO-DATE
> Task :unityLibrary:unity-android-resources:processReleaseManifest
> Task :unityLibrary:unity-android-resources:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:MoPub.plugin:packageReleaseRenderscript NO-SOURCE
> Task :unityLibrary:unity-android-resources:packageReleaseRenderscript NO-SOURCE
> Task :unityLibrary:generateReleaseBuildConfig UP-TO-DATE
> Task :unityLibrary:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:generateReleaseResValues UP-TO-DATE
> Task :unityLibrary:MoPub.plugin:compileReleaseRenderscript NO-SOURCE
> Task :launcher:preReleaseBuild
> Task :unityLibrary:unity-android-resources:compileReleaseRenderscript NO-SOURCE
> Task :launcher:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:generateReleaseResources UP-TO-DATE
> Task :launcher:compileReleaseRenderscript NO-SOURCE
> Task :launcher:checkReleaseManifest UP-TO-DATE
> Task :unityLibrary:MoPub.plugin:generateReleaseResValues
> Task :unityLibrary:unity-android-resources:generateReleaseResValues
> Task :unityLibrary:unity-android-resources:generateReleaseResources
> Task :unityLibrary:MoPub.plugin:generateReleaseResources
> Task :launcher:generateReleaseBuildConfig UP-TO-DATE
> Task :unityLibrary:packageReleaseResources UP-TO-DATE
> Task :unityLibrary:prepareLintJar UP-TO-DATE
> Task :unityLibrary:generateReleaseSources UP-TO-DATE
> Task :launcher:generateReleaseSources UP-TO-DATE
> Task :launcher:mainApkListPersistenceRelease UP-TO-DATE
> Task :unityLibrary:unity-android-resources:packageReleaseResources
> Task :launcher:generateReleaseResValues UP-TO-DATE
> Task :launcher:generateReleaseResources UP-TO-DATE
> Task :launcher:createReleaseCompatibleScreenManifests UP-TO-DATE
> Task :unityLibrary:unity-android-resources:generateReleaseRFile
> Task :unityLibrary:unity-android-resources:generateReleaseBuildConfig
> Task :unityLibrary:unity-android-resources:prepareLintJar UP-TO-DATE
> Task :unityLibrary:unity-android-resources:generateReleaseSources
> Task :unityLibrary:unity-android-resources:javaPreCompileRelease
> Task :unityLibrary:MoPub.plugin:packageReleaseResources
> Task :unityLibrary:MoPub.plugin:generateReleaseRFile
> Task :unityLibrary:prepareLintJarForPublish UP-TO-DATE
> Task :unityLibrary:MoPub.plugin:generateReleaseBuildConfig
> Task :unityLibrary:MoPub.plugin:prepareLintJar UP-TO-DATE
> Task :unityLibrary:MoPub.plugin:generateReleaseSources
> Task :unityLibrary:MoPub.plugin:javaPreCompileRelease
> Task :unityLibrary:generateReleaseRFile UP-TO-DATE
> Task :unityLibrary:mergeReleaseShaders UP-TO-DATE
> Task :unityLibrary:compileReleaseShaders UP-TO-DATE
> Task :unityLibrary:generateReleaseAssets UP-TO-DATE
> Task :unityLibrary:unity-android-resources:compileReleaseJavaWithJavac
> Task :unityLibrary:unity-android-resources:bundleLibCompileRelease
> Task :unityLibrary:unity-android-resources:prepareLintJarForPublish UP-TO-DATE
> Task :unityLibrary:unity-android-resources:mergeReleaseShaders
> Task :unityLibrary:unity-android-resources:compileReleaseShaders
> Task :unityLibrary:unity-android-resources:generateReleaseAssets
> Task :unityLibrary:unity-android-resources:packageReleaseAssets
> Task :unityLibrary:packageReleaseAssets
> Task :unityLibrary:unity-android-resources:bundleLibRuntimeRelease
> Task :launcher:processReleaseManifest
> Task :unityLibrary:processReleaseJavaRes NO-SOURCE
> Task :unityLibrary:unity-android-resources:processReleaseJavaRes NO-SOURCE
> Task :unityLibrary:unity-android-resources:bundleLibResRelease
> Task :unityLibrary:unity-android-resources:mergeReleaseJniLibFolders
> Task :unityLibrary:MoPub.plugin:compileReleaseJavaWithJavac
> Task :unityLibrary:unity-android-resources:transformNativeLibsWithMergeJniLibsForRelease
> Task :unityLibrary:MoPub.plugin:bundleLibCompileRelease
> Task :unityLibrary:MoPub.plugin:prepareLintJarForPublish UP-TO-DATE
> Task :unityLibrary:unity-android-resources:transformNativeLibsWithStripDebugSymbolForRelease
> Task :unityLibrary:MoPub.plugin:mergeReleaseShaders
> Task :unityLibrary:unity-android-resources:transformNativeLibsWithIntermediateJniLibsForRelease
> Task :unityLibrary:MoPub.plugin:compileReleaseShaders
> Task :unityLibrary:MoPub.plugin:generateReleaseAssets
> Task :unityLibrary:MoPub.plugin:packageReleaseAssets
> Task :unityLibrary:MoPub.plugin:bundleLibRuntimeRelease
> Task :unityLibrary:MoPub.plugin:processReleaseJavaRes NO-SOURCE
> Task :unityLibrary:MoPub.plugin:bundleLibResRelease
> Task :unityLibrary:MoPub.plugin:mergeReleaseJniLibFolders
> Task :unityLibrary:MoPub.plugin:transformNativeLibsWithMergeJniLibsForRelease
> Task :unityLibrary:MoPub.plugin:transformNativeLibsWithStripDebugSymbolForRelease
> Task :unityLibrary:MoPub.plugin:transformNativeLibsWithIntermediateJniLibsForRelease
> Task :launcher:mergeReleaseResources UP-TO-DATE
> Task :unityLibrary:mergeReleaseJniLibFolders
> Task :unityLibrary:javaPreCompileRelease UP-TO-DATE
> Task :unityLibrary:compileReleaseJavaWithJavac UP-TO-DATE
> Task :unityLibrary:bundleLibCompileRelease UP-TO-DATE
> Task :unityLibrary:bundleLibRuntimeRelease UP-TO-DATE
> Task :unityLibrary:bundleLibResRelease UP-TO-DATE
> Task :unityLibrary:transformNativeLibsWithMergeJniLibsForRelease
> Task :unityLibrary:transformNativeLibsWithStripDebugSymbolForRelease
> Task :launcher:processReleaseResources FAILED
> Task :unityLibrary:transformNativeLibsWithIntermediateJniLibsForRelease

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1.1/userguide/command_line_interface.html#sec:command_line_warnings
70 actionable tasks: 45 executed, 25 up-to-date

UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

##### Log2
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launcher:processReleaseResources'.
> Android resource linking failed
  C:\Users\kyw\Desktop\AdSdk\mopub-unity-sdk-master\unity-sample-app\Temp\gradleOut\launcher\build\intermediates\merged_manifests\release\AndroidManifest.xml:31: AAPT: error: unexpected element <queries> found in <manifest>.
      
  C:\Users\kyw\Desktop\AdSdk\mopub-unity-sdk-master\unity-sample-app\Temp\gradleOut\launcher\build\intermediates\merged_manifests\release\AndroidManifest.xml:47: AAPT: error: unexpected element <queries> found in <manifest>.
      

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by chauduyphanvu** [comment]
@vinkens, what's your Gradle version? If you have the `mainTemplate.gradle` file, try upgrading it to the next patch version suggested in [this help article](https://android-developers.googleblog.com/2020/07/preparing-your-build-for-package-visibility-in-android-11.html). 

If that doesn't resolve the issue, could you let us know the AdMob adapter package version you are using as well as share a sample project that reproduces the issue? Thanks.

Vu Chau
MoPub Team

**Comment by vinkens** [comment]
Probelem solved.
1,Toggle "Custom Main Gradle Template" in PlayerSettings->Publishing Settings,try to upgrade gradle version.
2,Cant find buildscript{dependecies{}} in file with Unity2019.4.18f1,so I copy it from Unity2019.2.11.
3,Build still failed with error"cant't use two gradle version",so I toggle"Custom Launcher Gradle Template" and add dependecies again,then build success.
4,There is another error with Firebase RemoteConfig after I solved problem above,maybe there is a conflict between them.It says Resolve Failed and build failed with error "Duplicate Files".But after toggling "Custom Gradle Properties Template",problem solved.So much toggling!
