### ISSUE TITLE
crash when closing video ad

### ISSUE THREAD

**Issue by tink3rla** [mopub/mopub-unity-sdk#172]
One line summary of the issue here

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
create new empty project in unity 2020.3.0f1
integrate unity mopub sdk package
add ad sdks as needed. In this case, admob and applovin were added
update android manifest with ad sdk keys as needed

after initialization, call MoPub.ShowRewardedVideo()

#### Expected behavior:
Ad can be closed without causing fatal error

#### Observed behavior:
When ad finishes, and close button is tapped, app crashes with fatal error 

#### Evidence:
stack trace from logcat output: 
FATAL EXCEPTION: main
Process: com.tincola.mopubtester, PID: 1843
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewParent android.widget.ImageView.getParent()' on a null object reference
	at com.mopub.mobileads.FullscreenAdController.onVideoFinish(FullscreenAdController.java:363)
	at com.mopub.mobileads.VastVideoViewController$PlayerCallback.onPlaybackCompleted(VastVideoViewController.kt:693)
	at androidx.media2.player.MediaPlayer$Mp2Callback$6.callCallback(MediaPlayer.java:3434)
	at androidx.media2.player.MediaPlayer$33.run(MediaPlayer.java:2969)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by p158276** [comment]
Hi @tink3rla ,
Thanks for reaching out. This issue is duplicate with https://github.com/mopub/mopub-android-sdk/issues/460. Please see the discussion on https://github.com/mopub/mopub-android-sdk/issues/460 for ongoing updates on this issue.

**Comment by tink3rla** [comment]
is there a timeline for releasing a fix to the unity SDK? And also, the notes on the android repo issue you linked states that an update was released with same version number as prior buggy release ("we've fixed this in 5.16.2 (the new 5.16.2—not the original 5.16.2)"). Please for the sake of your customers, increment version numbers when releasing public package; we already have many middleware versions to track, and this just makes it more complicated for your developers (and is a bad practice).

**Comment by chauduyphanvu** [comment]
Hi all, v5.16.3 has been released at https://github.com/mopub/mopub-unity-sdk/commit/e19c65c38ff5f7919dd6c602afc6956a9430dc99. It incorporates previous changes from v5.16.2. Please update to 5.16.3 and let us know if you continue seeing the issue.

Thank you!
