### ISSUE TITLE
Facebook Audience Network Configuration (Bidding Networks)

### ISSUE THREAD

**Issue by xxGAGASxx** [mopub/mopub-unity-sdk#174]
All integrated **waterfall** ads are working correctly. Only **bidding** ads not working (Facebook, Pangle).
They are already configured in MoPub dashboard.
I just want to know if I need to do something specific for bidding networks initialization in code ??

#### MoPub SDK Version:
5.16.3

#### Device model and OS Version:
iphoneX iOS 14.4.1

#### Unity Version:
2020.1.17

#### Steps to reproduce the behavior:

```
MoPub.InitializeSdk(new MoPub.SdkConfiguration
{
            AdUnitId = BannerAdUnit,
            AllowLegitimateInterest = true,
            LogLevel = MoPub.LogLevel.Debug,

            MediatedNetworks = new MoPubBase.MediatedNetwork[]
            {
                new MoPub.SupportedNetwork.Pangle
                {
                    NetworkConfiguration = new Dictionary<string,string> {
                        { "app_id", "xxxxxxxxx" },
                    },
                },

                new MoPub.SupportedNetwork.Facebook{ 
                    // What information should be passed here ???
                }
            }
});
MoPub.LoadBannerPluginsForAdUnits(new string[] { BannerAdUnit });
MoPub.LoadInterstitialPluginsForAdUnits(new string[] { InterAdUnit });
MoPub.LoadRewardedVideoPluginsForAdUnits(new string[] { RewardedAdUnit });
MoPub.ReportApplicationOpen("xxxxxxxxxx");
MoPub.EnableLocationSupport(true);

```

**Comment by chauduyphanvu** [comment]
@xxGAGASxx, one thing that might be useful to check on your end is the Advanced Bidding token in the ad request URL. You may do that by looking for the `abt` query param in your device/console logs. If the `abt` field is empty then that means the Advanced Bidding token is not available, hence no ads for Advanced Bidding. Occasionally, networks might not bid even if there is a token, so keep that in mind.

Usually, when there's no token, it means the network SDKs (Facebook and Pangle in your case) are not initializing successfully/early. And usually the cause of that is they do not have any data (IDs, etc.) to initialize with. You may rectify that by following the example [here](https://developers.mopub.com/publishers/unity/initialize/#initialize-custom-ad-networks). I see you are doing that for Pangle, and for Facebook you can pass in the placement IDs (the key name is `placement_ids`).

If you need assistance with that, you may post your console logs here and we can help analyze it.

Vu Chau
MoPub Team

**Comment by xxGAGASxx** [comment]
Thanks for respond. Is this log correct ?

`"abt":"{\"pangle\":{\"token\":\"{\\\"message\\\":\\\"2Bpa2ehJChT1ERpgPBUg1GfSTUQloQgZDbw7PIYUwR0FSAlKA3A7un3ON2QczNgZKYkOg8SgvnAD6LkabHjJeRyovcYtYfgKUzaQKOVBiL1FZyEwrvXzjxnYMNIKllyltLIQ4yt+iAiRessdh3th3m2DVqmjXni3Aaz29hetaCliIyaaDh+fDwFt+J0xlMVRRU7+ia9eZ4dKvj9MPhPem8\\\\\\\/PAGzOZizmaVhFGKL7YSMGjwoefW4Ymc\\\\\\\/8UYctrPs36G9694GkkME4e87RffrOb8eG0j\\\\\\\/93UuRIjgDmL\\\\\\\/vAGhV\\\\\\\/HugF6wZ1GK6brx0QaOr+ODVZVmkylvCR+xH4aw1Oukli9CuTzyL3ulMN1tEX\\\\\\\/xexkQEpU\\\\\\\/qgwFya8N34pNlVm5emN1A87xKgyUlX4qdbMMuqsjfqPWh\\\\\\\/qYc41hsbaaJJ2mUaAPwGVsQ8ch4XT5AoIGkb0F8lePDnLUEXMFKXmcJTuDklX7acQicowwuilw4EEcgIxLHB4ms\\\\\\\/cmqknNlYKXLmjow6IGgZnoNYOui6GN0XWqKoY5f2baSSLA==\\\",\\\"cypher\\\":2}\"},\"facebook\":{\"token\":\"eJx9VN+PmzgQ\\\/lcQT60EBPMrsNU9GGwSBMEIQ7LpcrJIlqooJOwl2Va7Vf\\\/3G5O9295D78WaGT6Pv5n5mB8qzlkuEqLeqfef3cj3iB84uktprDvBnOqhaSPddh3XDmkYRCRSNRXHBcADs23ne3B5VFKai01CqqV6Z89dTQ0TQmgpKpbCB3pflZjDjR+N2j816l2jIs8yLMc2kG8g1Kg\\\/IUtc5znNRMYWCwpsvrTDpdPUkrFKukhTMxbhjEKa7iRqDjcSEmMRZ3gBMQR+nSfVdoLiXPBUYCJyWm1YmcrHvwXfr9en3ZdDYFwO7eOpu34fzwftZPvDs2\\\/53l+\\\/hiEbwRUWRckiynmSLwQrqoTlXPAKV5LF6[MoPub-Unity] [RequestRewardedVideo] Attempting to load ad`

**Comment by chauduyphanvu** [comment]
That looks good to me. Are there additional logs that you can provide? I'm interested to see logs pertaining to the no fills.

The other thing to check is the validity of your placements on Facebook's/Pangle/s dashboard, and your MoPub ad unit ID setup. Is Advanced Bidding enabled for those ad units?

Keep in mind this tracker is for SDK/adapter issues, so if we conclude the cause of this issue to be specific to your account/waterfall, we might ask you to get assistance via the [Support Center](https://developers.mopub.com/support/).
