### ISSUE TITLE
iOS build failure when 5.15.0 mopub sdk is used and with cocoapods 1.10.0 using untiy3d

### ISSUE THREAD

**Issue by shanukp** [mopub/mopub-unity-sdk#177]
iOS build failure when 5.15.0 mopub sdk is used and with cocoapods 1.10.0 using untiy3d

#### Ad Unit IDs used in reproducing the issue: 

Build logs:
error: MoPub-Vungle-Adapters does not support provisioning profiles. MoPub-Vungle-Adapters does not support provisioning profiles, but provisioning profile name has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor. (in target 'MoPub-Vungle-Adapters' from project 'Pods')
error: PromisesObjC does not support provisioning profiles. PromisesObjC does not support provisioning profiles, but provisioning profile name has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor. (in target 'PromisesObjC' from project 'Pods')
error: FBSDKLoginKit does not support provisioning profiles. FBSDKLoginKit does not support provisioning profiles, but provisioning profile name has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor. (in target 'FBSDKLoginKit' from project 'Pods')
error: MoPub-AdMob-Adapters does not support provisioning profiles. MoPub-AdMob-Adapters does not support provisioning profiles, but provisioning profile name has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor. (in target 'MoPub-AdMob-Adapters' from project 'Pods')
error: MoPub-TapJoy-Adapters does not support provisioning profiles. MoPub-TapJoy-Adapters does not support provisioning profiles, but provisioning profile name has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor. (in target 'MoPub-TapJoy-Adapters' from project 'Pods')
error: FBSDKCoreKit does not support provisioning profiles. FBSDKCoreKit does not support provisioning profiles, but provisioning profile name has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor. (in target 'FBSDKCoreKit' from project 'Pods')
error: MoPub-Applovin-Adapters does not support provisioning profiles. MoPub-Applovin-Adapters does not support provisioning profiles, but provisioning profile name has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor. (in target 'MoPub-Applovin-Adapters' from project 'Pods')
error: FBSDKGamingServicesKit does not support provisioning profiles. FBSDKGamingServicesKit does not support provisioning profiles, but provisioning profile name has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor. (in target 'FBSDKGamingServicesKit' from project 'Pods')
error: mopub-ios-sdk does not support provisioning profiles. mopub-ios-sdk does not support provisioning profiles, but provisioning profile name been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor. (in target 'mopub-ios-sdk' from project 'Pods')
error: FBSDKShareKit does not support provisioning profiles. FBSDKShareKit does not support provisioning profiles, but provisioning profile name has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor. (in target 'FBSDKShareKit' from project 'Pods')
error: GoogleUtilities does not support provisioning profiles. GoogleUtilities does not support provisioning profiles, but provisioning profile name has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor. (in target 'GoogleUtilities' from project 'Pods')
error: MoPub-FacebookAudienceNetwork-Adapters does not support provisioning profiles. MoPub-FacebookAudienceNetwork-Adapters does not support provisioning profiles, but provisioning profile name has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor. (in target 'MoPub-FacebookAudienceNetwork-Adapters' from project 'Pods')
warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'IronSourceSDK' from project 'Pods')
error: nanopb does not support provisioning profiles. nanopb does not support provisioning profiles, but provisioning profile name has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor. (in target 'nanopb' from project 'Pods')
error: MoPub-SDK-Plugin does not support provisioning profiles. MoPub-SDK-Plugin does not support provisioning profiles, but provisioning profile name has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor. (in target 'MoPub-SDK-Plugin' from project 'Pods')
error: MoPub-UnityAds-Adapters does not support provisioning profiles. MoPub-UnityAds-Adapters does not support provisioning profiles, but provisioning profile name has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor. (in target 'MoPub-UnityAds-Adapters' from project 'Pods')
error: Pods-Unity-iPhone does not support provisioning profiles. Pods-Unity-iPhone does not support provisioning profiles, but provisioning profile name has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor. (in target 'Pods-Unity-iPhone' from project 'Pods')
warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'TapjoySDK' from project 'Pods')
warning: OpenGLES is deprecated. Consider migrating to Metal instead. (in target 'Unity-iPhone' from project 'Unity-iPhone')
error: MoPub-IronSource-Adapters does not support provisioning profiles. MoPub-IronSource-Adapters does not support provisioning profiles, but provisioning profile name has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor. (in target 'MoPub-IronSource-Adapters' from project 'Pods')

**Comment by shanukp** [comment]
This is a blocker for our release . Any help is appreciated!

**Comment by shanukp** [comment]
Any Updates here?

**Comment by shanukp** [comment]
Updated to latest sdk of mopub but still same issue

**Comment by chauduyphanvu** [comment]
@shanukp, based on the error messages, did you try the suggestion to `Set the provisioning profile value to "Automatic" in the build settings editor`? Did you also see those errors with a new Unity Editor (e.g. 2019)?

Vu Chau
MoPub Team

**Comment by shanukp** [comment]
Is there a way without setting provisioning to automatic?

**Comment by chauduyphanvu** [comment]
That is beyond the control of the MoPub Unity SDK. You are responsible for the provisioning profiles used in your build workflows.
