### ISSUE TITLE
App Tracking Transparency iOS14

### ISSUE THREAD

**Issue by agrobost** [mopub/mopub-unity-sdk#178]
Does the mopub sdk manage by itself the popup "App Tracking Transparency" on iOS 14 ? or should we use another plugin like https://assetstore.unity.com/packages/tools/integration/app-tracking-transparency-for-unity-ios-14-idfa-174256 ?

Also, can you automatically add the SkAdNetwork in the Info.plist according to the mediation networks used?

I have already done something on my side if it helps you:

```csharp
// Update the Info.plist with the SKAdNetworkItems
public static void ProcessPostBuild(BuildTarget buildTarget, string path)
{
    // Get plist
    string plistPath = path + "/Info.plist";
    PlistDocument plist = new PlistDocument();
    plist.ReadFromString(File.ReadAllText(plistPath));

    // Get root
    PlistElementDict rootDict = plist.root;

    rootDict.SetString("GADApplicationIdentifier", BonobrooSettings.AppSettings.adMobIOSAppId);

    PlistElementArray SKAdNetworkItemsArr = rootDict.CreateArray("SKAdNetworkItems");

    XmlDocument doc = new XmlDocument();
    doc.PreserveWhitespace = true;

    doc.Load(Application.dataPath + "/0-Bonobroo/Core/plist.xml");

    XmlElement root = doc.DocumentElement;
    XmlNodeList dictNodeList = root.SelectSingleNode("dict").SelectSingleNode("array").SelectNodes("dict");

    for (int i = 0; i < dictNodeList.Count; i++)
    {
        XmlNode dictNode = dictNodeList[i];
        PlistElementDict plistElementDict = SKAdNetworkItemsArr.AddDict();
        plistElementDict.SetString(dictNode.SelectSingleNode("key").InnerText, dictNode.SelectSingleNode("string").InnerText);
    }

    File.WriteAllText(plistPath, plist.WriteToString());
}

[MenuItem("MoPub/Save Info.plist data in xml file")]
static void SaveInfoPListDataInXmlFile()
{
    // https://developers.mopub.com/publishers/skadnetwork-ids-manager/
    WebRequestUtilities.Get("https://us-central1-mopub-mediation.cloudfunctions.net/getSKAdNetworkIds/[\"all\"]", (UnityWebRequest unityWebRequest) =>
    {
        if (unityWebRequest.result == UnityWebRequest.Result.Success)
        {
            string destination = Application.dataPath + "/0-Bonobroo/Core/plist.xml";
            File.WriteAllText(destination, unityWebRequest.downloadHandler.text);
        }
    });
}
```

**Comment by p158276** [comment]
Hi @agrobost ,
Thanks for reaching out. Publisher will need to implement the App Tracking Transparency dialog on their end. After MoPub 5.14 iOS SDK, we now follow the ATT framework and uses ATT to retrieve the user’s authorization status. You can refer [here](https://developers.mopub.com/publishers/ios/integrate/#step-4-optionally-configure-tracking-permission-alert-using-att-framework-for-ios-14) for more detail.

Thanks for sharing the code for automatically add the SkAdNetwork in the Info.plist according to the mediation networks used. We currently provide [MoPub’s SKAdNetwork IDs Manager tool](https://developers.mopub.com/publishers/skadnetwork-ids-manager/)  for the publisher to make quick work of gathering and processing the SKAdNetwork IDs for the info.plist.

Yoyo Lin
MoPub Team

**Comment by agrobost** [comment]
Thank you for the clarification! 
It would be nice if the MoPub unity sdk could manage the App Tracking Transparency dialog on iOS 14 and handle SKAdNetwork IDs for the info.plist by itself. This is a suggestion for improvement.

**Comment by p158276** [comment]
Hi @agrobost ,
Thanks for the suggestion here. MoPub is just one of the Ad platforms in publisher unity project. For the App Tracking Transparency dialog on Unity, the publisher should follow the iOS 14 guidelines provided by the Unity team to implement the dialog. Publisher can either use third-party unity plugin for the dialog.
