### ISSUE TITLE
Cannot build on iOS after update admob network to 19.8.0

### ISSUE THREAD

**Issue by agrobost** [mopub/mopub-unity-sdk#179]
![mopubios](https://user-images.githubusercontent.com/14184466/113630857-dc329600-9668-11eb-914d-60fa4174014f.png)
![3](https://user-images.githubusercontent.com/14184466/113631180-57944780-9669-11eb-8539-971d7083f03c.png)
![1](https://user-images.githubusercontent.com/14184466/113630856-db99ff80-9668-11eb-9d13-743da39c65c7.png)
![2](https://user-images.githubusercontent.com/14184466/113630858-dc329600-9668-11eb-8f75-7f407006bd68.png)

Unity 2020.3.0f1
MoPub 5.16.4

Looks like a dependencies problem, do you have any idea?

**Comment by chauduyphanvu** [comment]
@agrobost, which AdMob adapter package are you using in the game? Is it the [MoPub-AdMob-Adapters-prod-2.0.0-Android.19.8.0.0-iOS.8.3.0.0.unitypackage](https://github.com/mopub/mopub-unity-mediation/blob/master/unity-packages/MoPub-AdMob-Adapters-prod-2.0.0-Android.19.8.0.0-iOS.8.3.0.0.unitypackage) one? 

If so, could you show us your Podfile's content? It looks like there are conflicts with other existing dependencies.

Vu Chau
MoPub Team

**Comment by agrobost** [comment]
Here is my podfile
`source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/CocoaPods/Specs'
platform :ios, '11.0'

target 'UnityFramework' do
  pod 'FBAudienceNetwork', '~> 6.3.0'
  pod 'Firebase/Analytics', '7.5.0'
  pod 'Firebase/Core', '7.5.0'
  pod 'Firebase/Crashlytics', '7.5.0'
  pod 'Firebase/RemoteConfig', '7.5.0'
  pod 'Google-Mobile-Ads-SDK', '~> 7.68'
  pod 'MoPub-AdColony-Adapters', '4.6.0.0', :subspecs => ['Network']
  pod 'MoPub-AdMob-Adapters', '8.3.0.0', :subspecs => ['Network']
  pod 'MoPub-Applovin-Adapters', '10.1.1.0', :subspecs => ['Network']
  pod 'MoPub-FacebookAudienceNetwork-Adapters', '6.3.1.0', :subspecs => ['Network']
  pod 'mopub-ios-sdk', '5.16.2', :subspecs => ['Core']
  pod 'MoPub-UnityAds-Adapters', '3.6.0.1', :subspecs => ['Network']
end
target 'Unity-iPhone' do
end
use_frameworks!
`

**Comment by agrobost** [comment]
![image](https://user-images.githubusercontent.com/14184466/114463346-9b94c880-9be4-11eb-879e-77460dddd995.png)

**Comment by agrobost** [comment]
Ok now I can build
```xml
<dependencies>
  <androidPackages>
    <androidPackage spec="com.google.android.gms:play-services-ads:19.5.0">
      <repositories>
        <repository>https://maven.google.com/</repository>
      </repositories>
    </androidPackage>
  </androidPackages>

  <iosPods>
    // Before
    <iosPod name="Google-Mobile-Ads-SDK" version="~> 7.68">
    // After
    <iosPod name="Google-Mobile-Ads-SDK" version="8.3.0">
      <sources>
        <source>https://github.com/CocoaPods/Specs</source>
      </sources>
    </iosPod>
  </iosPods>
</dependencies>

```

**Comment by agrobost** [comment]
I have errors doing a build on xcode.. Do I have to use the sdk google mobile ads with mopub or is it not necessary?

**Comment by chauduyphanvu** [comment]
@agrobost, by having `pod 'MoPub-AdMob-Adapters'`, MoPub will automatically get `Google-Mobile-Ads-SDK` for you. You do not need to declare `pod 'Google-Mobile-Ads-SDK'` on its own. You can safely remove `Google-Mobile-Ads-SDK` from your Podfile.

Let us know if that works for you.

Vu Chau
MoPub Team

**Comment by agrobost** [comment]
Yes but the mopub adapter needs 8.3.0 whereas the audience network need 7.68..
![image](https://user-images.githubusercontent.com/14184466/114628249-dcf5a880-9cb6-11eb-8953-0307e1675e4c.png)

**Comment by chauduyphanvu** [comment]
I don't see why the Facebook Audience Network needs `Google-Mobile-Ads-SDK`? Could you elaborate?

**Comment by agrobost** [comment]
Ops, google mobile ads*

**Comment by chauduyphanvu** [comment]
I'm not sure what `GoogleMobileAds` is because all you need is `Google-Mobile-Ads-SDK`, which is transitively referenced via the `MoPub-AdMob-Adapters` pod. You shouldn't get any conflicts here. 

You might need to increase your iOS deployment target based on the error message in your initial post. If you need additional assistance, feel free to share your Unity project and we can take a look.

**Comment by agrobost** [comment]
I'm talking about this sdk
https://github.com/googleads/googleads-mobile-unity
Maybe it's not necessary to integrate it but for example AdColony told me on their dashboard that I also had to integrate their sdk.

**Comment by agrobost** [comment]
I also added the [FacebookAudienceNetwork sdk ](https://developers.facebook.com/docs/audience-network/guides/adding-sdk/unity/) in particular to call the consent functions
```csharp
        private void UpdateAdvertiserConsent(bool canCollectPersonalInfo)
        {
            if (LogEnabled) Debug.LogFormat("{0} UpdateAdvertiserConsent() - canCollectPersonalInfo={1}", LogPrefix, canCollectPersonalInfo);

            #region AudienceNetwork

#if UNITY_IOS
            AudienceNetwork.AdSettings.SetAdvertiserTrackingEnabled(canCollectPersonalInfo);
#endif
            AdSettings.SetDataProcessingOptions(canCollectPersonalInfo ? new string[] { } : new string[] { "LDU" }, 1, 1000);

            #endregion


            #region AdColony

            AdColony.AppOptions appOptions = new AdColony.AppOptions();

            // The value passed via setPrivacyFrameworkRequired() will determine the GDPR requirement of
            // the user. If it's set to true, the user is subject to the GDPR laws.
            if (MoPub.IsGdprApplicable.HasValue)
                appOptions.SetPrivacyFrameworkRequired(AdColony.AppOptions.GDPR, MoPub.IsGdprApplicable.Value);

            // Your user's consent String. In this case, the user has given consent to store
            // and process personal information. This value may be either O, 1, or an IAB consent string.
            if (canCollectPersonalInfo)
                appOptions.SetPrivacyConsentString(AdColony.AppOptions.GDPR, "1");

            appOptions.SetPrivacyFrameworkRequired(AdColony.AppOptions.COPPA, false);

#if UNITY_IOS
            AdColony.Ads.Configure(BonobrooSettings.AppSettings.adColonyIOSAppId, appOptions, BonobrooSettings.AppSettings.adColonyIOSZoneIds);
#else
            AdColony.Ads.Configure(BonobrooSettings.AppSettings.adColonyAndroidAppId, appOptions, BonobrooSettings.AppSettings.adColonyAndroidZoneIds);
#endif

            #endregion
        }
```

**Comment by chauduyphanvu** [comment]
> I'm talking about this sdk
> https://github.com/googleads/googleads-mobile-unity
> Maybe it's not necessary to integrate it but for example AdColony told me on their dashboard that I also had to integrate their sdk.

For MoPub, you do not need the Google Ads Unity SDK. You only need the iOS pod that I mentioned above (`Google-Mobile-Ads-SDK`). That might explain why there is a conflict in resolving the pod version. 

If you need it for AdColony, you should reach out to them and ask about the specific reasons. If you integrate AdColony with MoPub too then you should be fine to remove `GoogleMobileAds`.

We aren't able to comment on Facebook's consent solution best practices. You should reach out to Facebook for a confirmation.

**Comment by agrobost** [comment]
Thank you!
