### ISSUE TITLE
Failed to verify bitcode when archive export ad hoc.

### ISSUE THREAD

**Issue by TeddyBeam** [mopub/mopub-unity-sdk#18]
Hi everyone, whenever i try to export ad-hoc, this error occurs: 

_Failed to verify bitcode in MoPubSDKFramework.framework/MoPubSDKFramework:
error: Bundle only contains bitcode-marker /var/folders/0x/91w5869n7vscbcd33q5kb3cm0000gp/T/IDEDistributionOptionThinning.ZjG/Payload/emdemomopub.app/Frameworks/MoPubSDKFramework.framework/MoPubSDKFramework (armv7)_

Reproduce steps:
- Export project from Unity to Xcode.
- Click Product/Archive.
- Select archived project and click export.
- Choose Ad Hoc option and click Next.
- The error above shows up after a few seconds, while the App Thining load circle is spinning.

I have tried lots of solutions:
- Define BITCODE_GENERATION_MODE => doesn't work.
- Add -fembed-bitcode flag => doesn't work.
- Set **Enable Bitcode** in **Project** to **No** (by default it's set to **Yes**, only the one in **Target** is set to **No**) => doesn't work.
- Set **Enable Bitcode** in **Target** to **Yes** => Can't even archive anymore, error : _framework was built without full bitcode_.
- Add a Run Script to strip unwanted architectures? (follow [this ](http://ikennd.ac/blog/2015/02/stripping-unwanted-architectures-from-dynamic-libraries-in-xcode/)guide) => doesn't work.

I'm using Xcode 9.3, lastest SDK version.
Tried with sample project, same result.

Update: same error with Enterprise & Development export options.

**Comment by ankitjain8790** [comment]
I am having the same problem. Please help. Our project release is on line

**Comment by sdolim** [comment]
We have a fix coming soon.  In the meantime, a workaround is to rebuild the MoPubSDKFramework.framework from source using scripts/build.sh in a clone of this repo, but first go into the mopub-ios-sdk-unity Xcode project and set Enable Bitcode to No in there.  Replace the framework in your Unity project's Assets/Plugins/iOS with the build result (which is found in mopub-ios-sdk-unity/bin).

**Comment by ankitjain8790** [comment]
Tried your solution but still it do not works. Tell me if I install the sdk through cocoapods removing the framework, will it work?

**Comment by aornelas** [comment]
Sorry you're having trouble! I've built and tested a version of the framework that should solve your issue. Can you please download it from [here](https://github.com/mopub/mopub-ios-sdk/blob/framework-for-adapters-fix/MoPubSDKFramework/MoPubSDKFramework.framework.zip) and use it to replace the one in your project?

This will be fixed in our upcoming release (today), but wanted to make sure you were unblocked ASAP.

Thanks!

**Comment by sdolim** [comment]
Although our upcoming release today will fix this problem with an updated MoPub.unitypackage containing the fixed MoPubSDKFramework.framework, I'll document here the change to our build script that did the trick.  

In **scripts/mopub-ios-sdk-unity-build.sh**, the command to build the framework has to look like this:

    xcrun xcodebuild -project mopub-ios-sdk-unity/$XCODE_PROJECT_NAME \
                     -scheme "MoPub for Unity" \
                     -configuration "Release" \
                     OTHER_CFLAGS="-fembed-bitcode -w" \
                     BITCODE_GENERATION_MODE=bitcode \
                     clean \
                     build

The key new lines are the **-configuration** and **BITCODE_GENERATION_MODE** lines.  Running the script now rebuilds the framework with the right bitcode mode, and in release mode too.  It then copies it into our unity-sample-app Unity project.

Also, we currently have to patch in some extra header files that the MoPubSDK Xcode project doesn't put into the framework, if you are using any of the network mediation adapters from the _mopub-unity-mediation_ repo.  (If you aren't, do worry about this next part).  So after you run this step, check with git for any **.h**'s inside **Assets/Plugins/iOS/MoPubSDKFramework.framework/Headers** that it is saying got deleted.  Use git to restore them. 

The rebuilt framework needs to go into your Unity project.  Either copy it directly or use **scripts/unity-export-package.sh** to rebuild _MoPub.unitypackage_ and then import that into your project.

Once the release today is out, the new unitypackage will have undergone this process already, so you don't need to do any of the above steps after getting it.  But hopefully this makes the fix clear if in case you need to do this yourself before that, or if a similar issue crops up in the future.

**Comment by aornelas** [comment]
This has been fixed in the [5.1.0 release](https://github.com/mopub/mopub-unity-sdk/releases/tag/v5.1.0).

Thanks again for reporting!
