### ISSUE TITLE
Different behaviors for OnConsentDialogDismissedEvent and OnConsentStatusChangedEvent between Android and iOS

### ISSUE THREAD

**Issue by agrobost** [mopub/mopub-unity-sdk#181]
To understand the problems, here are the steps of the consent of mopub

#### Mopub step 1
> The consent is displayed 
![Screenshot_20210415-150201](https://user-images.githubusercontent.com/14184466/114879026-1df9d400-9e01-11eb-81b6-88d7f15367b4.jpg)  

#### Mopub step 2
> The user clicks on "Yes, I agree"  

#### Mopub step 3
 > The user waits 10/15sec and clicks on the cross at the top right of the screen

#### Mopub step 4
> The second part is displayed > "Great! We hope you enjoy..." 
![Screenshot_20210415-150211](https://user-images.githubusercontent.com/14184466/114879027-1e926a80-9e01-11eb-808a-0e58c9372189.jpg)  

#### Mopub step 5
> The user clicks on the cross 

### Event OnConsentStatusChangedEvent
On Android it is triggered on the step 5 whereas on iOS it is at the step 2.
It would be nice to trigger the iOS callback as on android.

### Event OnConsentDialogDismissedEvent
On Android it is triggered on the step 3 whereas on iOS it's never triggered.
Could you connect this event on iOS?

### Other
On iOS there is a cross at the top right of the screen whereas there is no cross on android
![2](https://user-images.githubusercontent.com/14184466/114882760-931ad880-9e04-11eb-8815-7e0b10de9361.png)

MoPub 5.16.4
Unity 2020.3.0f1

**Comment by chauduyphanvu** [comment]
@agrobost, thanks! I was able to reproduce the different behaviors you reported, and have let the rest of the team know. Stay tuned for an update.

Vu Chau
MoPub Team
