### ISSUE TITLE
Mediation Issues

### ISSUE THREAD

**Issue by rahat10120141** [mopub/mopub-unity-sdk#184]
I want some help in integrating mediation.. I have some issues:

1. Do I need to provide the ad codes of another mediation network to the ad codes section.. like the following code:
```
    private readonly string[] _bannerAdUnits = { "Mopubcode","Unity Banner Code","Admob Banner Code" };
    private readonly string[] _interstitialAdUnits = {"Mopubcode","Unity Banner Code","Admob Banner Code"  };
    private readonly string[] _rewardedAdUnits = { "Mopubcode","Unity Banner Code","Admob Banner Code" };
```
2. I have done everything according and mopub ads are showing perfectly. Now what I have to do for meditation? I have installed the unity and admob skd downloaded from new mopub ui.

**Comment by chauduyphanvu** [comment]
@rahat10120141, see answers below:

1. You do not need to do anything extra code-wise for mediation. That means all of the code you use to request and show MoPub Marketplace ads will go on to call specific mediation code via respective adapters on your behalf. But, you will need to create new ad unit IDs and use them in our code. See point 2 for more explanations.

2. For each network you plan to mediate, you will open accounts on its dashboard, register your app, create some ad units / placement IDs, and port that data back to MoPub on our dashboard (check the **Networks** tab --> **App and ad unit setup**). Then, launch the [SDK Manager](https://developers.mopub.com/publishers/unity/integrate/#option-1-use-the-sdk-manager-recommended) in Unity to get the mediation adapters. Specific ad networks might have specific requirements, so you are encouraged to check out [documentation](https://developers.mopub.com/publishers/mediation/mopub-network-mediation/).

Let us know if there are any questions.

Vu Chau
MoPub Team
