### ISSUE TITLE
MoPub.h file not found in MoPubManager.h Mopub5.16.4

### ISSUE THREAD

**Issue by kurisunoob** [mopub/mopub-unity-sdk#186]
One line summary of the issue here

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.16.4
#### Unity Version:
2019.3.0f6
#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.
Update Mopub from 5.11.1
Use windows OS Build for iOS.

#### Expected behavior:
Builds should succeed.

#### Observed behavior:
he build fails with:
MoPubManager.h:15:9: 'MoPub.h' file not found

#### Evidence:
It's work success with 5.11.1 
My podfile:
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
project 'Unity-iPhone.xcodeproj'

target 'UnityFramework' do
  pod 'Crashlytics', '3.14.0'
  pod 'Fabric', '1.10.2'
  pod 'FBSDKCoreKit', '~> 9.0'
  pod 'FBSDKGamingServicesKit', '~> 9.0'
  pod 'FBSDKLoginKit', '~> 9.0'
  pod 'FBSDKShareKit', '~> 9.0'
  pod 'Firebase/Analytics', '7.5.0'
  pod 'Firebase/Core', '7.5.0'
  pod 'Firebase/Crashlytics', '7.5.0'
  pod 'MoPub-AdMob-Adapters'
  pod 'MoPub-Applovin-Adapters'
  pod 'MoPub-FacebookAudienceNetwork-Adapters'
  pod 'mopub-ios-sdk', '5.16.2', :subspecs => ['Core']
  pod 'MoPub-IronSource-Adapters'
  pod 'MoPub-SDK-Plugin', :path => '/xx/xx/xxx/MopubSDK/Plugins/iOS'
  pod 'MoPub-UnityAds-Adapters'
  pod 'MoPub-Vungle-Adapters'
end
target 'Unity-iPhone' do
end
use_frameworks!
use_frameworks!

what shou i do

**Comment by kurisunoob** [comment]
i tryed
mopub-unity-sdk-5.15.0
mopub-unity-sdk-5.16.0
mopub-unity-sdk-5.16.1
mopub-unity-sdk-5.16.2
mopub-unity-sdk-5.16.3
mopub-unity-sdk-5.16.4

**Comment by kurisunoob** [comment]
pod 'mopub-ios-sdk', '5.16.2', :subspecs => ['Core'] 
to
 pod 'mopub-ios-sdk', '5.16.4', :subspecs => ['Core']
still failed

**Comment by dravyan** [comment]
@kurisunoob, thanks for the report. Could you confirm the External dependency manager version that you are on?

Thanks,
MoPub Team
