### ISSUE TITLE
New InMobi supported network is not available via manual initialization

### ISSUE THREAD

**Issue by Remstam** [mopub/mopub-unity-sdk#188]
One line summary of the issue here
New InMobi supported network is not available via manual initialization

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.16.4

#### Device model and OS Version:
No Android or iOS device needed to reproduce

#### Unity Version:
2018.4.34f1

#### Ad Unit IDs used in reproducing the issue:
No Ad Unit needed to reproduce the issue

#### Steps to reproduce the behavior:
As it is stated in the integration docs for InMobi (https://developers.mopub.com/publishers/mediation/networks/inmobi/#--unity) we should be able to use _MoPub.SupportedNetwork.InMobi_ to configurate InMobi, but that supported network is not defined yet in _Mopub.cs_ source file as of Unity MoPub SDK 5.16.4.

#### Expected behavior:
_MoPub.SupportedNetwork.InMobi_ is available and can be used exactly as it is written in intergration manual.

#### Observed behavior:
_MoPub.SupportedNetwork.InMobi_ is not available, we still have to integrate it via _MoPub.MediatedNetwork_ as it stated in the example (https://developers.mopub.com/publishers/unity/initialize/#initialize-custom-ad-networks)

#### Evidence:
Just have a look into _Mopub.cs_ source file or try to use, for example, IntelliSense hints for _MoPub.SupportedNetwork._ - no InMobi class to use there.

**Comment by p158276** [comment]
Hi @Remstam ,
Thanks for reaching out.
InMobi will be defined as SupportedNetwork in the following SDK version.
If you are using SDK below and include 5.16.4, you should follow the instruction [here](https://developers.mopub.com/publishers/unity/initialize/#initialize-custom-ad-networks) to initialize Inmobi as a custom network. 
Let us know if you have any other questions.

Yoyo Lin
MoPub Team

**Comment by Remstam** [comment]
@p158276 
Thank you for clarification.
