### ISSUE TITLE
Can't build Unity Android il2cpp build.

### ISSUE THREAD

**Issue by Troshchuk** [mopub/mopub-unity-sdk#19]
It is not possible to build Unity Android il2cpp with Mopub unity sdk 5.1.0.
Here is pastebin link with Editor Logs: https://pastebin.com/TFSqdcyg

**Comment by aornelas** [comment]
Hi!

Thank you for your report. This issue has been addressed in [5.2.0](https://github.com/mopub/mopub-unity-sdk/commit/8bdcb2ac180c385c51d98a78f56487df60d251e1), released just now! Please update to this version and give it another try. Here's the relevant fix: https://github.com/mopub/mopub-unity-sdk/blob/master/unity-sample-app/Assets/MoPub/Internal/MoPubiOS.cs#L475.

**Comment by Troshchuk** [comment]
Thanks, it works.
