### ISSUE TITLE
Banner cut at the bottom left on iOS

### ISSUE THREAD

**Issue by agrobost** [mopub/mopub-unity-sdk#190]
I am using the MoPub SDK 5.17.0
My device is: iPhone 6 Plus (iOS 12.5.1)

The banners are a little cut at the bottom left on iOS:
![IMG_8829](https://user-images.githubusercontent.com/14184466/118334942-db660d00-b50e-11eb-8d47-8405aa020196.PNG)
![IMG_8827](https://user-images.githubusercontent.com/14184466/118334945-dc973a00-b50e-11eb-930b-d27fad2c13d4.PNG)
![IMG_8826](https://user-images.githubusercontent.com/14184466/118334947-dd2fd080-b50e-11eb-8e18-f5d0d51d6daf.PNG)

On andorid the banners do not take all the width is this normal?

I request the banner like this:
```csharp
MoPub.RequestBanner(bannerAdUnit, MoPub.AdPosition.BottomCenter, MoPub.MaxAdSize.ScreenWidthHeight50, GetKeyWords(), GetUserDataKeyWords());
```

**Comment by p158276** [comment]
Hi @agrobost ,
Thanks for reaching out. May I know what is ad unit and network you are using? Besides, are you able to reproduce the same problem by using [our sample app](https://github.com/mopub/mopub-unity-sdk/)?

Yoyo Lin
MoPub Team
