### ISSUE TITLE
[iOS] Mopub 5.17.0 Crash on launch

### ISSUE THREAD

**Issue by pixeption** [mopub/mopub-unity-sdk#191]
One line summary of the issue here

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [ ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
- Upgrade Mopub from 5.16.4 to 5.17 via Mopub window in Unity
- Build to iOS
- Try to build and run on device with xCode 12.5

#### Expected behavior:
- App should not crash on launch

#### Observed behavior:
- App crashes on launch with logs

#### Evidence:
`Light[14908:3954701] Error loading /var/containers/Bundle/Application/4E058DC4-5A08-413E-972E-6C7B47340080/Light.app/Frameworks/UnityFramework.framework/UnityFramework:  dlopen(/var/containers/Bundle/Application/4E058DC4-5A08-413E-972E-6C7B47340080/Light.app/Frameworks/UnityFramework.framework/UnityFramework, 265): Library not loaded: @rpath/OMSDK_Mopub.framework/OMSDK_Mopub
  Referenced from: /private/var/containers/Bundle/Application/4E058DC4-5A08-413E-972E-6C7B47340080/Light.app/Frameworks/UnityFramework.framework/UnityFramework
  Reason: image not found
2021-05-15 09:22:20.522831+0700 Light[14908:3954701] Error loading /var/containers/Bundle/Application/4E058DC4-5A08-413E-972E-6C7B47340080/Light.app/Frameworks/UnityFramework.framework/UnityFramework:  dlopen(/var/containers/Bundle/Application/4E058DC4-5A08-413E-972E-6C7B47340080/Light.app/Frameworks/UnityFramework.framework/UnityFramework, 265): Library not loaded: @rpath/OMSDK_Mopub.framework/OMSDK_Mopub
  Referenced from: /private/var/containers/Bundle/Application/4E058DC4-5A08-413E-972E-6C7B47340080/Light.app/Frameworks/UnityFramework.framework/UnityFramework
  Reason: image not found
`

#### Note:
- I have to revert Mopub back to 5.16.4 and it works fine for now.

**Comment by chauduyphanvu** [comment]
@pixeption, are you able to install 5.17.0 fresh (without using the upgrade option)? 

I installed 5.17.0 fresh just now and did not run into any crashes. It's possible the upgrade did not handle getting the OMSDK_Mopub.framework on your behalf. Another thing you could try is to run `pod update` or `pod install` on the project directory once your Unity project has been exported. That should get the OMSDK_Mopub.framework for you.

Vu Chau
MoPub Team

**Comment by pixeption** [comment]
@chauduyphanvu 
Fresh install did not help, but I noticed the External Dependency version is 1.2.164 (I was using 1.2.163). 

Upgraded to 1.2.164 I didn't see crash in test project anymore but my game project still crashes. Then I found the differences in pod file and making changes:

This one crash
```source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'UnityFramework' do
  pod 'Firebase/Analytics', '7.5.0'
  pod 'Firebase/Core', '7.5.0'
  pod 'Firebase/Crashlytics', '7.5.0'
  pod 'Firebase/RemoteConfig', '7.5.0'
  pod 'MoPub-AdColony-Adapters', '4.6.1.0', :subspecs => ['Network']
  pod 'MoPub-AdMob-Adapters', '8.5.0.0', :subspecs => ['Network']
  pod 'MoPub-Applovin-Adapters', '10.2.1.1', :subspecs => ['Network']
  pod 'mopub-ios-sdk', '5.17.0', :subspecs => ['Core']
  pod 'MoPub-UnityAds-Adapters', '3.7.1.2', :subspecs => ['Network']
end
use_frameworks! :linkage => :static
```

This one crash too
```source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'UnityFramework' do
  pod 'Firebase/Analytics', '7.5.0'
  pod 'Firebase/Core', '7.5.0'
  pod 'Firebase/Crashlytics', '7.5.0'
  pod 'Firebase/RemoteConfig', '7.5.0'
  pod 'MoPub-AdColony-Adapters', '4.6.1.0', :subspecs => ['Network']
  pod 'MoPub-AdMob-Adapters', '8.5.0.0', :subspecs => ['Network']
  pod 'MoPub-Applovin-Adapters', '10.2.1.1', :subspecs => ['Network']
  pod 'mopub-ios-sdk', '5.17.0', :subspecs => ['Core']
  pod 'MoPub-UnityAds-Adapters', '3.7.1.2', :subspecs => ['Network']
end
use_frameworks!
```

Some how this one work?
```source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'UnityFramework' do
  pod 'Firebase/Analytics', '7.5.0'
  pod 'Firebase/Core', '7.5.0'
  pod 'Firebase/Crashlytics', '7.5.0'
  pod 'Firebase/RemoteConfig', '7.5.0'
  pod 'MoPub-AdColony-Adapters', '4.6.1.0', :subspecs => ['Network']
  pod 'MoPub-AdMob-Adapters', '8.5.0.0', :subspecs => ['Network']
  pod 'MoPub-Applovin-Adapters', '10.2.1.1', :subspecs => ['Network']
  pod 'mopub-ios-sdk', '5.17.0', :subspecs => ['Core']
  pod 'MoPub-UnityAds-Adapters', '3.7.1.2', :subspecs => ['Network']
end
target 'Unity-iPhone' do
end
use_frameworks!
```

**Comment by pixeption** [comment]
Changing the Pod file works for me.

I started to use `use_frameworks! :linkage => :static` because there was a bug that Admob did not serve ad in the previous version and I haven't changed it since.

I can update the External Dependency setting so it'll generate the correct Pod file so it's not a big issue for me.
