### ISSUE TITLE
[iOS] Mopub 5.17.0 Compile Error

### ISSUE THREAD

**Issue by SankarGanesh82** [mopub/mopub-unity-sdk#192]
One line summary of the issue here

- [ ] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
* Upgrade Mopub from 5.16.4 to 5.17.0 via Mopub window in Unity (or) Import Mopub Unity 5.17.0 package into empty project
* Build to iOS
* Mac OS version 10.15.7
* Open .xcworkspace file and compile (XCode version 12.4)

#### Expected behavior:
Build should compile without any exceptions

#### Observed behavior:
Got 3 exceptions(Swift compiler error)
<img width="1199" alt="Screenshot 2021-05-17 at 3 32 47 PM" src="https://user-images.githubusercontent.com/55496751/118471261-307b6c00-b725-11eb-9372-6a01df7e9ece.png">
. "Cannot find type 'SKAdImpression' in scope"

#### Evidence:
Screenshot

**Comment by Remstam** [comment]
Since Unity SDK 5.17 contains iOS SDK 5.17
https://github.com/mopub/mopub-ios-sdk/releases/tag/5.17.0

I guess you should try build project with xCode 12.5+.

**Comment by chauduyphanvu** [comment]
@SankarGanesh82, yes, like @Remstam said, please upgrade your Xcode to 12.5 for v5.17.0 of the MoPub SDK.

Vu Chau
MoPub Team

**Comment by SankarGanesh82** [comment]
Sure, Thanks for your response @Remstam and @chauduyphanvu
