### ISSUE TITLE
[iOS] Vungle deleted pod

### ISSUE THREAD

**Issue by sp-duarte-roso** [mopub/mopub-unity-sdk#193]
One line summary of the issue here

- [✅] I am submitting a bug report for existing functionality
- [✅] I visited https://developers.mopub.com/ and found no answer
- [✅] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [✅] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.17.0

#### Unity Version:
2019.4.25f1

#### Steps to reproduce the behavior:
Build iOS using Vungle Adapter 1.3.9

#### Observed behavior:
Because Vungle deleted their pod of version 6.10.0, MoPub's adapter is now referencing a non existing pod

#### Evidence:
https://github.com/CocoaPods/Specs/commit/15510d04c1db110001af151d7f6ea531c065947a#diff-e5c7f57a14d8ff940f814f81aec624676fb741f4037d0519b1c72530a263cda5

**Comment by dravyan** [comment]
@sp-duarte-roso, Vungle has retracted SDK version v6.10.0 from production. Hence new adapter [v6.9.2.1](https://github.com/mopub/mopub-ios-mediation/blob/master/Vungle/CHANGELOG.md#changelog) compatible with MoPub 5.17.0 has been released. You can update to this version.

Thanks,
MoPub Team
