### ISSUE TITLE
Rewarded ad server-side callback url not called on Android with Mopub 5.17.0 

### ISSUE THREAD

**Issue by erennsahinn** [mopub/mopub-unity-sdk#194]
Hi, 

I was using Mopub 5.15.0 and everything was ok. I tried to updating to Mopub 5.17.0. iOS works properly, watching an ad and server url is called. However on Android server is not called. Rewarded ad loads and plays, client delegate method (OnRewardedVideoReceivedRewardEvent) is called, but server side url is not called. 

Is there anything new that I should insert into Gradle template. I thought I might be missing something, like importing new dependency or updating old one, but couldn't find anything.

**Comment by erennsahinn** [comment]
Is there any feedback about this issue? I need to update to 5.17.0 for Fyber integration.

**Comment by erennsahinn** [comment]
Hi, this is test ad unit id we use.
2292ef103f994edab73fd0386baef969

**Comment by erennsahinn** [comment]
By the way, I downloaded Unity Mopub Sample and watched an ad with our test ad unit id and server url called.  So it seems like it is related to our game configuration, but everything on client side seems ok. Video is loaded and shown properly. Delegate methods of Mopub called as expected. I don't know what can I do on client side for server to be called.

**Comment by chauduyphanvu** [comment]
Thanks for the details. 

Yes, we also haven't been able to reproduce this issue on our end. How is this particular game different from the other ones where the server-side rewarding does occur? Are you using mediation for that ad unit ID? If the demand sources rotate, maybe an ad network fails to notify MoPub of rewarded ad completion, so server-side rewarding isn't triggered.

**Comment by erennsahinn** [comment]
Thanks for response.

Yes, we were using 7 mediations, and just added Fyber. Problem maybe related to that. How can we resolve it if it is related to this ?

**Comment by chauduyphanvu** [comment]
@erennsahinn, one thing to check would be whether this is happening to all creatives in your 5.17.0 integrations or only a few (and which demand sources they are coming from). Once that's confirmed, I recommend testing with the same creative on both 5.15.0 and 5.17.0 to narrow down on the culprit.

If you can reproduce the issue locally, utilize the console logs from the MoPub SDK that should print out the last invoked adapter instance, which tells you which demand source a creative comes from.

**Comment by erennsahinn** [comment]
@chauduyphanvu It happens on all ad networks.

**Comment by chauduyphanvu** [comment]
@erennsahinn - the team will reach out offline via the regular escalation process to work with you on this issue. Thanks!

**Comment by chauduyphanvu** [comment]
@erennsahinn - the issue has been resolved offline. For everyone else, the culprit was a non-SDK call to `Networking.getRequestQueue()`. If you are calling that directly from your app (which was a workaround for a separate bug that no longer exists), you should remove it.
