### ISSUE TITLE
Native ads request issue

### ISSUE THREAD

**Issue by SamihElsakhawi** [mopub/mopub-unity-sdk#195]
Hi,

I’m trying to implement Mopub SDK (5.17.0) to serve native ads, in a Unity game (2020.2.0f1) on Android.

I use a test ad unit for this purpose (11a17b188668469fb0412708c3d16813).

After I initialize the sdk:

```
var anyAdUnitId = _nativeAdUnits[0];

MoPub.InitializeSdk(new MoPub.SdkConfiguration
{
AdUnitId = anyAdUnitId,
});

MoPub.LoadNativePluginsForAdUnits(_nativeAdUnits);
```

I requested a native ads:

`MoPub.RequestNativeAd(_nativeAdUnits[0]);`

But in my log, i get this error:

> Invalid call to MoPub API; Native AdUnit with ID 11a17b188668469fb0412708c3d16813 has not been requested yet

The sdk is correctly initialized, because when i request interstitial ads, or the consent dialog, everything loaded fine.

Are native ads supported with the mopub sdk for Unity?
How could i fix this issue?

Thank you.

Regards, Samih.

**Comment by p158276** [comment]
Hi @SamihElsakhawi ,
Thanks for reaching out. We don't support the native format in Unity Plugin at the moment. 

Yoyo Lin
MoPub Team

**Comment by SamihElsakhawi** [comment]
Hi @p158276 ,

Thank you.

Regards, Samih
