### ISSUE TITLE
Inmobi can not show impression

### ISSUE THREAD

**Issue by chenqiu1988** [mopub/mopub-unity-sdk#196]
One line summary of the issue here

- [1] I am submitting a bug report for existing functionality
- [2] I visited https://developers.mopub.com/ and found no answer
- [3] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [4] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
I add about 10 partner， all others are OK, but Inmobi rewarded ad  is not. Inmobe  bidding can response, and win, but show impression number is always 0. 

#### Expected behavior:
in common, the impression / wins == 40%

#### Observed behavior:
inmobi bidding response bid， wins more than 200， but the impression number always 0. the other partners is all OK。

# ### Evidence:
we contact with the inmobi engineers, And they say may mopub sdk show the ad error, or the callback is bad. Thank you

**Comment by p158276** [comment]
Hi @chenqiu1988 ,
Thanks for reaching out. Looks all good on your ad unit setting. Can you check the InMobi SDK log and see if there's anything suspicious that related to the show error? You can also provide the error log that can reproduce the error. 
Besides, please also make sure all the [required dependencies](https://developers.mopub.com/publishers/mediation/networks/inmobi/#integration-prerequisites) have been added to your project. 

Yoyo Lin
MoPub Team

**Comment by chenqiu1988** [comment]
> Hi @chenqiu1988 ,
> Thanks for reaching out. Looks all good on your ad unit setting. Can you check the InMobi SDK log and see if there's anything suspicious that related to the show error? You can also provide the error log that can reproduce the error.
> Besides, please also make sure all the [required dependencies](https://developers.mopub.com/publishers/mediation/networks/inmobi/#integration-prerequisites) have been added to your project.
> 
> Yoyo Lin
> MoPub Team

Thank you very much.It's my mistake, missing some dependencies, and  fix the bug later. Please close the issue.
