### ISSUE TITLE
Facebook audience network crashes app, even in example project #198

### ISSUE THREAD

**Issue by zzzxxccvvzqm** [mopub/mopub-unity-sdk#199]
@chauduyphanvu Sorry to mention that I've tried to set Link frameworks statically before I post. The issue is when I enable this and run on device I get errors below:

> 2021-06-30 08:59:48.320792+0800 MoPubSample[7739:1105295] Error loading /var/containers/Bundle/Application/B1EB620E-18B4-4BEF-9FDF-20A2368161AA/MoPubSample.app/Frameworks/UnityFramework.framework/UnityFramework:  dlopen(/var/containers/Bundle/Application/B1EB620E-18B4-4BEF-9FDF-20A2368161AA/MoPubSample.app/Frameworks/UnityFramework.framework/UnityFramework, 265): Library not loaded: @rpath/OMSDK_Mopub.framework/OMSDK_Mopub
  Referenced from: /private/var/containers/Bundle/Application/B1EB620E-18B4-4BEF-9FDF-20A2368161AA/MoPubSample.app/Frameworks/UnityFramework.framework/UnityFramework
  Reason: image not found
2021-06-30 08:59:48.349921+0800 MoPubSample[7739:1105295] Error loading /var/containers/Bundle/Application/B1EB620E-18B4-4BEF-9FDF-20A2368161AA/MoPubSample.app/Frameworks/UnityFramework.framework/UnityFramework:  dlopen(/var/containers/Bundle/Application/B1EB620E-18B4-4BEF-9FDF-20A2368161AA/MoPubSample.app/Frameworks/UnityFramework.framework/UnityFramework, 265): Library not loaded: @rpath/OMSDK_Mopub.framework/OMSDK_Mopub
  Referenced from: /private/var/containers/Bundle/Application/B1EB620E-18B4-4BEF-9FDF-20A2368161AA/MoPubSample.app/Frameworks/UnityFramework.framework/UnityFramework
  Reason: image not found

This was the reason I don't use static links. This guy has the same error as mine:
[https://github.com/mopub/mopub-unity-sdk/issues/191](https://github.com/mopub/mopub-unity-sdk/issues/191)
He says he has to revert to Mopub 5.16, so I guess this might be an issue relative to 5.17 and the latest Unity

and here is my pod file:
> source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
> target 'UnityFramework' do
  pod 'MoPub-FacebookAudienceNetwork-Adapters', '6.5.0.0', :subspecs => ['Network']
  pod 'mopub-ios-sdk', '5.17.0', :subspecs => ['Core']
end
target 'Unity-iPhone' do
end
use_frameworks! :linkage => :static

 Any ideas?

_Originally posted by @gamefish in https://github.com/mopub/mopub-unity-sdk/issues/197#issuecomment-871021506_

**Comment by chauduyphanvu** [comment]
Please keep the conversation in https://github.com/mopub/mopub-unity-sdk/issues/197. Closing this one.
