### ISSUE TITLE
GDPR consent not working on Android

### ISSUE THREAD

**Issue by vizgl** [mopub/mopub-unity-sdk#20]
I create new empty project in Unity 2018.2.0f2 and add latest sdk 5.2.0. 
On the device I installed Hola vpn and choose different EU countries, but every time I launch app always get same. Is gdpr applicable is **false**. I tried different devices and vpn services.
On my iphone all works fine.

**Comment by aornelas** [comment]
GDPR applicability may not be refreshed frequently enough to detect your vpn changes... please try reinstalling the sample app or clearing its data.

Alternatively, you can use the *Force GDPR* button in the sample app to test the consent flow.

**Comment by aornelas** [comment]
Hi @vizgl, were you able to solve this issue?

**Comment by aornelas** [comment]
Closing this out for now; feel free to reopen if needed.
