### ISSUE TITLE
The server may drop some request today, (2021.07.02)

### ISSUE THREAD

**Issue by chenqiu1988** [mopub/mopub-unity-sdk#200]
I just find the fillrate drop from 54% to 45% today, and is still dowing now. Analyze data, and the request is not normal. 
Just for ad unit:a2b6c2b1b79a47f6a9634997a91bef1d, All setting is not change
yesterday (2021.07.01) : the all request is 881k, the Marketplace bidding request is 871k , about 99%
today,Just now(2021.07.02):the all request is 714k, the Marketplace bidding request is just 426k , about 60%

because of the request lost, the adunit fillrate is drop from 54% (a long time) to 45%(today). 
Please check if all services are normal, if all server are working.

One line summary of the issue here

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
You can the adunit request data : a2b6c2b1b79a47f6a9634997a91bef1d

#### Expected behavior:
Marketplace bidding request  approximately equal to overview request.

#### Observed behavior:
Marketplace bidding request  / overview request Just 60%.

#### Evidence:
Please the the unit:a2b6c2b1b79a47f6a9634997a91bef1d (before 2021.07.01 V.S. 2021.07.02)
The server may drop some request today, (2021.07.02)

**Comment by dravyan** [comment]
@chenqiu1988, thanks for the report. Looking at the ad requests, it started to happen with the app version 5.5+. In order to investigate this further, could you open a support ticket at https://developers.mopub.com/support/?

Thanks,
MoPub team

**Comment by chenqiu1988** [comment]
> @chenqiu1988, thanks for the report. Looking at the ad requests, it started to happen with the app version 5.5+. In order to investigate this further, could you open a support ticket at https://developers.mopub.com/support/?
> 
> Thanks,
> MoPub team

I had open a support ticket, Case Number: 00229775. Thank you.

**Comment by dravyan** [comment]
@chenqiu1988, thank you. Our support team will reach out to you.
