### ISSUE TITLE
Crash when calling MoPub.RequestInterstitial

### ISSUE THREAD

**Issue by 7Hazard** [mopub/mopub-unity-sdk#202]
One line summary of the issue here

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version: 
5.17.0 (May 12, 2021)

#### Device model and OS Version: 
Android

#### Unity Version: 
2020.3.8f1

#### Ad Unit IDs used in reproducing the issue:
Whatever was used in demo scene

#### Steps to reproduce the behavior:
Run the demo scene on Android and press on Request interstitial

#### Expected behavior:
Not crash

#### Observed behavior:
The app crashes

#### Evidence:
![Console](https://cdn.discordapp.com/attachments/780809613624475659/863865471739625492/unknown.png)

**Comment by 7Hazard** [comment]
I found this after some digging https://github.com/mopub/mopub-unity-sdk/issues/136
I will give the suggestions in here a try and comment back if anything fixes it.

**Comment by 7Hazard** [comment]
So I managed to figure out what I was missing, and in all honesty this was hard for me to find for the first time. Despite that it was mentioned [here](https://github.com/mopub/mopub-unity-sdk#additional-requirements-for-unity-2020), I didn't know where to place these settings. It would've been nice if this was done automatically on the integrators behalf.

This is what I had to do:
Inside *Project Settings -> Player -> Android -> Publishing Settings* I had to tick the `Custom Gradle Properties Template` and then open the file that is mentioned below the setting and make sure the following properties were set:
```
android.useAndroidX=true
android.enableDexingArtifactTransform=false
```

![](https://i.imgur.com/kFAT1C3.png)

So I'm going to keep this open in the case where this issue could stand for a potential enhancement but effectively I have managed to fix my issue and the crashing by doing the steps above.

**Comment by chauduyphanvu** [comment]
Thanks for the information. We have that instruction documented here: https://developers.mopub.com/publishers/unity/integrate/#additional-requirements-for-unity-2020. We will add the path to the custom Gradle template for other readers.

I will close this issue now given we have a resolution.

Thanks,
Vu Chau
MoPub Team
