### ISSUE TITLE
App crashes when starting without internet connection

### ISSUE THREAD

**Issue by BacheyG** [mopub/mopub-unity-sdk#206]
App crashes (with mopub SDK integrated) when running without internet connection.

#### MoPub SDK Version:
5.17.0

#### Device model and OS Version:
HONOR 20, Android 10

#### Unity Version:
2020.1.14f1

#### Steps to reproduce the behavior:
Start the app without internet connection
https://play.google.com/store/apps/details?id=com.BacheyGraphics.JelloBallo

#### Evidence:
`` 2021/07/18 16:47:16.641 12090 12090 Error AndroidRuntime FATAL EXCEPTION: main
2021/07/18 16:47:16.641 12090 12090 Error AndroidRuntime Process: com.BacheyGraphics.JelloBallo, PID: 12090
2021/07/18 16:47:16.641 12090 12090 Error AndroidRuntime java.lang.AbstractMethodError: abstract method "void com.mopub.network.MoPubResponse$Listener.onErrorResponse(com.mopub.network.MoPubNetworkError)"
2021/07/18 16:47:16.641 12090 12090 Error AndroidRuntime 	at com.mopub.network.TrackingRequest$1.onErrorResponse(TrackingRequest.java:138)
2021/07/18 16:47:16.641 12090 12090 Error AndroidRuntime 	at com.mopub.network.MoPubRequest$volleyErrorListener$1.onErrorResponse(MoPubRequest.kt:62)
2021/07/18 16:47:16.641 12090 12090 Error AndroidRuntime 	at com.mopub.volley.Request.deliverError(Request.java:623)
2021/07/18 16:47:16.641 12090 12090 Error AndroidRuntime 	at com.mopub.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:104)
2021/07/18 16:47:16.641 12090 12090 Error AndroidRuntime 	at android.os.Handler.handleCallback(Handler.java:900)
2021/07/18 16:47:16.641 12090 12090 Error AndroidRuntime 	at android.os.Handler.dispatchMessage(Handler.java:103)
2021/07/18 16:47:16.641 12090 12090 Error AndroidRuntime 	at android.os.Looper.loop(Looper.java:219)
2021/07/18 16:47:16.641 12090 12090 Error AndroidRuntime 	at android.app.ActivityThread.main(ActivityThread.java:8393)
2021/07/18 16:47:16.641 12090 12090 Error AndroidRuntime 	at java.lang.reflect.Method.invoke(Native Method)
2021/07/18 16:47:16.641 12090 12090 Error AndroidRuntime 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
2021/07/18 16:47:16.641 12090 12090 Error AndroidRuntime 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
``

**Comment by dravyan** [comment]
@BacheyG , thank you for the report. A similar issue was reported in https://github.com/mopub/mopub-android-sdk/issues/475#issuecomment-855531321. Can you confirm the [additional requirements](https://developers.mopub.com/publishers/unity/integrate/#additional-requirements-for-unity-2020) for the app are enabled?

Thanks,
MoPub Team

**Comment by BacheyG** [comment]
Hmm, I might be missing something, I'm getting this gradle error:
`Starting a Gradle Daemon, 1 incompatible and 2 stopped Daemons could not be reused, use --status for details

> Configure project :launcher
WARNING: The option 'android.enableR8' is deprecated and should not be used anymore.
It will be removed in a future version of the Android Gradle plugin, and will no longer allow you to disable R8.
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2021.1.15f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\build-tools\30.0.2\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2021.1.15f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platform-tools\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2021.1.15f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platforms\android-29\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2021.1.15f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\tools\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2021.1.15f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\build-tools\30.0.2\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2021.1.15f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platform-tools\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2021.1.15f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platforms\android-29\package.xml. Probably the SDK is read-only
Exception while marshalling C:\Program Files\Unity\Hub\Editor\2021.1.15f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\tools\package.xml. Probably the SDK is read-only

> Task :launcher:preBuild UP-TO-DATE
> Task :launcher:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:preBuild UP-TO-DATE
> Task :unityLibrary:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:MoPub.plugin:preBuild UP-TO-DATE
> Task :unityLibrary:MoPub.plugin:preReleaseBuild UP-TO-DATE
> Task :unityLibrary:packageReleaseRenderscript NO-SOURCE
> Task :unityLibrary:MoPub.plugin:compileReleaseAidl NO-SOURCE
> Task :unityLibrary:compileReleaseAidl NO-SOURCE
> Task :launcher:generateReleaseBuildConfig
> Task :launcher:compileReleaseAidl NO-SOURCE
> Task :launcher:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:MoPub.plugin:packageReleaseRenderscript NO-SOURCE
> Task :unityLibrary:generateReleaseBuildConfig
> Task :unityLibrary:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:MoPub.plugin:compileReleaseRenderscript NO-SOURCE
> Task :unityLibrary:MoPub.plugin:generateReleaseResValues
> Task :unityLibrary:MoPub.plugin:generateReleaseResources
> Task :unityLibrary:generateReleaseResValues
> Task :unityLibrary:generateReleaseResources
> Task :unityLibrary:MoPub.plugin:packageReleaseResources
> Task :unityLibrary:packageReleaseResources
> Task :unityLibrary:MoPub.plugin:parseReleaseLocalResources
> Task :unityLibrary:parseReleaseLocalResources
> Task :unityLibrary:MoPub.plugin:generateReleaseBuildConfig
> Task :unityLibrary:processReleaseManifest
> Task :unityLibrary:MoPub.plugin:processReleaseManifest
> Task :launcher:mainApkListPersistenceRelease
> Task :launcher:generateReleaseResValues
> Task :launcher:generateReleaseResources
> Task :unityLibrary:extractDeepLinksRelease
> Task :unityLibrary:compileReleaseLibraryResources
> Task :unityLibrary:MoPub.plugin:javaPreCompileRelease
> Task :unityLibrary:MoPub.plugin:extractDeepLinksRelease
> Task :unityLibrary:MoPub.plugin:compileReleaseLibraryResources
> Task :unityLibrary:prepareLintJarForPublish
> Task :unityLibrary:MoPub.plugin:generateReleaseRFile
> Task :unityLibrary:MoPub.plugin:prepareLintJarForPublish
> Task :unityLibrary:mergeReleaseShaders
> Task :unityLibrary:compileReleaseShaders
> Task :unityLibrary:generateReleaseAssets
> Task :unityLibrary:packageReleaseAssets
> Task :unityLibrary:generateReleaseRFile
> Task :unityLibrary:processReleaseJavaRes NO-SOURCE
> Task :unityLibrary:bundleLibResRelease
> Task :unityLibrary:MoPub.plugin:compileReleaseJavaWithJavac
> Task :unityLibrary:MoPub.plugin:bundleLibRuntimeRelease
> Task :unityLibrary:MoPub.plugin:mergeReleaseShaders
> Task :unityLibrary:MoPub.plugin:compileReleaseShaders
> Task :unityLibrary:MoPub.plugin:generateReleaseAssets
> Task :unityLibrary:MoPub.plugin:packageReleaseAssets
> Task :unityLibrary:MoPub.plugin:processReleaseJavaRes NO-SOURCE
> Task :unityLibrary:mergeReleaseJniLibFolders
> Task :unityLibrary:MoPub.plugin:bundleLibCompileRelease
> Task :unityLibrary:MoPub.plugin:mergeReleaseJniLibFolders
> Task :unityLibrary:MoPub.plugin:bundleLibResRelease
> Task :unityLibrary:MoPub.plugin:mergeReleaseNativeLibs
> Task :unityLibrary:MoPub.plugin:stripReleaseDebugSymbols
> Task :unityLibrary:MoPub.plugin:copyReleaseJniLibsProjectOnly
> Task :unityLibrary:javaPreCompileRelease

> Task :unityLibrary:compileReleaseJavaWithJavac

> Task :unityLibrary:mergeReleaseNativeLibs
> Task :unityLibrary:bundleLibRuntimeRelease
> Task :launcher:createReleaseCompatibleScreenManifests
> Task :launcher:extractDeepLinksRelease
> Task :launcher:processReleaseManifest
> Task :launcher:prepareLintJar
> Task :launcher:checkReleaseDuplicateClasses FAILED
> Task :unityLibrary:bundleLibCompileRelease
> Task :launcher:mergeReleaseResources
49 actionable tasks: 49 executed

UnityEditor.BuildPlayerWindow:BuildPlayerAndRun ()

Note: C:\Users\EDU_NILM_5344\Documents\JelloBello\DrawBallGame\Temp\gradleOut\unityLibrary\src\main\java\com\unity3d\player\UnityPlayerActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':launcher:checkReleaseDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class androidx.appcompat.app.ActionBar found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.ActionBar$DisplayOptions found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.ActionBar$LayoutParams found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.ActionBar$NavigationMode found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.ActionBar$OnMenuVisibilityListener found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.ActionBar$OnNavigationListener found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.ActionBar$Tab found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.ActionBar$TabListener found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.ActionBarDrawerToggle found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.ActionBarDrawerToggle$1 found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.ActionBarDrawerToggle$Delegate found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.ActionBarDrawerToggle$DelegateProvider found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.ActionBarDrawerToggle$ToolbarCompatDelegate found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.ActionBarDrawerToggleHoneycomb found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.ActionBarDrawerToggleHoneycomb$SetIndicatorInfo found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.AlertController found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.AlertController$1 found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.AlertController$2 found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.AlertController$3 found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.AlertController$4 found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.AlertController$5 found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.AlertController$AlertParams found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.AlertController$AlertParams$1 found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.AlertController$AlertParams$2 found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.AlertController$AlertParams$3 found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.AlertController$AlertParams$4 found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.AlertController$AlertParams$OnPrepareListViewListener found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.AlertController$ButtonHandler found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.AlertController$CheckedItemAdapter found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.AlertController$RecycleListView found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.AlertDialog found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.AlertDialog$Builder found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.AppCompatActivity found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.AppCompatCallback found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.AppCompatDelegate found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.AppCompatDelegate$NightMode found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.AppCompatDialog found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.AppCompatDialogFragment found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.AppCompatViewInflater found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.NavItemSelectedListener found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.ResourcesFlusher found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.ToolbarActionBar found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.ToolbarActionBar$1 found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.ToolbarActionBar$2 found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.ToolbarActionBar$ActionMenuPresenterCallback found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.ToolbarActionBar$MenuBuilderCallback found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.ToolbarActionBar$ToolbarCallbackWrapper found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.TwilightCalculator found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.TwilightManager found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.TwilightManager$TwilightState found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.WindowDecorActionBar found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.WindowDecorActionBar$1 found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.WindowDecorActionBar$2 found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.WindowDecorActionBar$3 found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.WindowDecorActionBar$ActionModeImpl found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.app.WindowDecorActionBar$TabImpl found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.content.res.AppCompatResources found in modules jetified-androidx.appcompat.appcompat-resources-1.1.0-runtime.jar (:androidx.appcompat.appcompat-resources-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.content.res.AppCompatResources$ColorStateListCacheEntry found in modules jetified-androidx.appcompat.appcompat-resources-1.1.0-runtime.jar (:androidx.appcompat.appcompat-resources-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.graphics.drawable.DrawableWrapper found in modules jetified-androidx.appcompat.appcompat-resources-1.1.0-runtime.jar (:androidx.appcompat.appcompat-resources-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.graphics.drawable.DrawerArrowDrawable found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.graphics.drawable.DrawerArrowDrawable$ArrowDirection found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.text.AllCapsTransformationMethod found in modules jetified-androidx.appcompat.appcompat-1.1.0-runtime.jar (:androidx.appcompat.appcompat-1.1.0:) and jetified-appcompat-v7-25.2.0-runtime.jar (:appcompat-v7-25.2.0:)
  Duplicate class androidx.appcompat.view.ActionBarPolicy found in modules jetified-androidx.appcompat.appcompa<message truncated>
`

My gradleTemplate.properties:
`unityStreamingAssets=.unity3d**STREAMING_ASSETS**
org.gradle.jvmargs=-Xmx**JVM_HEAP_SIZE**M
org.gradle.parallel=true
# Android Resolver Properties Start
android.useAndroidX=true
android.enableJetifier=true
# Android Resolver Properties End
**ADDITIONAL_PROPERTIES**
android.enableDexingArtifactTransform=false

android.enableR8=**MINIFY_WITH_R_EIGHT**`

The last line was auto added by Unity.

My settings:
![image](https://user-images.githubusercontent.com/10908673/126865636-6da36b12-1826-463c-b393-ac9c445c906c.png)

**Comment by chengbowen1992** [comment]
> @BacheyG , thank you for the report. A similar issue was reported in [mopub/mopub-android-sdk#475 (comment)](https://github.com/mopub/mopub-android-sdk/issues/475#issuecomment-855531321). Can you confirm the [additional requirements](https://developers.mopub.com/publishers/unity/integrate/#additional-requirements-for-unity-2020) for the app are enabled?
> 
> Thanks,
> MoPub Team

hi, we meet the same crash event.
I am sure that we enables the configs:

android.useAndroidX=true
android.enableDexingArtifactTransform=false

when we do not use the config above, It will crash every time when we open the game offline.
when we use the config above, It will not crash every time ,but it will still crash randomly sometime.

the error log is :

1627269081.467  7230  AndroidRuntime  Error FATAL EXCEPTION: main
Process: com.dxx.punball.googleplaynew, PID: 7230
java.lang.AbstractMethodError: abstract method "void com.mopub.network.MoPubResponse$Listener.onErrorResponse(com.mopub.network.MoPubNetworkError)"
  at com.mopub.network.TrackingRequest$1.onErrorResponse(TrackingRequest.java:138)
  at com.mopub.network.MoPubRequest$volleyErrorListener$1.onErrorResponse(MoPubRequest.kt:62)
  at com.mopub.volley.Request.deliverError(Request.java:623)
  at com.mopub.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:104)
  at android.os.Handler.handleCallback(Handler.java:873)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loop(Looper.java:224)
  at android.app.ActivityThread.main(ActivityThread.java:7042)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:536)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:868)
