### ISSUE TITLE
Cannot build on iOS after the update 5.18.0

### ISSUE THREAD

**Issue by agrobost** [mopub/mopub-unity-sdk#210]
![image](https://user-images.githubusercontent.com/14184466/128983604-30308f22-4879-480b-95a8-1e18d665e422.png)
Hi,
I have a dependency problem with vungle, do you know how to fix it? Do I have to wait for a network update?

**Comment by chauduyphanvu** [comment]
@agrobost, we made new adapter releases last week to remove the hard dependency on 5.17.0. Please upgrade _all_ of your mediation adapters to the latest releases. That should resolve this issue.

Vu Chau
MoPub Team

**Comment by agrobost** [comment]
I had already updated all of my mediation adapters.
![image](https://user-images.githubusercontent.com/14184466/129103721-c47a3515-a9ac-48cd-b3ef-56b2f2be4483.png)

**Comment by chauduyphanvu** [comment]
Thank you for the details! There were propagation delays with the Vungle release. It should be fixed now. 

Let us know if you continue seeing the issue.
