### ISSUE TITLE
After importing plugin in Unity : Getting an error from Sample folder's scripts

### ISSUE THREAD

**Issue by mayura33** [mopub/mopub-unity-sdk#211]
**ERROR is : Assets\MoPub\Sample\Content\Views\MoPubAdUnitView_g.cs(4800,28): error CS1061: 'Label' does not contain a definition for 'MaxVisibleLines' and no accessible extension method 'MaxVisibleLines' accepting a first argument of type 'Label' could be found (are you missing a using directive or an assembly reference?)**

#### Expected behavior:
Should not get any error after importing plugin

![image](https://user-images.githubusercontent.com/33602207/129164705-49b78e0b-1d1b-4e19-915e-6241463bb9d3.png)

**Comment by p158276** [comment]
Hi @mayura33 ,
Thanks for reaching out. I am able to reproduce the issue from the environment as well. I will circle back to our internal team and provide the update here. As the Sample folder is used for the sample app, you can just remove it from your project. So you won't get any error then.

Thanks, 
Yoyo Lin
MoPub Team

**Comment by aornelas** [comment]
just gonna leave this here... 😉 
https://github.com/mopub/mopub-unity-sdk/tree/master/unity-sample-app/Assets/MoPub/Sample#sample-app-troubleshooting

**Comment by wacamoe** [comment]
Thank you @aornelas !
