### ISSUE TITLE
IOS Crash Upon Banner Ad Request

### ISSUE THREAD

**Issue by cagatayisikcoda** [mopub/mopub-unity-sdk#214]
On iOS only, the game crashes as soon as a banner ad is attempted to load. From my understanding from the logs, mopub responses as an ad already loaded to the banner request but there is no ads available.

- [X] I am submitting a bug report for existing functionality
- [X] I visited https://developers.mopub.com/ and found no answer
- [X] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [X] I checked to make sure that this issue has not already been filed

#### Ad Unit IDs used in reproducing the issue: 45171270e9da44179d26bccc1f41ee56
[BannerIssue.txt](https://github.com/mopub/mopub-unity-sdk/files/7171618/BannerIssue.txt)

#### Evidence:
Device log attached.

**Comment by khchen428** [comment]
Hi @cagatayisikcoda - thanks for reporting this issue! Would you happen to have a different log that shows a stacktrace of where in the MoPub SDK the crash is occuring?  We can't reproduce the crash so far with the same setup.

**Comment by cagatayisikcoda** [comment]
Hi @khchen428 , I just had a chance to look at the crash log from firebase and it seems like this is not on you but rather about unity/ios problem. We will try to upgrade unity version to see if we will get any changes. Here is the crash log
[CrashLog.txt](https://github.com/mopub/mopub-unity-sdk/files/7185996/CrashLog.txt)
.
