### ISSUE TITLE
MoPub.h file not found in MoPubManager.h Mopub 5.18.0

### ISSUE THREAD

**Issue by dodamgames** [mopub/mopub-unity-sdk#219]
One line summary of the issue here

- [ ] I am submitting a bug report for existing functionality
- [ ] I visited https://developers.mopub.com/ and found no answer
- [ ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ ] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.

Update Mopub from 5.18.0
Use Unity Cloud Build

#### Expected behavior:
As concisely as possible, describe the expected behavior.

#### Observed behavior:
As concisely as possible, describe the observed behavior.

#### Evidence:
Device log files, Network log file, etc.
/BUILD_PATH/#########/Libraries/MoPub/Plugins/iOS/MoPubManager.h:15:9: 'MoPub.h' file not found

External dependency manager version is 1.2.167

what shou i do

**Comment by chauduyphanvu** [comment]
@dodamgames, could you elaborate a bit on how you are integrating the MoPub SDK? This issue has been fixed before (https://github.com/mopub/mopub-unity-sdk/issues/107) and if you could share additional details we can take a deeper look.

Vu Chau
MoPub Team

**Comment by KimKangilDodam** [comment]
![화면 캡처 2021-11-22 160750](https://user-images.githubusercontent.com/89884970/142818597-d8794ec0-600a-4337-a290-7bf7c0ae89e0.png)

![화면 캡처 2021-11-22 161027](https://user-images.githubusercontent.com/89884970/142818684-a72642a6-9468-44e1-a686-b747cc59e43b.png)

![화면 캡처 2021-11-22 161147](https://user-images.githubusercontent.com/89884970/142818818-2557c5c9-ee7e-4b26-805a-bf5b651c2008.png)

![화면 캡처 2021-11-22 161250](https://user-images.githubusercontent.com/89884970/142818928-48d8fd64-e345-4793-8fa4-a1f69d791d6c.png)

MoPubUnity.unitypackage 

I installed only the unity package.

**Comment by KimKangilDodam** [comment]
![image](https://user-images.githubusercontent.com/89884970/142820215-3c727f0d-bbf7-4f17-8a2b-93bd0c2e82da.png)

**Comment by chauduyphanvu** [comment]
Thank you for the details.

Just to be sure the SDK is effectively integrated, could you run `pod update` from the exported Xcode project directory? Make sure that the `mopub-ios-sdk` pod is successfully installed.
