### ISSUE TITLE
Can not create archive in xcode 12.5.1

### ISSUE THREAD

**Issue by oleksandr-diukov** [mopub/mopub-unity-sdk#221]
Can not create archive in xcode 12.5.1

#### Ad Unit IDs used in reproducing the issue:
Rewarded Video

#### Steps to reproduce the behavior:
Create iOS build and try to create ipa-archive in xcode

#### Expected behavior:
Archiving will not throw exceptions

#### Observed behavior:
Archiving throws exceptions

#### Evidence:
ld: warning: Could not find or use auto-linked library 'swift_Concurrency'
ld: warning: Could not find or use auto-linked library 'swiftFileProvider'
ld: warning: Could not find or use auto-linked library 'swiftDataDetection'
ld: warning: Could not find or use auto-linked framework 'DataDetection'
Undefined symbols for architecture arm64:
  "__swift_FORCE_LOAD_$_swiftDataDetection", referenced from:
      __swift_FORCE_LOAD_$_swiftDataDetection_$_FBAudienceNetwork in FBAudienceNetwork(FBAudienceNetwork.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftDataDetection_$_FBAudienceNetwork)
  "__swift_FORCE_LOAD_$_swiftFileProvider", referenced from:
      __swift_FORCE_LOAD_$_swiftFileProvider_$_FBAudienceNetwork in FBAudienceNetwork(FBAudienceNetwork.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftFileProvider_$_FBAudienceNetwork)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by oleksandr-diukov** [comment]
If i delete FBAudienceNetwork everything is archiving correctly

**Comment by chauduyphanvu** [comment]
@oleksandr-diukov, how are you integrating the Facebook Audience Network SDK exactly? Are you using CocoaPods or otherwise?

Vu Chau
MoPub Team

**Comment by oleksandr-diukov** [comment]
I am using Facebook Audience Network SDK via your MoPub SDK Manager in Unity and then using cocoapods in xcode project,
this is how my pod file looks like with FB Audience (not working):

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

target 'UnityFramework' do
  pod 'AppsFlyerFramework', '6.2.5'
  pod 'FBSDKCoreKit', '~> 11.0'
  pod 'FBSDKCoreKit_Basics', '~> 11.0'
  pod 'FBSDKGamingServicesKit', '~> 11.0'
  pod 'FBSDKLoginKit', '~> 11.0'
  pod 'FBSDKShareKit', '~> 11.0'
  pod 'Firebase/Analytics', '7.5.0'
  pod 'Firebase/Core', '7.5.0'
  pod 'Firebase/Crashlytics', '7.5.0'
  pod 'Firebase/RemoteConfig', '7.5.0'
  pod 'MoPub-AdMob-Adapters', '8.11.0.1', :subspecs => ['Network']
  pod 'MoPub-FacebookAudienceNetwork-Adapters', '6.7.0.1', :subspecs => ['Network']
  pod 'mopub-ios-sdk', '5.18.0', :subspecs => ['Core']
  pod 'MoPub-UnityAds-Adapters', '3.7.5.3', :subspecs => ['Network']
end
target 'Unity-iPhone' do
end
use_frameworks! :linkage => :static
```

and this is without (this one work)

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

target 'UnityFramework' do
  pod 'AppsFlyerFramework', '6.2.5'
  pod 'FBSDKCoreKit', '~> 11.0'
  pod 'FBSDKCoreKit_Basics', '~> 11.0'
  pod 'FBSDKGamingServicesKit', '~> 11.0'
  pod 'FBSDKLoginKit', '~> 11.0'
  pod 'FBSDKShareKit', '~> 11.0'
  pod 'Firebase/Analytics', '7.5.0'
  pod 'Firebase/Core', '7.5.0'
  pod 'Firebase/Crashlytics', '7.5.0'
  pod 'Firebase/RemoteConfig', '7.5.0'
  pod 'MoPub-AdMob-Adapters', '8.11.0.1', :subspecs => ['Network']
  pod 'mopub-ios-sdk', '5.18.0', :subspecs => ['Core']
  pod 'MoPub-UnityAds-Adapters', '3.7.5.3', :subspecs => ['Network']
end
target 'Unity-iPhone' do
end
use_frameworks! :linkage => :static
```

**Comment by oleksandr-diukov** [comment]
Also, build is crashed after starting the app with log
```
Error loading /var/containers/Bundle/Application/14CC88CC-3A22-49E0-BEE9-FBEB242438B4/Appname.app/Frameworks/UnityFramework.framework/UnityFramework:  dlopen(/var/containers/Bundle/Application/14CC88CC-3A22-49E0-BEE9-FBEB242438B4/Appname.app/Frameworks/UnityFramework.framework/UnityFramework, 0x0109): Library not loaded: @rpath/OMSDK_Mopub.framework/OMSDK_Mopub
  Referenced from: /private/var/containers/Bundle/Application/14CC88CC-3A22-49E0-BEE9-FBEB242438B4/Appname.app/Frameworks/UnityFramework.framework/UnityFramework
  Reason: tried: '/usr/lib/swift/OMSDK_Mopub.framework/OMSDK_Mopub' (no such file), '/private/var/containers/Bundle/Application/14CC88CC-3A22-49E0-BEE9-FBEB242438B4/Appname.app/Frameworks/OMSDK_Mopub.framework/OMSDK_Mopub' (no such file), '/usr/lib/swift/OMSDK_Mopub.framework/OMSDK_Mopub' (no such file), '/private/var/containers/Bundle/Application/14CC88CC-3A22-49E0-BEE9-FBEB242438B4/Appname.app/Frameworks/OMSDK_Mopub.framework/OMSDK_Mopub' (no such file), '/private/var/containers/Bundle/Application<…>
```

**Comment by chauduyphanvu** [comment]
@oleksandr-diukov, ah I see. Thanks for the confirmation.

In that case, your issue is related to https://github.com/mopub/mopub-unity-sdk/issues/197. Please see the workaround in https://github.com/mopub/mopub-unity-sdk/issues/197#issuecomment-891176829.

**Comment by oleksandr-diukov** [comment]
yes, I've tried this workaround and it doesn't work for me(
