### ISSUE TITLE
App Crash on Android

### ISSUE THREAD

**Issue by oleksandr-diukov** [mopub/mopub-unity-sdk#222]
When you watch rewarded video and close when it is done app is crashing

#### MoPub SDK Version: 
5.18.0

#### Device model and OS Version: 
Android 10, Samsung Galaxy A70

#### Unity Version: 
2021.2.1f1

#### Steps to reproduce the behavior:
Create android build, run and play rewarded video, also I had to remake Mobub.plugins to Mopub.androidlib, so it can be attached to gradle build correctly, because I have issues without this step. 

#### Expected behavior:
App not crashing

#### Observed behavior:
App crashing

#### Evidence:
[logs.txt](https://github.com/mopub/mopub-unity-sdk/files/7588493/logs.txt)

**Comment by sezbladex** [comment]
Me to crash when request ad, Please check graddle properties add this code before build android.enableDexingArtifactTransform=false

**Comment by oleksandr-diukov** [comment]
@sezbladex thanks, but I have this in my gradle.properties
<img width="491" alt="Screenshot 2021-11-24 at 17 35 44" src="https://user-images.githubusercontent.com/90186148/143268372-7284a092-ed9a-4b3d-be0b-7451f11d1e0c.png">

**Comment by sezbladex** [comment]
I added other adapters now I am getting  crash when  use app there are problems sdk
