### ISSUE TITLE
Rewarded callbacks sometimes not fired

### ISSUE THREAD

**Issue by vizgl** [mopub/mopub-unity-sdk#23]
I am using latest Mopub(5.4.0)(also same issue in the 5.3.0) for mediation: unityads, admob, applovin and vungle. All works fine instead of Rewarded videos. Sometimes events such as: OnRewardedVideoShownEvent, OnRewardedVideoClosedEvent, OnRewardedVideoReceivedRewardEvent is not called. Event OnMoPubLoadedEvent is fired.

Ads initialized after Mopub initialization:
`MoPub.LoadRewardedVideoPluginsForAdUnits(new[] {adUnit});`
`MoPubManager.OnRewardedVideoLoadedEvent += OnMoPubLoadedEvent;`
`MoPubManager.OnRewardedVideoFailedEvent += OnMoPubFailedEvent;`
`MoPubManager.OnRewardedVideoClosedEvent += OnMoPubClosedEvent;`
`MoPubManager.OnRewardedVideoReceivedRewardEvent += OnMoPubReceivedRewardEvent;`
`MoPub.RequestRewardedVideo(_adUnit);`

`void OnMoPubLoadedEvent()`
`{`
`     MoPub.ShowRewardedVideo(_adUnit);`
`}`

**Comment by vizgl** [comment]
Found that events not fired only on unityads

**Comment by fuatcoskun** [comment]
So, what is the solution? Did you just ignore unityads? Btw, we are facing the same problem on mopub-android-sdk with unityads. Can you please share if you have any solution for that?

**Comment by chauduyphanvu1** [comment]
@fuatcoskun - it looks like @vizgl closed this thread, but the issue you're talking about sounds similar to https://github.com/mopub/mopub-unity-mediation/issues/22. Could you take a look at that one and confirm? If so, feel free to move the conversation to that issue report so we can better track it. Thanks!

**Comment by BinuVargheseC** [comment]
we are facing the same problem on mopub-android-sdk 5.8.0 with unityads.

**Comment by chauduyphanvu** [comment]
@BinuVargheseC, this issue is closed, and we've had multiple Unity Ads adapters and SDK releases over the months that might have addressed the original bug and/or altered some other behaviors.

Please open a new issue report and fill out the provided template so we can better assist you. Thank you!
