### ISSUE TITLE
ArgumentException: An element with the same key already exists in the dictionary when initializing SDK

### ISSUE THREAD

**Issue by reavenheart** [mopub/mopub-unity-sdk#27]
If we call plugin initialization after the SDK is initialized, it uses the same UnitIDs and calls an ArgumentException upon the initialization. It can be fixed if some logic of the initialization inside Mopub SDK is modified. An example is below

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed.  There's a Thread there https://twittercommunity.com/t/argumentexception-an-element-with-the-same-key-already-exists-in-the-dictionary/69859, but there's no answer there
- [x] I checked to make sure that this issue has not already been filed

#### Ad Unit IDs used in reproducing the issue:
Test IDs were taken from here:
https://developers.mopub.com/docs/android/testing/
https://developers.mopub.com/docs/ios/testing/

#### Steps to reproduce the behavior:
According to the docs, I initialize the SDK with a test interstitial ID
https://developers.mopub.com/docs/unity/initialization/
In our project we need to initialize it not in a Start function, but later. But in awake we connect to events to receive callbacks.
When the SDK is initialized, it triggers OnSDKinitializedHandler(string adUnitId), where we initialize plugins for a currect environment (test or production) (methods are taken from here https://developers.mopub.com/docs/unity/getting-started/)
MoPub.LoadBannerPluginsForAdUnits(mopubEnvData.GetAllBannerAdUnits());
MoPub.LoadInterstitialPluginsForAdUnits(mopubEnvData.GetAllInterstitialAdUnits());

#### Expected behavior:
This issue can be fixed if you process the existing keys correctly.
public static void LoadBannerPluginsForAdUnits(string[] bannerAdUnitIds)
    {
        foreach (var bannerAdUnitId in bannerAdUnitIds)
        {
            if (!BannerPluginsDict.ContainsKey(bannerAdUnitId))
                BannerPluginsDict.Add(bannerAdUnitId, new MPBanner(bannerAdUnitId));
            else
            {
                BannerPluginsDict[bannerAdUnitId] = new MPBanner(bannerAdUnitId);
            }
        }

        Debug.Log(
            bannerAdUnitIds.Length + " banner AdUnits loaded for plugins:\n" + string.Join(", ", bannerAdUnitIds));
    }
We check if the key already exists or not. And this issue is eliminated

#### Observed behavior:
See the log segment below. It happens because this ID already exists in the part of code of MoPubAndroid and MoPubiOS
public static void LoadBannerPluginsForAdUnits(string[] bannerAdUnitIds)
    {
        foreach (var bannerAdUnitId in bannerAdUnitIds)
            BannerPluginsDict.Add(bannerAdUnitId, new MPBanner(bannerAdUnitId));

        Debug.Log(
            bannerAdUnitIds.Length + " banner AdUnits loaded for plugins:\n" + string.Join(", ", bannerAdUnitIds));
    }

Same thing for the Interstitials, rewarded ads, etc.

#### Evidence:
MopubManager.cs is our script.

01-08 23:48:15.961 21978 22033 E Unity   : ArgumentException: An element with the same key already exists in the dictionary.
01-08 23:48:15.961 21978 22033 E Unity   :   at System.Collections.Generic.Dictionary`2[System.String,MoPubAndroidBanner].Add (System.String key, .MoPubAndroidBanner value) [0x00171] in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:432
01-08 23:48:15.961 21978 22033 E Unity   :   at MoPubAndroid.LoadBannerPluginsForAdUnits (System.String[] bannerAdUnitIds) [0x0002c] in D:\Projects\Assets\MoPub\Scripts\Internal\MoPubAndroid.cs:67
01-08 23:48:15.961 21978 22033 E Unity   :   at MopubManager.OnSDKinitializedHandler (System.String adUnitId) [0x00022] in D:\Projects\Assets\Scripts\MopubManager.cs:171
01-08 23:48:15.961 21978 22033 E Unity   :   at MoPubManager.EmitSdkInitializedEvent (System.String argsJson) [0x0001c] in D:\Projects\Assets\MoPub\Scripts\MoPubManager.cs:145

**Comment by sdolim** [comment]
As far as the C# dictionary goes, the syntax 

    BannerPluginsDict[bannerAdUnitId] = new MPBanner(bannerAdUnitId);

is sufficient by itself to add a new key and to update an existing key (see https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.item?view=netframework-4.7.2#System_Collections_Generic_Dictionary_2_Item__0_). The bug was using the .Add() syntax instead, which only works to add new keys.

**Comment by reavenheart** [comment]
Cool. Maybe this fix could get into the next SDK version?

**Comment by chauduyphanvu1** [comment]
@reavenheart - could you attach or send a link to a mini sample project (or our sample project if you modified it) with steps to trigger the same behavior? There currently is no ETA for a fix but I'll check with the rest of the team on what we can do.

**Comment by chauduyphanvu1** [comment]
@reavenheart - we've fixed this and are releasing it in the next SDK.

**Comment by chauduyphanvu1** [comment]
This issue is now fixed in https://github.com/mopub/mopub-unity-sdk/commit/ac30c78946c10cc467e7d6d8c400fcba9b64e3be. Please try with that release and let us know if the issue persists!

**Comment by aliakseipashkel** [comment]
Thanks! The issue status is Open, however, the fix is in v5.5.0 now. Are we testing the fix at our own risk? ;)

**Comment by chauduyphanvu1** [comment]
It's fixed. We close issue reports once a week so this one will go away pretty soon!

**Comment by rsatrasala** [comment]
Fixed in our latest SDK release 5.5.0

**Comment by aliakseipashkel** [comment]
Perfect, thanks. Already opened a ticket to update the SDK in our application.
