### ISSUE TITLE
MoPubPostBuildiOS.cs error

### ISSUE THREAD

**Issue by Jovar** [mopub/mopub-unity-sdk#28]
MoPubPostBuildiOS.cs doesn't properly find MoPubSDKFramework.framework when using Unity 2018.3, because it seems that 2018.3 now puts the library directly  in /Frameworks directory. This causes some problems when opening the project in XCode.

Adding the following line:
 ?? project.FindFileGuidByProjectPath("Frameworks/MopubSDKFramework.framework); 

to appropriate place in PrepareProject fixes the issue.

- [X] I am submitting a bug report for existing functionality
- [X] I visited https://developers.mopub.com/ and found no answer
- [X] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [X] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
Build and iOS project in Unity 2018.3
Open project

#### Expected behavior:
Can build and run application

#### Observed behavior:
Errors on build due to the MoPubSDKFramework.framework not being in Embedded Libraries section AND Enable Objective-C Exceptions set to No

**Comment by chauduyphanvu1** [comment]
@Jovar, thanks for letting us know! This is a [known issue](https://issuetracker.unity3d.com/issues/ios-frameworks-location-is-ignored-when-building-xcode-project) on Unity's side that was tracked and has been fixed. Please watch for a new Unity Editor release that should contain that fix, but in the meantime, you may continue using the workaround you identified to unblock Xcode builds. That should have no side effects on your MoPub Unity integration.

Let us know if you need anything else!
Vu Chau
MoPub SDK  Team
