### ISSUE TITLE
Unble to do submodule update 

### ISSUE THREAD

**Issue by YadneshCitrus** [mopub/mopub-unity-sdk#3]
I am unable to do submodule update, it says permission denied , following are the logs for it

Yadneshs-MacBook-Pro:mopub-unity-sdk yadnesh$ git submodule init
Yadneshs-MacBook-Pro:mopub-unity-sdk yadnesh$ git submodule update
Cloning into '/Users/yadnesh/Desktop/GitHub/mopub-unity-sdk/mopub-android-sdk'...
The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:mopub/mopub-android-sdk.git' into submodule path '/Users/yadnesh/Desktop/GitHub/mopub-unity-sdk/mopub-android-sdk' failed
Failed to clone 'mopub-android-sdk'. Retry scheduled
Cloning into '/Users/yadnesh/Desktop/GitHub/mopub-unity-sdk/mopub-ios-sdk'...
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:mopub/mopub-ios-sdk.git' into submodule path '/Users/yadnesh/Desktop/GitHub/mopub-unity-sdk/mopub-ios-sdk' failed
Failed to clone 'mopub-ios-sdk'. Retry scheduled
Cloning into '/Users/yadnesh/Desktop/GitHub/mopub-unity-sdk/mopub-android-sdk'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:mopub/mopub-android-sdk.git' into submodule path '/Users/yadnesh/Desktop/GitHub/mopub-unity-sdk/mopub-android-sdk' failed
Failed to clone 'mopub-android-sdk' a second time, aborting
Yadneshs-MacBook-Pro:mopub-unity-sdk yadnesh$

**Comment by aornelas** [comment]
Thanks for the report!

We've fixed this issue in the latest release, so please do the following:
```
git pull origin master
git submodule sync
git submodule update
```

That should take care of it, but feel free to reopen this issue otherwise.

Regards,
Andrés
