### ISSUE TITLE
AdUnit ... not found: no plugin was initialized

### ISSUE THREAD

**Issue by BlackMB** [mopub/mopub-unity-sdk#30]
i have a game that works properly in iOS version, but i get this error on android version when i initialize the Mopub SDK:
"Unity: AdUnit ... not found: no plugin was initialized". - (the "..." is my adUnit.)

in the device with android version 7-8 it takes about 2-3 minutes to load RV. i want to reduce this time!

in another device, with version android 6.0.1, i didn't even get the rewarded video and get this error:
MoPub: Sending message to Unity: MoPubManager#EmitRewardedVideoFailedEvent["adUnit...","No ads found."]
Unity: RewardError: No ads found.

i couldn't find out the solution for this issue yet.
any ideas?

Tested on mopub version 5.3 & 5.4, and unity version is 2018.2.2.f1
use facebook as mediation: 5.1.0 and mopub-fbaudience 5.1.0.0

**Comment by chauduyphanvu1** [comment]
@BlackMB - could you fill out [this template](https://raw.githubusercontent.com/mopub/mopub-unity-sdk/master/.github/ISSUE_TEMPLATE.md) with as much information as you can so we could investigate the issue? Thank you!

Vu Chau
MoPub SDK Team

**Comment by BlackMB** [comment]
> @BlackMB - could you fill out [this template](https://raw.githubusercontent.com/mopub/mopub-unity-sdk/master/.github/ISSUE_TEMPLATE.md) with as much information as you can so we could investigate the issue? Thank you!
> 
> Vu Chau
> MoPub SDK Team

is it possible that the android version 6.0.1 not support the fbaudience 5.1.0?

**Comment by chauduyphanvu1** [comment]
If an SDK's minimum supported Android API version is x.y.z, then you won't be able to install and run the app containing that SDK on devices whose versions are lower/smaller than x.y.z. If you can run it, then it should be supported.

Could you send over a sample project you are using to see the issue? If that's not possible, you can feel free to reproduce it in [our Unity sample app](https://github.com/mopub/mopub-unity-sdk/tree/master/unity-sample-app) and send it to us.
