### ISSUE TITLE
IOS build linker error

### ISSUE THREAD

**Issue by vizgl** [mopub/mopub-unity-sdk#32]
Ios linking error
Mopub version is 5.5.0
Unity 2018.3.3f1
Using adapters: unityads, admob

Error message:
:- 1 :  library not found for -lAvid-mopub-3.6.1

I found library in the Pods\mopub-ios-sdk\MoPubSDK\Viewability\Avid\ fodler but it named as libAvid-mopub-3.6.1.a

**Comment by chauduyphanvu1** [comment]
@vizgl - do you have the repro steps that'd consistently trigger this error? Thanks!

Vu Chau
MoPub SDK Team

**Comment by sdolim** [comment]
The linker flag "-lAvid-mopub-3.6.1" tells the linker to go find a file called "libAvid-mopub-3.6.1.a" (assuming this is a static link build), so if the file is there it may be in a directory that is not being searched.

However the larger problem is that the Unity SDK doesn't support viewability yet anyway, so this library should not even be getting linked at all (same with Moat).  It would be better to remove it from the link list altogether, as well as the header files.  This would be a workaround till we can fix the extra dependency in the podspec, that should not be there.

**Comment by vizgl** [comment]
> The linker flag "-lAvid-mopub-3.6.1" tells the linker to go find a file called "libAvid-mopub-3.6.1.a" (assuming this is a static link build), so if the file is there it may be in a directory that is not being searched.
> 
> However the larger problem is that the Unity SDK doesn't support viewability yet anyway, so this library should not even be getting linked at all (same with Moat). It would be better to remove it from the link list altogether, as well as the header files. This would be a workaround till we can fix the extra dependency in the podspec, that should not be there.

At the current moment, I made first build with Pod file generation enabled, and then copied all downloaded sdk's(except mopub, because it already exist in project) in to unity plugin/ios folder. And on the second build, I disabled pod generation and now all succesfully builded.

**Comment by sdolim** [comment]
It's OK to use pod file generation, but if you do you should **not** copy the downloaded libraries back into Plugins/iOS, and you should also delete MoPubSDKFramework.framework from MoPub/Plugins/iOS.  Then let the Unity Jar Resolver build the pod file for you, which will bring in all these libraries to the Xcode project that Unity creates.

**Comment by vizgl** [comment]
After I delete mopub framework from mopub/plugins/ios, it build without errors

**Comment by chauduyphanvu1** [comment]
@vizgl - good to know! A release of adapter .unitypackage binaries just went out (https://github.com/mopub/mopub-unity-mediation/commit/7a2e7e166f4af9303b90af073840dc01d82f03a7) so check those out as well. They do not download the viewability SDKs (Moat and Avid) so there shouldn't be any linker issue anymore.
