### ISSUE TITLE
stuck on Resolving Android Dependencies

### ISSUE THREAD

**Issue by mubshar1** [mopub/mopub-unity-sdk#33]
stuck on Resolving Android Dependencies
![untitled](https://user-images.githubusercontent.com/45542019/52181384-0b43e780-2813-11e9-9dcf-bfbd62f830e5.png)

**Comment by mubshar1** [comment]
How to integrate ironsource and chartboost network SDKs, Mopub SDK Manager not allowing right now. 
![captureiu](https://user-images.githubusercontent.com/45542019/52198954-64009800-2886-11e9-8c81-098767bfb6ef.PNG)

**Comment by chauduyphanvu1** [comment]
The SDK Manager currently supports only network SDKs that are distributed via JCenter/CocoaPods. Networks that are available for direct downloads as a jar/aar will need to be integrated manually as usual (see https://developers.mopub.com/docs/unity/getting-started/#best-practices).

**Comment by mubshar1** [comment]
Build completed with a result of 'Failed'
![err](https://user-images.githubusercontent.com/45542019/52344301-35c4b900-2a3c-11e9-8d22-1783c8019f3d.PNG)

**Comment by mubshar1** [comment]
build stuck 
![errrt](https://user-images.githubusercontent.com/45542019/52344468-a8ce2f80-2a3c-11e9-84f7-6187a3738383.PNG)

**Comment by mubshar1** [comment]
CommandInvokationFailure: Gradle build failed. 
E:\unity 2018.3\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\OpenJDK\Windows\bin\java.exe -classpath "E:\unity 2018.3\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-4.6.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "assembleRelease"

stderr[
D8: Program type already present: com.unity3d.ads.UnityAds$FinishState

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformDexArchiveWithExternalLibsDexMergerForRelease'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\0.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\1.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\2.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\3.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\4.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\5.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\6.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\7.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\8.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\9.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\10.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\11.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\12.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\13.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\14.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\15.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\16.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\17.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\18.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\19.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\20.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\21.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\22.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\23.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\24.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\25.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\26.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\27.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\28.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\29.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\30.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\31.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\32.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\33.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\34.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\35.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\36.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\37.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\39.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\40.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\41.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\42.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\43.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\44.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\45.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\46.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\47.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\48.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\49.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\50.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\51.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\52.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\53.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\54.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\55.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\56.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\57.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\58.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\59.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\60.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\61.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\62.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\63.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\64.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\65.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\66.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\67.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\68.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\69.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\70.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\71.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\72.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\73.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\74.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\75.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\76.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\77.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\78.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\79.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\80.jar, C:\ads 0.4\Temp\gradleOut\build\intermediates\transforms\dexBuilder\release\81.jar
  Program type already present: com.unity3d.ads.UnityAds$FinishState
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
]
stdout[
:checkReleaseClasspath UP-TO-DATE
:preBuild UP-TO-DATE
:MoPub.plugin:preBuild UP-TO-DATE
:MoPub.plugin:preReleaseBuild UP-TO-DATE
:MoPub.plugin:checkReleaseManifest
:MoPub.plugin:processReleaseManifest
:preReleaseBuild UP-TO-DATE
:MoPub.plugin:compileReleaseAidl NO-SOURCE
:compileReleaseAidl NO-SOURCE
:MoPub.plugin:packageReleaseRenderscript NO-SOURCE
:compileReleaseRenderscript UP-TO-DATE
:checkReleaseManifest UP-TO-DATE
:generateReleaseBuildConfig UP-TO-DATE
:prepareLintJar UP-TO-DATE
:mainApkListPersistenceRelease UP-TO-DATE
:generateReleaseResValues UP-TO-DATE
:generateReleaseResources UP-TO-DATE
:MoPub.plugin:compileReleaseRenderscript
:MoPub.plugin:generateReleaseResValues
:MoPub.plugin:generateReleaseResources
:MoPub.plugin:packageReleaseResources
:mergeReleaseResources UP-TO-DATE
:createReleaseCompatibleScreenManifests UP-TO-DATE
:processReleaseManifest
:splitsDiscoveryTaskRelease UP-TO-DATE
:MoPub.plugin:generateReleaseRFile
:processReleaseResources
:generateReleaseSources
:MoPub.plugin:generateReleaseBuildConfig
:MoPub.plugin:prepareLintJar UP-TO-DATE
:MoPub.plugin:generateReleaseSources
:MoPub.plugin:javaPreCompileRelease
:MoPub.plugin:compileReleaseJavaWithJavac
:MoPub.plugin:processReleaseJavaRes NO-SOURCE
:MoPub.plugin:transformClassesAndResourcesWithPrepareIntermediateJarsForRelease
:javaPreCompileRelease UP-TO-DATE
:compileReleaseJavaWithJavac UP-TO-DATE
:compileReleaseNdk NO-SOURCE
:compileReleaseSources UP-TO-DATE
:lintVitalRelease
:mergeReleaseShaders UP-TO-DATE
:compileReleaseShaders UP-TO-DATE
:generateReleaseAssets UP-TO-DATE
:MoPub.plugin:mergeReleaseShaders
:MoPub.plugin:compileReleaseShaders
:MoPub.plugin:generateReleaseAssets
:MoPub.plugin:packageReleaseAssets
:mergeReleaseAssets
:transformClassesWithDexBuilderForRelease UP-TO-DATE
:transformDexArchiveWithExternalLibsDexMergerForRelease FAILED
35 actionable tasks: 18 executed, 17 up-to-date
]
exit code: 1
UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <e1c3953b4cf040ddb1400046b1c34897>:0)
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <e1c3953b4cf040ddb1400046b1c34897>:0)
UnityEditor.Android.Command.Run (System.String command, System.String args, System.String workingdir, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <e1c3953b4cf040ddb1400046b1c34897>:0)
UnityEditor.Android.AndroidJavaTools.RunJava (System.String args, System.String workingdir, System.Action`1[T] progress, System.String error) (at <e1c3953b4cf040ddb1400046b1c34897>:0)
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <e1c3953b4cf040ddb1400046b1c34897>:0)
Rethrow as GradleInvokationException: Gradle build failed
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <e1c3953b4cf040ddb1400046b1c34897>:0)
UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <e1c3953b4cf040ddb1400046b1c34897>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <e1c3953b4cf040ddb1400046b1c34897>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by chauduyphanvu1** [comment]
@mubshar1 - let us know if you still need assistance with that issue since you closed it!

**Comment by mubshar1** [comment]
getting multidex error every time, when I'm trying to build with mopub and firebase both.

**Comment by chauduyphanvu1** [comment]
You will need to handle multidex via Gradle: https://forum.unity.com/threads/build-using-gradle-and-multidex-support.492117/.

**Comment by mubshar1** [comment]
Mopub 5.4 is working fine along with firebase. there is no issue at all. Then why it is happening now (with mopub 5.5)

**Comment by chauduyphanvu1** [comment]
There might have been more methods in the 5.5.0 release. It also depends on the Firebase components you are using.

**Comment by rsatrasala** [comment]
Please re-open if you have more questions.
