### ISSUE TITLE
IOS - AIRPLANE MODE - Missing one or more values: ["BANNER_ID"] (expected 2)

### ISSUE THREAD

**Issue by agrobost** [mopub/mopub-unity-sdk#34]
I created two banners, one for android and the other for IOS. That works perfectly when I use the banner test ad. I try to use audience network mediation. On android everything works but on ios I had this error:

Missing one or more values: ["BANNER_ID"] (expected 2)

And no banner displayed.

I found how to solve this error. In the file mopub-unity-sdk/mopub-ios-sdk-unity/mopub-ios-sdk-unity/MoPubManager.mm at line 373 I replace

`[self sendUnityEvent:@"EmitAdFailedEvent"];` by `[[self class] sendUnityEvent:@"EmitAdFailedEvent" withArgs:@[_adUnitId, @(_adView.frame.size.height)]];`

I have no more error, but no banner displayed :
Here are the logs:
```
[MoPub-Unity][CreateBanner] Attempting to load ad
[MoPub-Unity][ShowBanner] Attempting to show ad
[MoPub-Unity][EmitAdFailedEvent] Ad failed to load: ({0} {1}
```

I follow these steps (https://developers.facebook.com/docs/audience-network/testing/) : 

> Adding Testers To Your App
> You can test your app or mobile website on physical devices with production ads by ensuring the person testing is added to your Facebook app in any role. This is the recommended method of adding testers to your app:
> 
> Go to your Business Settings.
> Click +Add on the People tab on the left.
> Type the email address of the person you want to your account in Business Manager. You can enter multiple people here.
> You can assign people roles if you wish or you can click Skip to only add them to your account in Business Manager.

I detect no request in "Ad Request Debugger" of audience network.

Can you help me please ?

#### Ad Unit IDs used in reproducing the issue: fc51f3f9b26842579cdd6df7fc0e2440

EDIT : MY BAD, that works after I add a test device I follow these steps (https://developers.facebook.com/docs/audience-network/testing/#test-devices).

**Comment by agrobost** [comment]
I reopen the issue because on IOS if I activate the airplane I still have this bug : 
Missing one or more values: ["BANNER_ID"] (expected 2)

The application does not crash so it's not a problem, but I found the solution.

In the file mopub-unity-sdk/mopub-ios-sdk-unity/mopub-ios-sdk-unity/MoPubManager.mm at line 373 I replace

`[self sendUnityEvent:@"EmitAdFailedEvent"];` by `[[self class] sendUnityEvent:@"EmitAdFailedEvent" withArgs:@[_adUnitId, @(_adView.frame.size.height)]];`

**Comment by sdolim** [comment]
The 2nd argument should actually be whatever the error message was from the ad failure, but that is not passed up from the iOS SDK :( . Also, the 1st argument should be the ad unit id of your ad, so it is weird that it is "BANNER_ID" instead.

**Comment by agrobost** [comment]
It's because I have replaced my banner id by "BANNER_ID" , the first argument is correct ! but no second argument

**Comment by chauduyphanvu1** [comment]
@agrobost - I see there were 3 different issues mentioned on this report, some of which were self-resolved. Do you still need help with any specific issue(s)? If so, let us know!

**Comment by agrobost** [comment]
Can you just please the bug on IOS when the airplane mode is enabled ? Otherwise it's not very important it's not blocking.

**Comment by chauduyphanvu1** [comment]
@agrobost - OK, does that error happen with other banner-related errors (such as no fills) instead of just enabling airplane mode? Do you have the steps to reproduce that issue or could you send over a mini sample project with which you saw that log? Thanks!

**Comment by agrobost** [comment]
No error when no fill. This bug occurs only on IOS when there is no internet. It's not very embarrassing so I close this issue!
