### ISSUE TITLE
Self-defeating 5.5 installer (SDK Manager)

### ISSUE THREAD

**Issue by DavidDurston** [mopub/mopub-unity-sdk#36]
The .unitypackage installer adds a file to the project that the SDK Manager says must not exist.

#### Steps to reproduce the behavior:
1. Create an empty Unity project
2. Install MoPubUnity.unitypackage for version 5.5.0
3. Attempt to launch the SDK Manager via the MoPub dropdown menu

#### Expected behavior:
The SDK Manager lists the available mediated networks.

#### Observed behavior:
The SDK Manager demands deleting the following file, which is installed by the .unitypackage:
/Assets/MoPub/Plugins/iOS/MoPubSDKFramework.framework

#### Evidence:
![screen shot 2019-02-07 at 2 49 46 pm](https://user-images.githubusercontent.com/11182753/52448692-8f36f180-2ae9-11e9-88ca-eaee9276e1a5.png)
![screen shot 2019-02-07 at 3 01 53 pm](https://user-images.githubusercontent.com/11182753/52448694-8f36f180-2ae9-11e9-950a-a3f876c60ab4.png)

**Comment by chauduyphanvu1** [comment]
You only need to delete the iOS SDK framework if you plan to use mediation on iOS. Otherwise you can keep the framework bundled with the MoPub Unity plugin - you can continue using the SDK Manager to manage the MoPub Unity plugin version. The behavior you are seeing is intended.

**Comment by agrobost** [comment]
I am a random guys, but I think it's normal. In any case it works but be careful in xcode you need to add library in "Linked frameworks and libraries" : 
-libmopub-ios-sdk.a
-other mediation networks

But I have a problem, when I add admob network, I can build my app but it crash at the launch..

**Comment by chauduyphanvu1** [comment]
@agrobost What is the stack trace of that crash? Feel free to open a separate issue report so we can debug it.

**Comment by agrobost** [comment]
@chauduyphanvu1 Yes I will do this as quickly as possible, but from time to time it also crash my unity client, I will recover the logs with android studio

**Comment by chauduyphanvu1** [comment]
@agrobost Oh it's an Android crash? Make sure you add the app ID to your Manifest (https://developers.mopub.com/docs/mediation/networks/google/#download-and-integration).

**Comment by agrobost** [comment]
No it's with unity, but it's very weird, I build the app I have no error in the console and the app doesn't launch, nothing happens, but the app is on my phone. I will launch apk with android studio to get the logcat.

**Comment by agrobost** [comment]
2019-02-09 00:27:50.576 12302-12302/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.bonobroo.paperbrain, PID: 12302
    java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: 
    
    ******************************************************************************
    * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
    * should follow the instructions here: https://goo.gl/fQ2neu to add a valid  *
    * App ID inside the AndroidManifest. Google Ad Manager publishers should     *
    * follow instructions here: https://goo.gl/h17b6x.                           *
    ******************************************************************************

You're right, I have to find how to start mopub with the admob app id..

**Comment by chauduyphanvu1** [comment]
Cool - you will be entering the AdMob App ID in the [Manifest](https://github.com/mopub/mopub-unity-sdk/blob/master/unity-sample-app/Assets/MoPub/Plugins/Android/MoPub.plugin/AndroidManifest.xml) shipped with the MoPub Unity plugin. You can find your App ID on the AdMob web dashboard.

Let us know if you need anything else!

**Comment by agrobost** [comment]
That works, thank you very much !!!
