### ISSUE TITLE
Typo in MoPubiOS.cs

### ISSUE THREAD

**Issue by stopiccot** [mopub/mopub-unity-sdk#37]
#### MoPub SDK Version:
5.5

Does not compile on android. Not a big deal but it's a shame that official SDK wasn't tested that it at least compiles.

https://github.com/mopub/mopub-unity-sdk/blob/master/unity-sample-app/Assets/MoPub/Scripts/Internal/MoPubiOS.cs#L500

**Comment by chauduyphanvu1** [comment]
Thanks for pointing this out. We're taking a look and will see what can be done!

Vu Chau
MoPub SDK  Team

**Comment by chauduyphanvu1** [comment]
We have fixed this internally, and will release the fix in the next Unity plugin release.

**Comment by chauduyphanvu1** [comment]
This should be fixed as of v5.6.0 of the Unity SDK. Please update to that version and let us know if you continue seeing the issue!
