### ISSUE TITLE
ios build link error

### ISSUE THREAD

**Issue by kaishuai007** [mopub/mopub-unity-sdk#40]
Ios linking error
mopub 5.50
unity5.6.6 f2
Using adapters: admob

Error message:

ld: warning: arm64 function not 4-byte aligned: ltmp0 from /Users/hlnnana/Documents/unity/exportN/IOSPublish/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
ld: warning: arm64 function not 4-byte aligned: _unwind_tester from /Users/hlnnana/Documents/unity/exportN/IOSPublish/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
ld: warning: object file (/Users/hlnnana/Library/Developer/Xcode/DerivedData/Unity-iPhone-hhmwvauvtpayejfweqvxayoutpau/Build/Products/Debug-iphoneos/libPods-Unity-iPhone.a(Pods-Unity-iPhone-dummy.o)) was built for newer iOS version (9.0) than being linked (8.0)
Undefined symbols for architecture arm64:
  "__moPubSetAdvancedBiddingEnabled", referenced from:
      _MoPubiOS__moPubSetAdvancedBiddingEnabled_m2774479417 in Bulk_Assembly-CSharp_0.o
     (maybe you meant: _MoPubiOS__moPubSetAdvancedBiddingEnabled_m2774479417)
  "__moPubIsAdvancedBiddingEnabled", referenced from:
      _MoPubiOS__moPubIsAdvancedBiddingEnabled_m2332550448 in Bulk_Assembly-CSharp_0.o
     (maybe you meant: _MoPubiOS__moPubIsAdvancedBiddingEnabled_m2332550448)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by sdolim** [comment]
The functions __moPubSetAdvancedBiddingEnabled and __moPubIsAdvancedBiddingEnabled were removed from the iOS wrapper code in v5.5 of the SDK.  This error looks like you still have [DllImport] declarations for them in the MoPubiOS.cs script in Assets/MoPub/Scripts/Internal.  Did that file somehow not get updated to v5.5?

**Comment by kaishuai007** [comment]
thanks, has been resolved
