### ISSUE TITLE
ios applovin sdk key

### ISSUE THREAD

**Issue by kaishuai007** [mopub/mopub-unity-sdk#41]
mopub 5.50
unity5.6.6 f2
Using adapters: applovin

I have seen in this file (AppLovinAdapterConfiguration.m) are as follows

> - (nullable ALSdk *)SDKFromConfiguration:(NSDictionary<NSString *, id> *)configuration
{
    // If there is a configuration cached with SDK key already from any of the custom events, use that instead
    NSDictionary<NSString *, id> *cachedConfiguration = [[self class] cachedInitializationParameters];
    NSDictionary<NSString *, id> *configurationToUse = cachedConfiguration[@"sdk_key"] ? cachedConfiguration : configuration;
    NSString *key = configurationToUse[@"sdk_key"];
    return ( key.length > 0 ) ? [ALSdk sharedWithKey: key] : [ALSdk shared];
}

so, i  write applovin's NetworkConfiguration as follows

> MoPub.MediatedNetwork appLovinMediatedNetwork = new MoPub.SupportedNetwork.AppLovin();
            appLovinMediatedNetwork.NetworkConfiguration = new Dictionary<string, object>()
            {
                {"sdk_key", "xDAwySJa9W_nTnoaJMtNCVVaJ2CiWtuVNVOXLWK3nFJc8QuH1BpdgDKgRiAPhTciKTG1Fuv4D1U6gnGys5AH2p"}
            };

but it's not succeed.  

at ios in xcode info.list add AppLovinSdkKey is succeed.

i think ask , in unity code how to add.

**Comment by chauduyphanvu1** [comment]
@kaishuai007 - when you passed the SDK Key like that, it requires that it is cached by previous ad requests. Have you checked to see that you have made at least 1 ad request already in order for the SDK Key to be fetched from the cache?

**Comment by chauduyphanvu1** [comment]
@kaishuai007 - do you have any update to the issue or to our question?

**Comment by kaishuai007** [comment]
thanks, I have modified adapters code to meet my needs
