### ISSUE TITLE
MoPubAndroid.HasRewardedVideo not working sometimes

### ISSUE THREAD

**Issue by chechulinYuri** [mopub/mopub-unity-sdk#42]
Rewarded Video
Android
mopub 5.5.0
com.mopub.mediation.unityads-3.0.0.1
com.unity3d.ads.unity-ads-3.0.0
MoPub-UnityAds-Adapters-prod-1.0.1-Android.3.0.0.1-iOS.3.0.0.4

Sometimes MoPubManager.OnRewardedVideoLoadedEvent fired but MoPubAndroid.HasRewardedVideo() return false forever

**Comment by sdolim** [comment]
Are there any messages in the logcat mentioning the ad unity id for this ad?  (Something like "AdUnit xx not found" or similar.)

**Comment by rsatrasala** [comment]
Please re-open if needed. Thank you.
