### ISSUE TITLE
Unity Ads SDK link broken for Mopub v5.5 SDK manager

### ISSUE THREAD

**Issue by IVeselovskyy** [mopub/mopub-unity-sdk#44]
I'm getting a 404 when trying to download Unity Ads SDK (v1.0.2) through the SDK manager.

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.5
#### Unity Version:
2017.4.16f1

#### Steps to reproduce the behavior:
Try to download Unity Ads SDK through the SDK manager.

#### Expected behavior:
The Unity package for Unity Ads SDK gets downloaded.

#### Observed behavior:
A 404 gets thrown when trying to download Unity Ads SDK. Other SDKs get downloaded without any issue.

#### Evidence:
Download attempt log:
```
Downloading https://firebasestorage.googleapis.com/v0/b/mopub-mediation.appspot.com/o/MoPub-UnityAds-Adapters-prod-1.0.2-Android.3.0.1.0-iOS.3.0.1.0.unitypackage?alt=media to Assets/MoPub/MoPub-UnityAds-Adapters-prod-1.0.1-Android.3.0.0.1-iOS.3.0.0.4.unitypackage
```
Error: 
```
System.Net.WebException: The remote server returned an error: (404) Not Found.
  at System.Net.HttpWebRequest.CheckFinalStatus (System.Net.WebAsyncResult result) [0x00000] in <filename unknown>:0 
  at System.Net.HttpWebRequest.SetResponseData (System.Net.WebConnectionData data) [0x00000] in <filename unknown>:0 
UnityEngine.Debug:LogError(Object)
<DownloadSDK>c__Iterator1:MoveNext() (at Assets/MyProject/MoPub/Scripts/Editor/MoPubSDKManager.cs:404)
marijnz.EditorCoroutines.EditorCoroutines:MoveNext(EditorCoroutine) (at Assets/MyProject/MoPub/Scripts/ThirdParty/EditorCoroutines/Editor/EditorCoroutines.cs:368)
marijnz.EditorCoroutines.EditorCoroutines:OnUpdate() (at Assets/MyProject/MoPub/Scripts/ThirdParty/EditorCoroutines/Editor/EditorCoroutines.cs:351)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()
```

**Comment by chauduyphanvu1** [comment]
@IVeselovskyy - thanks for letting us know! We updated the package but it looked like the change did not thoroughly propagate. I've tested it again and it's working now. 

Vu Chau
MoPub SDK Team

**Comment by IVeselovskyy** [comment]
@chauduyphanvu1 Thanks, looks good now!
