### ISSUE TITLE
SDK Manager Adds Chartboost Adapter

### ISSUE THREAD

**Issue by temresen** [mopub/mopub-unity-sdk#47]
SDK Manager adds Chartboost adapter to unity project and it also comes from podfile in iOS.

So, when you try to build on iOS there will be duplicate adapters for Chartboost and Xcode does not build successfully.

MoPub SDK Version: 5.5
Unity Version: 2017.4.23f1

Open Unity.
Install Chartboost from MoPuB -> SDK Manager
Take a build for iOS.

To one who face with the same problem, just delete Chartboost adapter from your unity project except Editor file. 

Evidence:
<img width="968" alt="Screen Shot 2019-03-15 at 5 28 04 PM" src="https://user-images.githubusercontent.com/16319223/54438507-ce3f0f00-4747-11e9-81df-46ed16517104.png">

**Comment by chauduyphanvu1** [comment]
@temresen - thank you for letting us know about that! We'll prepare a fix and let you know when it's in production.

Vu Chau
MoPub SDK Team

**Comment by chauduyphanvu1** [comment]
@temresen - this issue has been addressed via a new Chartboost Unity package released just now (https://github.com/mopub/mopub-unity-mediation/commit/3b06b0f9d1a7297faff6b7bef62f57e8b08573e5). If you use the SDK Manager, simply download v1.0.4 of the Chartboost Unity package. Let us know if you continue seeing the duplicate iOS adapter source files!
