### ISSUE TITLE
MoPub Unity SDK 5.5.0 dependency mopub-ios-sdk 5.6.0

### ISSUE THREAD

**Issue by jim1019** [mopub/mopub-unity-sdk#49]
MoPub Unity SDK 5.5.0 MoPubBinding.m line 137 need MPLogLevel,but mopub-ios-sdk 5.6.0 use MPBLogLevel replace MPLogLevel
 
solution:
ns.dependency 'mopub-ios-sdk/Core', '~> 5.5'

Need to be modified to

ns.dependency 'mopub-ios-sdk/Core', '~> 5.5.0'

**Comment by chauduyphanvu1** [comment]
@jim1019 - this has been addressed at the SDK level internally and the fix should go out in the upcoming Unity SDK release. Check it out when it's live and let us know if you continue seeing the issue!

Vu Chau
MoPub SDK Team

**Comment by jim1019** [comment]
@chauduyphanvu1  Can Unity sdk and ios sdk be released at the same time, because this kind of error situation is mandatory, if I am a newbie, the first time I install and use it, I will be at a loss.

**Comment by chauduyphanvu1** [comment]
@jim1019 - thank you for the feedback; I'll bring it back to the rest of the team! Historically, we have been releasing the Unity SDK a couple days after the Android and iOS SDKs are released. This is because the Unity SDK submodules the Android and iOS SDKs, so to allow for thorough testing, all three SDKs cannot feasibly go out at the same time. 

What's happening specifically on this thread is that, the iOS SDK is fetched by the Jar Resolver via the mediation adapters (as you pointed out). Previously, we included a static iOS SDK with the Unity release so this type of issue didn't exist. We'll discuss internally on ways to streamline this process.

**Comment by MixMasterRickyC** [comment]
I've literally just spent the last 1 hour trying to figure out why our iOS version is failing to build. 

Why would the cocoapods be downloading a version of the SDK which isn't compatible? Surely it should only grab the 5.6.0 version of the framework once I've updated it? Until then it should stick to 5.5.0.

Is this going to be an issue in the future when newer versions are release?

If we need to get a new version of our app out and then suddenly we can't build for a couple of days this really puts us in a bind.

**Comment by chechulinYuri** [comment]
Should we just replace MPLogLevel with MPBLogLevel? Does it break something?
It blocked our release for a whole day, only now we found that bug report!

**Comment by MixMasterRickyC** [comment]
@chechulinYuri, we've done that (replace MPLogLevel with MPBLogLevel) to get it compiling, not sure if they'll be a knock on affect.

Just needed to be able to build to allow our QA to test on that platform. We won't be releasing until we've completely updated to 5.6.0

**Comment by chechulinYuri** [comment]
When will you release the fix? We can't update the project for two days already due to that issue

**Comment by chauduyphanvu1** [comment]
Hello all, please update to [v5.6.0 of the Unity SDK](https://github.com/mopub/mopub-unity-sdk/releases) to resolve this issue. Starting with this release, we've begun locking the iOS SDK version dependency for the Unity SDK, so from now on, the Jar Resolver will prioritize the iOS SDK version that is compatible with the Unity SDK version you have over the iOS SDK version that is pulled by the mediation adapters. This way, we are confident this kind of issue will not happen again.

Let us know if you need anything else.
