### ISSUE TITLE
Pod Install Failure

### ISSUE THREAD

**Issue by temresen** [mopub/mopub-unity-sdk#50]
PostProcessor(or sth else. not sure) inserts an empty path on podfile for AppLovin Adapter. 

MoPub SDK Version: 5.6.0

Unity Version: 2017.4.23f1

Evidence:
![Screen Shot 2019-03-26 at 7 04 15 PM](https://user-images.githubusercontent.com/16319223/55059827-01a36700-5081-11e9-871a-c3e70c99c274.png)
<img width="1136" alt="Screen Shot 2019-03-26 at 7 04 51 PM" src="https://user-images.githubusercontent.com/16319223/55059832-0405c100-5081-11e9-9307-a2b9c89ac391.png">
![Screen Shot 2019-03-26 at 7 14 22 PM](https://user-images.githubusercontent.com/16319223/55059837-07994800-5081-11e9-8daf-5c1cffa7157a.png)
![Screen Shot 2019-03-26 at 7 05 35 PM](https://user-images.githubusercontent.com/16319223/55059841-0b2ccf00-5081-11e9-9339-7751fea79e24.png)

**Comment by dravyan** [comment]
Hi @temresen ,
Thanks for reporting the issue. We will look into this and get back to you.

Thanks,
Dravya
MoPub SDKTeam

**Comment by dravyan** [comment]
@temresen, could you please try updating to the  newer AppLovin unitypackage that we released today and use `Replace` when building the app ?.


Thanks,
Dravya Nataraj
MoPub SDKTeam

**Comment by MixMasterRickyC** [comment]
This is the same for the latest AdMob update (1.0.3)

```
 <iosPods>
   <iosPod name="MoPub-AdMob-Adapters" subspecs="['Network']" bitcodeEnabled="false" minTargetSdk="9.0"
           path="Assets/MoPub/Mediation/AdMob/Adapter/iOS"/>
 </iosPods>
```

The Adapter doesn't exist so it throws an installation failure error.

I also tried updating the AppLovin unitypackage and the same thing happened.

```
<iosPods>
   <iosPod name="MoPub-Applovin-Adapters" subspecs="['Network']" bitcodeEnabled="false" minTargetSdk="9.0"
           path="Assets/MoPub/Mediation/AppLovin/Adapter/iOS"/>
 </iosPods>
```

These locations don't exist and aren't part of either  `.unitypackage`

```
Assets/MoPub/Mediation/AppLovin/Adapter/iOS
Assets/MoPub/Mediation/AdMob/Adapter/iOS
```

Are we meant to install the adapters manually?

The AppLovin dependencies used to point to an actual version.

```
<iosPods>
   <iosPod name="MoPub-Applovin-Adapters" subspecs="['Network']" bitcodeEnabled="false" minTargetSdk="9.0"
           version="6.2.0.0"/>
 </iosPods>
```

**Comment by dravyan** [comment]
@MixMasterRickyC, 
When you select Platform as iOS and build the project in Unity, if you tried to choose `Append` in the Build dialogue, the pod file from before is retained. Using `Replace` should fix this. But if it does not, then delete the Xcode project and rebuild should work. Let me know if you have any questions.

Thanks,
Dravya Nataraj
MoPub SDK Team

**Comment by MixMasterRickyC** [comment]
Under Build Settings? I don't have that option, we're running Unity 2017.4.23f1. Is this something from Unity 2018?

Also what happens if this is a fresh install? I won't have pod files from before? We also our build process which means it's always a fresh Xcode project.

**Comment by temresen** [comment]
@MixMasterRickyC for a fast fix you can use this podfile. I did not have a problem with this podfile. 

@dravyan I could not find a chance to test new unitypackage. I will try it tomorrow and let you know.

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.3'

target 'Unity-iPhone' do
pod 'MoPub-AdMob-Adapters', '7.39.0.0', :subspecs => ['Network']
pod 'MoPub-Applovin-Adapters', '6.2.0.1', :subspecs => ['Network']
pod 'MoPub-Chartboost-Adapters', '7.3.0.5', :subspecs => ['Network']
pod 'MoPub-FacebookAudienceNetwork-Adapters', '5.1.0.4', :subspecs => ['Network']
pod 'mopub-ios-sdk', '5.6.0', :subspecs => ['Core']
pod 'MoPub-IronSource-Adapters', '6.8.1.0.2', :subspecs => ['Network']
pod 'MoPub-SDK-Plugin', :path => '/Users/**path**/**path**/Unity Projects/**path**/Assets/MoPub/Plugins/iOS'
pod 'MoPub-TapJoy-Adapters', '12.2.0.4', :subspecs => ['Network']
pod 'MoPub-UnityAds-Adapters', '3.0.1.0', :subspecs => ['Network']
pod 'MoPub-Vungle-Adapters', '6.3.2.5', :subspecs => ['Network']
end
```

**Comment by temresen** [comment]
Just updated all the packages. AppLovin problem fixed but now, the same thing happens for AdMob.

**Comment by temresen** [comment]
Latest updates for adapter packages solved the problem. 

This issue may be closed.
