### ISSUE TITLE
iOS - Clicks on VAST ads are not working

### ISSUE THREAD

**Issue by tontonpiero** [mopub/mopub-unity-sdk#54]
Our VAST ads don't work anymore on some of our iPhones.

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.5.0

#### Device model and OS Version:
iPhone 5, iOS 12.1.4 <-- Working
iPhone 8, iOS 12.2 <-- Not working

#### Unity Version:
2018.2.2f1

#### Ad Unit IDs used in reproducing the issue:
de64e6ad4e75489db4f985b3ebe5d97b

#### Steps to reproduce the behavior:
- Use the MoPub test app with the ad unit id containing the VAST video interstitials attached below
- Click on the ad button when it appears

#### Expected behavior:
Clicks should redirect to the ad website

#### Observed behavior:
The clicks are not working on an iPhone 8, iOS 12.2
Clicks work fine on an iPhone 5, iOS 12.1.4

#### Evidence:
[vast.txt](https://github.com/mopub/mopub-unity-sdk/files/3098454/vast.txt)

**Comment by dravyan** [comment]
Hello @tontonpiero,
  Thank you for reporting this. We will try to replicate it. Meanwhile could you share logs from iPhone 8, iOS 12.2 you are testing with in order to investigate further?


Thanks,
Dravya Nataraj
MoPub SDKTeam

**Comment by dravyan** [comment]
The fix on our server side has resolved this issue. Let us know if the issue happens again.

Thanks,
Dravya Nataraj
MoPub SDKTeam
