### ISSUE TITLE
EmitRewardedVideoReceivedRewardEvent is  throwing format exception on some systems with non-english language 

### ISSUE THREAD

**Issue by sayiliromer** [mopub/mopub-unity-sdk#57]
One line summary of the issue here

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version: 
5.6.0

#### Device model and OS Version: 
Provided log is from iPhone5c but i can practically applies on all devices 

#### Unity Version: 
2018.3.14f1

#### Ad Unit IDs used in reproducing the issue: 
c091d59049a7402aa34defd942644f23

#### Steps to reproduce the behavior:
Set device language to Russian (I think French works too but provided crash log was in Russian) and watch an ad to get reward callback.

#### Expected behavior:
All exceptions should be handled correctly. 

#### Observed behavior:
format exception thrown in  EmitRewardedVideoReceivedRewardEvent(string argsJson) 
because "float.Parse(string)" used inside the function is using culture info with device language by default. We fixed issue by providing "CultureInfo.InvariantCulture" to float.Parse(string,cultureinfo). 

#### Evidence:
Logs are in the attachment, it is a unity diagnostics file. 
[crashlog.txt](https://github.com/mopub/mopub-unity-sdk/files/3138324/crashlog.txt)

#### Log Summary

Managed Stack Trace:

  at System.Number.ParseSingle (System.String value, System.Globalization.NumberStyles options, System.Globalization.NumberFormatInfo numfmt) [0x00000] in <00000000000000000000000000000000>:0 

The last log is 

[MoPub-Unity] [EmitRewardedVideoReceivedRewardEvent] Ad should reward user with 0.000000

**Comment by sayiliromer** [comment]
On here, patch notes.
https://unity3d.com/unity/whats-new/2018.3.13
IL2CPP: Fixed default current culture not being detected correctly on macOS and iOS instead of the invariant culture. (1133961, 1135065)

I believe the bug that they fixed, changed the default behavior of all CultureInfo depended functions.  
Including double.Parse, float.Parse , System.Convert.ToDouble , string.ToUpper etc. 

It can be solved by setting default cultureinfo to InvariantCulture

In .Net 4.x you can set for all app domain
 CultureInfo.DefaultThreadCurrentCulture = CultureInfo.InvariantCulture;

In .Net 3.5 you can set it per thread
System.Threading.Thread.CurrentThread.CurrentCulture = CultureInfo.InvariantCulture;

**Comment by chauduyphanvu1** [comment]
@sayiliromer - thanks for letting us know! I'll relay the issue to the rest of the team, and we'll see what we can do for the next SDK release.

Vu Chau
MoPub SDK Team

**Comment by aornelas** [comment]
thanks for reporting!

fixed in the [5.7.0 release](https://github.com/mopub/mopub-unity-sdk/releases/tag/v5.7.0)
