### ISSUE TITLE
No way to set testDevices for AdMob

### ISSUE THREAD

**Issue by appetizermonster** [mopub/mopub-unity-sdk#58]
It looks the latest version unity plugin doesn't have a way to set `testDevices` for AdMob.
I just wanted to report it 😅

**Comment by chauduyphanvu1** [comment]
@appetizermonster - thanks for letting us know. We are working on this feature. In the next Unity SDK release, you will be able to pass network-specific data (like a test device ID for AdMob), so stay tuned!

Vu Chau
MoPub SDK Team

**Comment by appetizermonster** [comment]
That sounds awesome! 👍

**Comment by chauduyphanvu** [comment]
@appetizermonster, I wanted to let you know that this feature is now supported in Unity. However, the Android and iOS AdMob adapters still need to be refactored to read the test device ID passed from Unity. We'll update you when the refactoring is done!

**Comment by dsabatier** [comment]
I was able to get a test device added by initializing the mopub SDK this way:
```
                MoPubBase.MediatedNetwork adMobSettings = new MoPubBase.SupportedNetwork.AdMob
                {
                    MediationSettings = new Dictionary<string, object>()
                    {
                        {"testDeviceId", "DEVICEIDABC123" }
                    },
                };

                MoPubBase.SdkConfiguration config = new MoPubBase.SdkConfiguration()
                {
                    AdUnitId = "my ad unit",
                    MediatedNetworks = new [] { adMobSettings },
                    LogLevel = MoPubBase.LogLevel.Debug

                };
```
