### ISSUE TITLE
FbAudience Network Ads not showing up after integrating in unity 2018.3.8f1

### ISSUE THREAD

**Issue by shanukp** [mopub/mopub-unity-sdk#60]
unity version - 2018.3.8f1

Receiving MOPUB-OnRewardedVideoFailed - No ads found.

**Comment by shanukp** [comment]
Installed FbAudience network from Mopub Sdk manager

**Comment by shanukp** [comment]
[Admanager.txt](https://github.com/mopub/mopub-unity-sdk/files/3176768/Admanager.txt)
this is the init code , ran play services resolver after installing FB audience network from MOPUB SDK MANAGER

**Comment by shanukp** [comment]
Do i have to download and install FB audience unity sdk also or does the MOPUB SDK MAnager take care of pulling the required aar .

**Comment by shanukp** [comment]
E FBAudienceNetwork: You don't call AudienceNetworkAds.initialize(). Some functionality may not work properly.

**Comment by shanukp** [comment]
Not sure why i have to call Audience network separately when we are using Mopub to manage that?

**Comment by shanukp** [comment]
Updating ad debug logging enablement.
05-14 15:09:55.492  6346  6483 W Ads     : Update ad debug logging enablement as false
05-14 15:09:55.560  6346  6364 E Unity   : MOPUB-OnSdkInitializedEvent
05-14 15:09:55.560  6346  6364 E Unity   :
05-14 15:09:55.560  6346  6364 E Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
05-14 15:09:55.560  6346  6364 E Unity   :
05-14 15:09:55.581  6346  6364 I Unity   : 1 rewarded video AdUnits loaded for plugins:
05-14 15:09:55.581  6346  6364 I Unity   : wordscasual_android_w2e_facebook_test
05-14 15:09:55.581  6346  6364 I Unity   :
05-14 15:09:55.581  6346  6364 I Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
05-14 15:09:55.581  6346  6364 I Unity   :
05-14 15:09:55.892  6346  6472 E ActivityThread: Failed to find provider info for com.facebook.katana.provider.AttributionIdProvider
05-14 15:09:56.674  6346  6364 E Unity   : MOPUB-OnRewardedVideoFailedEventwordscasual_android_w2e_facebook_test-------No ads found.
05-14 15:09:56.674  6346  6364 E Unity   :
05-14 15:09:56.674  6346  6364 E Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)

**Comment by sdolim** [comment]
Is this part supposed to be commented out?

    //MediatedNetworks = new MoPub.MediatedNetwork[]
    //{
    //    new MoPub.SupportedNetwork.AdMob(), new MoPubBase.SupportedNetwork.Facebook()
    //}

**Comment by shanukp** [comment]
Tried with that part also

**Comment by shanukp** [comment]
Still getting No Ads Found

**Comment by shanukp** [comment]
Is there any thing else to add in unity other than installing fb audience network through Mopub Sdk manager? and then use the mopub slot id which contains fb audience network ?

**Comment by shanukp** [comment]
Let me summarize entire procedure 
- Integrate mopub unity package
- Go to Mopub sdk manager - install fb audience network
- Now create Admanager script like the one attached above
- Pass adunit id as generated in MoPub portal which contains fb network

Thats it , No ads for Facebook Audience Netwrok.

Anything else iam missing?

**Comment by shanukp** [comment]
adUnitId being used for test is something like this ee759f1a1bfd49a69b08d0e49278b7d4

**Comment by chauduyphanvu1** [comment]
@shanukp, there's no need for publishers to initialize mediation network SDKs directly. That's already taken care of [here](https://github.com/mopub/mopub-android-mediation/blob/master/FacebookAudienceNetwork/src/main/java/com/mopub/mobileads/FacebookAdapterConfiguration.java#L69-L71) in the adapter.

Could you enable verbose logging (like [so](https://github.com/mopub/mopub-unity-sdk/blob/master/unity-sample-app/Assets/MoPub/Sample/MoPubDemoGUI.cs#L228)) so we can get more log to help debug the issue? This could be a no fill scenario; in that case, make sure you try again at other times to see if there are ads.

Also, please consolidate all your responses into one post (and edit the post to add updates).

Vu Chau
MoPub SDK Team

**Comment by shanukp** [comment]
Seems like i found the problem after looking at debug logs
Missed this for android - 
MoPubAndroid.AddFacebookTestDeviceId("a9d9def0-e28e-4de2-8d40-021f12283c10");

Couln't find any similar api for iOS , do i have to whitelist for test ads in iOS as well ,
AddFacebookTestDeviceId() is not in MoPubiOs

**Comment by chauduyphanvu1** [comment]
That call should only be used for testing purposes. Ensure that you remove it when publishing your apps (because you don't want to keep getting test ads). 

It doesn't seem like the equivalent API is available on iOS. Let me check with the team. Alternatively, you could enter your iOS IDFA on the Facebook Audience Network dashboard: https://developers.facebook.com/docs/audience-network/testing/.

**Comment by chauduyphanvu1** [comment]
@shanukp, do you still need any assistance on this issue? Feel free to close the ticket otherwise.
