### ISSUE TITLE
Mopub Unity SDK for iOS Build

### ISSUE THREAD

**Issue by bugbytestudio** [mopub/mopub-unity-sdk#62]
I'm using Unity 2017.4.10f, Xcode Version 9.1 (9B55), Mopub SDK 5.6.0. When I open my project in Xcode and to archive it gives me an error. I tried disabling bitcode but it didn't resolve my issue. 

Showing All Messages
IosVersion/Pods/FBAudienceNetwork/Static/FBAudienceNetwork.framework/FBAudienceNetwork(FBAdExtraHint.m.o), could not parse object file IosVersion/Pods/FBAudienceNetwork/Static/FBAudienceNetwork.framework/FBAudienceNetwork(FBAdExtraHint.m.o): **'Invalid bitcode version (Producer: '1001.0.46.3_0' Reader: '900.0.38_0')',** using libLTO version 'LLVM version 9.0.0, (clang-900.0.38)' file IosVersion/Pods/FBAudienceNetwork/Static/FBAudienceNetwork.framework/FBAudienceNetwork' for architecture arm64

Waiting for your support :)

**Comment by thomasmso** [comment]
The FAN SDK MoPub certified against is 5.3.0 - which requires Xcode 10.2 or later. See Change Log [here](https://developers.facebook.com/docs/audience-network/changelog-ios#5_3_0).

**Comment by bugbytestudio** [comment]
Thanks for letting me know is there any way to downgrade to FAN SDK 5.2.0 through Mopub Mediation or upgrading to XCode 10.2 is the only option.

**Comment by chauduyphanvu1** [comment]
@bugbytestudio, you can use `pod 'MoPub-FacebookAudienceNetwork-Adapters', '5.2.0.0'` to get v5.2.0.0 of the adapters and v5.2.0 of the Facebook Audience Network SDK.

Vu Chau
MoPub SDK Team

**Comment by bugbytestudio** [comment]
Hi, @chauduyphanvu1 I tried doing this but Pod is not helping me to install FAN through it. 
<img width="817" alt="Screen Shot 2019-05-20 at 11 32 42 PM" src="https://user-images.githubusercontent.com/50843314/58043888-d7899500-7b57-11e9-8f5f-faf6edcff3e6.png">

**Comment by chauduyphanvu1** [comment]
@bugbytestudio, `pod 'MoPub-FacebookAudienceNetwork-Adapters', '5.3.0.0'` is the name of the pod, but the command to install it is `pod update` or `pod install`. You need to put the pod name in a Podfile, and run the command from the directory containing the Podfile.

**Comment by bugbytestudio** [comment]
Okay, @chauduyphanvu1 I did what you said. But got this error now. Pod file and terminal screenshots are attached below:
<img width="656" alt="Screen Shot 2019-05-20 at 11 57 28 PM" src="https://user-images.githubusercontent.com/50843314/58045220-3f8daa80-7b5b-11e9-9ec7-de99a8e3c078.png">
<img width="187" alt="Screen Shot 2019-05-20 at 11 57 25 PM" src="https://user-images.githubusercontent.com/50843314/58045230-47e5e580-7b5b-11e9-89c1-31aae84e13c4.png">

**Comment by bugbytestudio** [comment]
Okay, @chauduyphanvu1 I did what you said. But got this error now. Pod file and terminal screenshots are attached below:
<img width="656" alt="Screen Shot 2019-05-20 at 11 57 28 PM" src="https://user-images.githubusercontent.com/50843314/58045256-5e8c3c80-7b5b-11e9-9a77-fd095feab109.png">

<img width="708" alt="Screen Shot 2019-05-20 at 11 57 02 PM" src="https://user-images.githubusercontent.com/50843314/58045272-664be100-7b5b-11e9-97af-6a087bfbd3bd.png">

**Comment by chauduyphanvu1** [comment]
@bugbytestudio, try again without the `pod 'MoPub-SDK-Plugin'` for now. I'm checking with the rest of the team on whether that specific pod is needed.

**Comment by bugbytestudio** [comment]
@chauduyphanvu1  still same issue. Attaching a screenshot with this thread 
<img width="1424" alt="Screen Shot 2019-05-21 at 12 27 51 AM" src="https://user-images.githubusercontent.com/50843314/58046769-ad3bd580-7b5f-11e9-8f27-572d615916e1.png">

**Comment by chauduyphanvu1** [comment]
I still see `pod 'MoPub-SDK-Plugin' ......` in your Podfile. It's a local pod for the MoPub Unity SDK - you don't need to extract it to your Podfile. It should be removed.

**Comment by bugbytestudio** [comment]
Thanks for pointing out. I just deleted it and it works like a charm. Let me archive it now

**Comment by bugbytestudio** [comment]
Still getting the same linker error.
<img width="853" alt="Screen Shot 2019-05-21 at 1 07 20 AM" src="https://user-images.githubusercontent.com/50843314/58049588-a5336400-7b66-11e9-95ec-4e424cdde937.png">

<img width="564" alt="Screen Shot 2019-05-21 at 1 21 11 AM" src="https://user-images.githubusercontent.com/50843314/58049646-c7c57d00-7b66-11e9-8301-9c63e81231d5.png">


Should I downgrade it more to 5.1.0?

**Comment by chauduyphanvu1** [comment]
@bugbytestudio, you aren't expected to downgrade the Facebook Audience Network SDK to 5.1.0 or lower to get past this error. Could you send over a zipped project that reproduces the issue so we can investigate? Thank you!

**Comment by bugbytestudio** [comment]
@chauduyphanvu1  where I have to send you?

**Comment by chauduyphanvu1** [comment]
@bugbytestudio, could you zip up your project and send it over Google Drive? If it's sensitive, just paste the link and grant me permission when I request for it. Thank you!

**Comment by bugbytestudio** [comment]
@chauduyphanvu1  kindly email me at bugbytestudio@gmail.com I will share the link with you as I don't have a pro account so anyone with the link can edit it.

**Comment by chauduyphanvu1** [comment]
@bugbytestudio, you should be able to upload a zip file and make it shareable to only certain people upon request. Let us know if that works! Otherwise, see if you can reproduce the same error(s) in our Unity sample app (in this repository). If you can, let us know the steps you try.

**Comment by bugbytestudio** [comment]
@chauduyphanvu1 kindly find the attached link for the project: https://www.dropbox.com/s/41puen7iy4ocurr/escape-house-of-fear-unity-iOS.zip?dl=0

**Comment by bugbytestudio** [comment]
@chauduyphanvu1 can you please take a look into this issue?

**Comment by chauduyphanvu1** [comment]
@bugbytestudio I'm not seeing the same error as you. There are errors around the MoPub SDK not existing in the project. Also, I've just realized I don't have Xcode 9.x installed on my machine to reproduce the issue you're facing.

Could you walk me through your integration process? For example, did you use the [MoPub's SDK Manager](https://developers.mopub.com/publishers/unity/get-started/#option-1-use-the-sdk-manager-recommended) to download and integrate the Facebook Audience Network SDK? Is there a chance you could upgrade to Xcode 10.x to try again?

**Comment by rsatrasala** [comment]
Closing, please open a new issue if needed.
