### ISSUE TITLE
MiniJSON and double issues

### ISSUE THREAD

**Issue by paradizIscool** [mopub/mopub-unity-sdk#64]
minijson don't use CulutreInfo.InvariantCulture for parsing double so publisher_revenue fail on non dotted decimal number

fix
Double.TryParse(number, NumberStyles.Float, CultureInfo.InvariantCulture, out parsedDouble);

- [x] I am submitting a bug report for existing functionality
- [ ] I visited https://developers.mopub.com/ and found no answer
- [ ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
Use french device f.e.

**Comment by paradizIscool** [comment]
Only if .Net 4.x

**Comment by chauduyphanvu1** [comment]
@paradizIscool, thanks for letting us know! We'll apply a fix in an upcoming SDK release. 

Vu Chau
MoPub SDK Team

**Comment by rsatrasala** [comment]
This issue is fixed in 5.8.0. Closing.
