### ISSUE TITLE
ironSource MPlogDebug invalid, missing MPLogging.h

### ISSUE THREAD

**Issue by Eirienen** [mopub/mopub-unity-sdk#66]
Missing MPLogger.h import line.

- [X] I am submitting a bug report for existing functionality
- [X] I visited https://developers.mopub.com/ and found no answer
- [X] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ X] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
Using cocoapods.
1. Create empty unity project. Switch to IOS build, Run in XCode as Debug and development build as true.
2. Download and import mopub unitypackage v. 5.7.1
3. Manage SDK: download ironSource adapter, v. 6.8.4.0
4. Build project.
5. Open *.xcworkspace
6. Build in Xcode, check errors.

#### Expected behavior:
No errors

#### Observed behavior:
Error while building in XCode.
Sample project doesn't build in Xcode, problem with:
IronSource adapter: 6.8.4.0
Mopub_Sample/Pods/MoPub-IronSource-Adapters/IronSource/IronSourceManager.m:69:9: Implicit declaration of function 'MPLogDebug' is invalid in C99 and others files.

Missing: #import "MPLogging.h".

#### Evidence:
Mopub_Sample/Pods/MoPub-IronSource-Adapters/IronSource/IronSourceManager.m:69:9: Implicit declaration of function 'MPLogDebug' is invalid in C99

**Comment by dravyan** [comment]
@Eirienen ,
We are trying to reproduce the issue internally. We will revert back on this soon. In the meantime, if there any specific steps you followed to repro the issue, please let us know.

Thanks,
Dravya Nataraj
MoPub SDK team

**Comment by Eirienen** [comment]
Updated issue with repro steps.

**Comment by Eirienen** [comment]
<img width="277" alt="Zrzut ekranu 2019-06-19 o 14 47 36" src="https://user-images.githubusercontent.com/9266207/59766755-2f273780-92a1-11e9-8917-f6962768bf45.png">

**Comment by dravyan** [comment]
@Eirienen, this issue has been addressed and fixed in MoPub unitypackage`1.1.9`. Please update the unity package.

Thanks,
Dravya Nataraj
MoPub SDK Team
