### ISSUE TITLE
OverflowException From MiniJson.cs

### ISSUE THREAD

**Issue by MochaGameStudio** [mopub/mopub-unity-sdk#67]
One line summary of the issue here

- [1 ] I am submitting a bug report for existing functionality
- [ ] I visited https://developers.mopub.com/ and found no answer
- [ ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [1 ] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.7.1 or 5.6.0
#### Device model and OS Version:
Unity Editor On PC
#### Unity Version:
2018.2.18f1
#### Steps to reproduce the behavior:
1. import the SDK to Unity Project.
2. open "Manage SDKs" from Menu/MoPub/Manage SDKs......
3. then the exception come up in the console after a while

#### Expected behavior:
Download the SDKs successed in the manage window

#### Evidence:
OverflowException: Value was either too large or too small for a character.
System.Convert.ToChar (System.Int32 value) (at <f2e6809acb14476a81f399aeb800f8f2>:0)
MoPubInternal.ThirdParty.MiniJSON.Json+Parser.get_PeekChar () (at Assets/MoPub/Scripts/ThirdParty/MiniJSON.cs:317)
MoPubInternal.ThirdParty.MiniJSON.Json+Parser.EatWhitespace () (at Assets/MoPub/Scripts/ThirdParty/MiniJSON.cs:306)
MoPubInternal.ThirdParty.MiniJSON.Json+Parser.get_NextToken () (at Assets/MoPub/Scripts/ThirdParty/MiniJSON.cs:358)
MoPubInternal.ThirdParty.MiniJSON.Json+Parser.ParseValue () (at Assets/MoPub/Scripts/ThirdParty/MiniJSON.cs:198)
MoPubInternal.ThirdParty.MiniJSON.Json+Parser.Parse (System.String jsonString) (at Assets/MoPub/Scripts/ThirdParty/MiniJSON.cs:122)
MoPubInternal.ThirdParty.MiniJSON.Json.Deserialize (System.String json) (at Assets/MoPub/Scripts/ThirdParty/MiniJSON.cs:89)
MoPubSDKManager+<GetSDKVersions>c__Iterator0.MoveNext () (at Assets/MoPub/Scripts/Editor/MoPubSDKManager.cs:208)
marijnz.EditorCoroutines.EditorCoroutines.MoveNext (marijnz.EditorCoroutines.EditorCoroutines+EditorCoroutine coroutine) (at Assets/MoPub/Scripts/ThirdParty/EditorCoroutines/Editor/EditorCoroutines.cs:368)
marijnz.EditorCoroutines.EditorCoroutines.OnUpdate () (at Assets/MoPub/Scripts/ThirdParty/EditorCoroutines/Editor/EditorCoroutines.cs:351)
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at C:/buildslave/unity/build/Editor/Mono/EditorApplication.cs:191)

**Comment by chauduyphanvu1** [comment]
@MochaGameStudio, thanks for letting us know about the crash. How often do you see it? I wonder if this is something that happens when we push out a release server-side. Could you confirm if you are able to re-launch the SDK Manager and continue with the integration/update without issues? Thank you!

Vu Chau
MoPub SDK Team

**Comment by MochaGameStudio** [comment]
> @MochaGameStudio, thanks for letting us know about the crash. How often do you see it? I wonder if this is something that happens when we push out a release server-side. After getting the exception, could you confirm if you are able to re-launch the SDK Manager and continue with the integration/update without issues? Thank you!
> 
> Vu Chau
> MoPub SDK Team

Well, I just followed the link content.(https://developers.mopub.com/publishers/unity/get-started/#step-1-integrate-the-plugin-and-mediation-adapters). And today I tried it again. First, create a new empty project with unity version 2018.2.18f1, then import the sdk (5.7.1), an error shows on, i change scripting runtime version from .net 3.5 to 4.x, restart , the error never show, and i click Mopub menu on the top, then click "Manage SDKs" , a message "Downloading SDK version manifest" shows in the "MoPub SDK Manager" panel, after several seconds, the Error "OverflowException : value was either too large or too small for a charactor" apears in the Unity console, that's all.

**Comment by duanzhk** [comment]
Unity 5.5.6
OverflowException: Value is greater than Char.MaxValue or less than Char.MinValue
System.Convert.ToChar (Int32 value) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/Convert.cs:624)
MoPubInternal.ThirdParty.MiniJSON.Json+Parser.get_PeekChar () (at Assets/MoPub/Scripts/ThirdParty/MiniJSON.cs:317)
MoPubInternal.ThirdParty.MiniJSON.Json+Parser.EatWhitespace () (at Assets/MoPub/Scripts/ThirdParty/MiniJSON.cs:306)
MoPubInternal.ThirdParty.MiniJSON.Json+Parser.get_NextToken () (at Assets/MoPub/Scripts/ThirdParty/MiniJSON.cs:345)
MoPubInternal.ThirdParty.MiniJSON.Json+Parser.ParseValue () (at Assets/MoPub/Scripts/ThirdParty/MiniJSON.cs:198)
MoPubInternal.ThirdParty.MiniJSON.Json+Parser.Parse (System.String jsonString) (at Assets/MoPub/Scripts/ThirdParty/MiniJSON.cs:122)
MoPubInternal.ThirdParty.MiniJSON.Json.Deserialize (System.String json) (at Assets/MoPub/Scripts/ThirdParty/MiniJSON.cs:89)
MoPubSDKManager+<GetSDKVersions>c__Iterator0.MoveNext () (at Assets/MoPub/Scripts/Editor/MoPubSDKManager.cs:208)
marijnz.EditorCoroutines.EditorCoroutines.MoveNext (marijnz.EditorCoroutines.EditorCoroutine coroutine) (at Assets/MoPub/Scripts/ThirdParty/EditorCoroutines/Editor/EditorCoroutines.cs:368)
marijnz.EditorCoroutines.EditorCoroutines.OnUpdate () (at Assets/MoPub/Scripts/ThirdParty/EditorCoroutines/Editor/EditorCoroutines.cs:351)
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at C:/buildslave/unity/build/artifacts/generated/common/editor/EditorApplicationBindings.gen.cs:207)

**Comment by sdolim** [comment]
From the stack trace it looks like an empty manifest was retrieved.  The MiniJSON.cs code will give this error if it is looking for a JSON character and instead reaches the end of the string.

**Comment by sdolim** [comment]
The new 5.8.0 release of the SDK guards against this now, so this issue may be fixed.
