### ISSUE TITLE
Build fails when FBSDK is present along with FBaudience network mediation in Mopub

### ISSUE THREAD

**Issue by shanukp** [mopub/mopub-unity-sdk#68]
#### Steps to reproduce the behavior:
1)Integrate Mopub add FBaudience network through SDK manager ,
 2)Integrate FBSDK
3)try building using Xcode 10.1
Build Fails

#### Expected behavior:
As concisely as possible, describe the expected behavior.

**XCODE BUILD ERROR BELOW**

duplicate symbol _OBJC_CLASS_$_FBSDKTypeUtility in:
    /Users/shprasad/Library/Developer/Xcode/DerivedData/Unity-iPhone-alnodpcnijfbcedxvfzpwoehowwk/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos/FBSDKCoreKit/libFBSDKCoreKit.a(FBSDKTypeUtility.o)
    /Users/shprasad/Desktop/newIosBuild05/Frameworks/FacebookSDK/Plugins/iOS/FBSDKCoreKit.framework/FBSDKCoreKit(FBSDKTypeUtility.o)
duplicate symbol _OBJC_METACLASS_$_FBSDKTypeUtility in:
    /Users/shprasad/Library/Developer/Xcode/DerivedData/Unity-iPhone-alnodpcnijfbcedxvfzpwoehowwk/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos/FBSDKCoreKit/libFBSDKCoreKit.a(FBSDKTypeUtility.o)
    /Users/shprasad/Desktop/newIosBuild05/Frameworks/FacebookSDK/Plugins/iOS/FBSDKCoreKit.framework/FBSDKCoreKit(FBSDKTypeUtility.o)
ld: 2 duplicate symbols for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by shanukp** [comment]
Can see that pod folder is somehow pulling  FBCoreKit even though i have FBSdkFramework in my plugins folder in unity. removing it results in error

**Comment by chauduyphanvu1** [comment]
@shanukp, could you confirm that you only add the `FBSDKCoreKit` framework exactly once to your project? Other Facebook SDKs also depend on `FBSDKCoreKit`, so if you are not using CocoaPods you might be integrating more than 1 copy of it, resulting in the duplicate symbols issue. 

What is the `FBSdkFramework` that you already have in your project? We're already pulling `FBSDKCoreKit`, which is the Facebook SDK, automatically via the SDK Manager so you don't need to add any other Facebook SDK framework later.

Vu Chau
MoPub SDK Team

**Comment by shanukp** [comment]
Iam not manually adding that . Unitys FbSdk framework in Plugins folder has FBSDKCoreKit and through cocoapods Mopub pulls FBSDKCoreKit to pods folder . This is What is creating the problem .

Deleting the FBSDKCoreKit from frameworks folder in Unity is creating build issues wrt FBSDK.

**Comment by shanukp** [comment]
so the whole idea is to reference the corekit in frameworks folder of unity rather again copying it again into pods . How do i do that here?

**Comment by shanukp** [comment]
<img width="516" alt="Screen Shot 2019-06-23 at 7 19 58 PM" src="https://user-images.githubusercontent.com/18196974/59977200-fc0bdd80-95eb-11e9-8d7d-5b46e0128aee.png">
<img width="488" alt="Screen Shot 2019-06-23 at 7 19 35 PM" src="https://user-images.githubusercontent.com/18196974/59977202-fdd5a100-95eb-11e9-8ad1-167adfc2061f.png">


Attached the screen shots of built xcode project from unity

**Comment by shanukp** [comment]
you can see the FbsdkCorekit in both target and in pods

**Comment by shanukp** [comment]
Try keeping just in one place , but then this keeps throwing error in one or other place

**Comment by shanukp** [comment]
How do i have go ahead and install fbaudience network through Mopub when i already have FBSDK in my unity project ?

**Comment by shanukp** [comment]
Or in other way how do i reference the corekit in Frameworks folder rather that downloading it into pods again?

**Comment by shanukp** [comment]
Can't mopub see whether project has corekit then reference that rather than blindly pulling it?

**Comment by chauduyphanvu1** [comment]
What's happening behind the scenes is the adapters are [transitively referencing the ad network SDK](https://github.com/mopub/mopub-ios-mediation/blob/master/FacebookAudienceNetwork/MoPub-FacebookAudienceNetwork-Podspecs/MoPub-FacebookAudienceNetwork-Adapters.podspec#L27), and that's how you have the `FBSDKCoreKit` in your `Pods` directory (`FBAudienceNetwork` references `FBSDKCoreKit`). Because the _other_ FB SDK you have is a `.framework` file and not dynamically downloaded by CocoaPods when you build your Xcode project from Unity, CocoaPods is not managing that in order to skip downloading the MoPub-side FB dependency.

My recommendation to resolve this duplicate symbols issue is remove the FB `.framework` file from your Unity project (if you manually put it there), and rely on the one that MoPub pulls via CocoaPods (via the way of the adapters). This way, you have exactly 1 copy of `FBSDKCoreKit`. If you have other code that references the FB `.framework` file, you will have to resolve subsequent linking issues. Otherwise, you should be good to go.

If you need another dependency from the FB SDK, add its pod name to [this dependency list](https://github.com/mopub/mopub-unity-mediation/blob/master/mopub-unity-adapters/FacebookAudienceNetwork/FacebookAudienceNetworkDependencies.xml), and CocoaPods will download it for you.

**Comment by shanukp** [comment]
other sdk iam using here is Facebook's Unity Sdk , which is not just a .framework file (Which makes it hard to delete specific files) . Tried removing CoreKit , sharekit and loginKit from framework and added in dependencies file as you mentioned , but thats throwing lot of error when FBSDK is compiled .FBsdk is not able to resolve and figure out that frameworks are in pods i guess

**Comment by shanukp** [comment]
Is there any other work around here ?

**Comment by shanukp** [comment]
is there any older version of fbaudience  where it doesnt pull corekit along?

**Comment by chauduyphanvu1** [comment]
Assuming you use the [MoPub SDK Manager](https://developers.mopub.com/publishers/unity/get-started/#option-1-use-the-sdk-manager-recommended), if you absolutely must keep the `.framework` file of the FB SDK, you can edit the FB adapter dependency list to remove [this snippet](https://github.com/mopub/mopub-unity-mediation/blob/master/mopub-unity-adapters/FacebookAudienceNetwork/FacebookAudienceNetworkDependencies.xml#L6-L9).  Doing so will stop the automated adapters + SDK download for Facebook Audience Network. Then, once you've built an Xcode project, you will be importing the adapters [manually](https://developers.mopub.com/publishers/unity/get-started/#option-2-integrate-manually). Just make sure the adapters can find the FB SDK `.framework` that you already have.

**Comment by shanukp** [comment]
There seems to be lot more dependency on the unity package . Just removing the framework to pod is not working for me . Since iam init fbsdk in unity specific manner. and will be required for android as well , and would like to keep it in the generic way .

Any ways i found a work around - which is downgraded project to 5.3.2.0 version of audience adapter which is actually not pulling the FbCorekit and ads are showing up as well . So i will stick to this for now . But i dont think i can upgrade anytime unless we somehow figure out proper fix for this . Removing frmaeworks from FBSDK unity package is creating problems compiling FBSDK . May be you guys can try a fresh project with both these plugins installed in it .

**Comment by Eirienen** [comment]
Have the same problem after upgrade FAN Adapter to 1.3.0

**Comment by feraligatr** [comment]
> There seems to be lot more dependency on the unity package . Just removing the framework to pod is not working for me . Since iam init fbsdk in unity specific manner. and will be required for android as well , and would like to keep it in the generic way .
> 
> Any ways i found a work around - which is downgraded project to 5.3.2.0 version of audience adapter which is actually not pulling the FbCorekit and ads are showing up as well . So i will stick to this for now . But i dont think i can upgrade anytime unless we somehow figure out proper fix for this . Removing frmaeworks from FBSDK unity package is creating problems compiling FBSDK . May be you guys can try a fresh project with both these plugins installed in it .

Thank you very much!

**Comment by sharoni** [comment]
Hi, just letting you know that Facebook Unity SDK 7.17.0 has been just released and should resolve this issue as all iOS dependencies are pulled from CocoaPods now -- https://developers.facebook.com/docs/unity/change-log#v7_17_0
