### ISSUE TITLE
Mediated network configuration values are not parsed properly for Android

### ISSUE THREAD

**Issue by AsafKoskiWork** [mopub/mopub-unity-sdk#72]
Hi. 

I'm a developer at Fyber. We have a custom adapter  which receives a parameter via Mopub.initializeSdk config map.
One of our customers saw, that when getting a parameter from Unity Mopub mediation layer, the value within the key-value map is a String which looks like the following:
"com.fasterxml.jackson.jr.stree.JrsString@2cfa321".

Caused by adding a network configuration object in the Mopub Unity sample: 
For example:
NetworkConfiguration = new Dictionary<string,object> {
                        { "appID", "102960543" }
                    }

I've investigated the issue, and have a suggested pull request:
https://github.com/mopub/mopub-unity-sdk/pull/71

**Comment by chauduyphanvu** [comment]
Hi @AsafKoskiWork, thanks for putting in the fix. I can confirm we've also fixed this internally on our end, and will release a new SDK containing the fix.

Vu Chau
MoPub SDK Team

**Comment by AsafKoskiWork** [comment]
Thanks

**Comment by rsatrasala** [comment]
Released in 5.9.0 of MoPub Unity SDK. Closing
