### ISSUE TITLE
Linker error on building through Jenkins

### ISSUE THREAD

**Issue by vivekgamedev** [mopub/mopub-unity-sdk#73]
I updated the Mopub Unity SDK to v5.7.1 and am trying to get a build through Jenkins. On building I get the following errors - 
[mopubError.txt](https://github.com/mopub/mopub-unity-sdk/files/3406116/mopubError.txt)

ld: warning: 
directory not found for option '-L /Volumes/Scratch/jenkins/xxx/bin/app/game/build/iphone/DerivedData/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos/mopub-ios-sdk'
ld: warning: arm64 function not 4-byte aligned: _unwind_tester from /Volumes/Scratch/jenkins/xxx/bin/app/game/build/iphone/src/Libraries/libiPhone-lib.a(unwind_test_arm64.o)

ld: symbol(s) not found for architecture arm64

- [*] I am submitting a bug report for existing functionality
- [*] I visited https://developers.mopub.com/ and found no answer
- [*] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [*] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.7.1
#### Device model and OS Version:
iPhone - iOS 12.3.1
#### Unity Version:
2018.3.14f1

Anyone have a fix for this?

**Comment by chauduyphanvu** [comment]
@vivekgamedev, I have not seen this issue before, so to help us debug it, I have some questions for you:

- Is your Jenkins set up to build for an iOS simulator or a physical iPhone? 
- If you are using an older version of Xcode, could you update it and retry? 
- Have you added the ObjC linker flag if needed?
- Is Jenkins _replacing_ or _appending_ to an earlier build ([doc](https://docs.unity3d.com/Manual/iphone-BuildProcess.html))?
- Do you have any other SDKs in your project? If so, could you try building the MoPub Unity SDK by itself with Jenkins and see if there's any similar issue?

Vu Chau
MoPub SDK Team

**Comment by vivekgamedev** [comment]
Turns out that the upgrade to PlayServicesResolver v1.2.110 is **EXTREMELY** critical for this upgrade.

Since we were using other third party SDKs I had not removed my older version to prevent complications. A clean Mopub + PlayServicesResolver installation has fixed my problem.
