### ISSUE TITLE
Mopub 5.8.0 Admob Network Configuration via Mopub Manager (Appid does not work)

### ISSUE THREAD

**Issue by stefanivalinov** [mopub/mopub-unity-sdk#75]
With the latest MoPub SDK(v5.8.0) i have done clean install. I have added MoPubManager to my scene and I've added Admob mediation plugin with its own tool. Then i've added Admob Network configuration from the prefab's interface and i have written required appids inside Admob Network configuration. After i built for android i have crash as you can see below.
This means that appids that i've written inside admob network configuration does not work.
Do i need to do something extra to apply these appids to my project ? 

The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
    * should follow the instructions here: https://goo.gl/fQ2neu to add a valid  *
    * App ID inside the AndroidManifest. Google Ad Manager publishers should     *
    * follow instructions here: https://goo.gl/h17b6x.

**Comment by hmertkahraman** [comment]
Hi @stefanivalinov,

Thanks for reaching out to us on this. Yes you're right, there's an extra step necessary for AdMob. In fact among all of our certified networks, only AdMob requires this exception. What you need to do is, when you export to Android from Unity, include this:
```
        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="[ADMOB_APP_ID]"/>
```
inside the `application` tag on your project's AndroidManifest file. It's also mentioned [here](https://firebase.google.com/docs/admob/android/quick-start#update_your_androidmanifestxml) on the AdMob docs.

Please let us know if this works, or if you have any additional questions.

Thanks,
MoPub Team

**Comment by stefanivalinov** [comment]
Thanks for the support. It works.
