### ISSUE TITLE
How to get Height of mopub banner

### ISSUE THREAD

**Issue by stefanivalinov** [mopub/mopub-unity-sdk#77]
Hello,

Mopub banners are stated as 320x50. It expands banners according to screen densities. It can be also 640x100 and 960x150.

I’ve tested and seen that for 408ppi screen it gives 960x150px banner and for 282ppi screen it gives 640x100px banner.

The height of banner changes according to screen density. But the problem is I can not get the mopub banner height. I need that dimension to setup an empty space for banner in my design.

Is there any rule in MoPub Unity SDK that has intervals like between 240ppi-320ppi it is 2X (640x100)? Or if the screen density is more than 320ppi it is 3X (960x150)?

**Comment by chauduyphanvu** [comment]
@stefanivalinov, you do not need to get the ad's height _after_ the request. Instead, to account for the conversion between dp and pixel, when you make an ad request to the MoPub Unity SDK, you can specify the ad sizes like so:

```csharp
float DENSITY = Screen.dpi / 160.0;
RequestBanner(adSlotWidth/DENSITY, asSlotHeight/DENSITY, position);
```
Let us know if there are any questions!
Vu Chau
MoPub SDK Team

**Comment by stefanivalinov** [comment]
It worked. Thanks for support.
