### ISSUE TITLE
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)

### ISSUE THREAD

**Issue by mubshar1** [mopub/mopub-unity-sdk#79]
Crash on Playable Ad

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ x] I checked to make sure that this issue has not already been filed

#### Device model and OS Version: 
SM-A7000 - Android 4.4.4
Xiaomi Redmi 6 (cereus), Android 8.1
TR10CS1_19, Android 4.4
Samsung Galaxy J4 Core (j4corelte), Android 8.1
Samsung Galaxy J6 (j6lte), Android 9

#### Steps to reproduce the behavior: 
Load and Play playable video Ad

#### Observed behavior:
crash

#### Evidence:
attached 
![error1](https://user-images.githubusercontent.com/45542019/64015841-dc8ab700-cb3e-11e9-8945-253297c4ec6c.PNG)

**Comment by chauduyphanvu** [comment]
@mubshar1, could you reproduce the crash locally? If so, could you send over your Unity project so we can take a look? This seems to be a low-level crash so it might be specific to the devices you test on.

Vu Chau
MoPub SDK Team

**Comment by mubshar1** [comment]
That was produced locally. Its not project dependent.

**Comment by chauduyphanvu** [comment]
Thanks! If you reproduced the issue locally, could you send us the Unity project with which the issue was observed as well as outline the steps taken to trigger it?
