### ISSUE TITLE
5.5.9 :   building errors: Duplicate class android.support.v4.app.INotificationSideChannel ..

### ISSUE THREAD

**Issue by YuliyF** [mopub/mopub-unity-sdk#82]
I got a list of errors after updating MoPub to 5.5.9 :

1)  java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class android.support.v4.app.INotificationSideChannel found in modules classes.jar (androidx.core:core:1.0.0) and classes.jar (com.android.support:support-compat:27.1.1)
2)   Duplicate class android.support.v4.os.IResultReceiver found in modules classes.jar (androidx.core:core:1.0.0) and classes.jar (com.android.support:support-compat:27.1.1)
...
and so on. And I can't fix it. I added:
android.useAndroidX=true
android.enableJetifier=true
and get a build but it's crashed on start

**Comment by chauduyphanvu** [comment]
@YuliyF, we do not have a 5.5.9 version. Did you mean 5.9.0?

If you are integrating from Unity, did you enable the Jetifier in Unity (in the Play Services Jar Resolver's settings) instead of doing that in the exported Android project? If not, give that a try and let us know if you continue seeing the issue. 

If you still see the issue, send us your zipped Unity project and we're happy to take a look!

Vu Chau
MoPub SDK Team

**Comment by chauduyphanvu** [comment]
@YuliyF, did you have a chance to try the suggestion in my previous response? Let us know if you resolved the issue or still need assistance!

**Comment by ttesla** [comment]
Similar error here. 

Mopub 5.9.0
Unity 2018.4.9f1
IL2cpp, 64 bit.
Facebook SDK 7.17.2 
GameAnalytics 5.1.11
All mediation networks.
Tried jetifier, didn't work.

```
com.android.build.api.transform.TransformException: Error while generating the main dex list.
> Error while generating the main dex list.
  > com.android.tools.r8.errors.CompilationError: Program type already present: android.support.v4.app.INotificationSideChannel$Stub$Proxy
    > Program type already present: android.support.v4.app.INotificationSideChannel$Stub$Proxy
```

**Comment by chauduyphanvu** [comment]
@ttesla, do you have a Unity project that reproduces that crash? If not, is it possible for you to reproduce it in our Unity sample app on this repository? If yes, could you share the reproduction steps?

Thank you!

**Comment by ttesla** [comment]
Hi again. 

After trying many combinations, Jetifier actually worked out. But I had to disable "auto resolution" and "resolution on build" from "Android Resolver Settings". I had to use "force resolution".  Or else it doesn't add these lines to my graddle which actually enables jetifier. 

Thank you, my issue is resolved.

`([rootProject] + (rootProject.subprojects as List)).each {
    ext {
        it.setProperty("android.useAndroidX", true)
        it.setProperty("android.enableJetifier", true)
    }`

**Comment by chauduyphanvu** [comment]
@ttesla, thanks for letting us know what you tried. You can actually enable the Jetifier right in the Jar Resolver settings without needing to fiddle with Gradle:

<img width="1171" alt="Screen Shot 2019-10-01 at 11 05 48 AM" src="https://user-images.githubusercontent.com/25616035/65974754-81006180-e43b-11e9-8835-44d6a22ba9db.png">

<img width="1230" alt="Screen Shot 2019-10-01 at 11 05 57 AM" src="https://user-images.githubusercontent.com/25616035/65974766-8493e880-e43b-11e9-8b90-2e838469002c.png">

Give that a try and let us know if that works!

**Comment by rsatrasala** [comment]
If the issue persists, please create a new issue. Closing this one.
