### ISSUE TITLE
MoPub 5.9.0 SetEngineInformation exception

### ISSUE THREAD

**Issue by rmohm** [mopub/mopub-unity-sdk#83]
Build for android:
Because setEmgineInformation is not implemented in com.mopub.unity.MoPubUnityPlugin there are errors in logcat:
 AndroidJavaException: java.lang.NoSuchMethodError: no static method with name='setEngineInformation' signature='(Ljava/lang/String;Ljava/lang/String;)V' in class Ljava.lang.Object;

**Comment by rmohm** [comment]
I made a mistake...

**Comment by chauduyphanvu** [comment]
@rmohm, I was going to respond to the issue 😄 Glad to know it's now resolved. Let us know if you still need help in the future!

Vu Chau
MoPub SDK Team

**Comment by mikotomioo** [comment]
I get this mistake too. What can I do?

**Comment by chauduyphanvu** [comment]
@mikotomioo, could you send over your Unity project so we can build and reproduce this crash? Could you also confirm you integrated the MoPub SDK using the [official instructions](https://developers.mopub.com/publishers/unity/get-started/#step-1-integrate-the-plugin-and-mediation-adapters) outlined in our public documentation?

**Comment by mikotomioo** [comment]
@chauduyphanvu I use the SDK Manager to fix this error.
