### ISSUE TITLE
Probelm with multidex 

### ISSUE THREAD

**Issue by GeekyGal123** [mopub/mopub-unity-sdk#84]
One line summary of the issue here

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.9.0

#### Device model and OS Version:
Samsung Galaxy A10

#### Unity Version: 
2019.2.0f1

#### Ad Unit IDs used in reproducing the issue:
b195f8dd8ded45fe847ad89ed1d016da

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.
Installed all the Network SDKS and tried building in Unity

#### Expected behavior:
As concisely as possible, describe the expected behavior.
Build successfully.

#### Observed behavior:
As concisely as possible, describe the observed behavior.

Got Following errors:
D8: Cannot fit requested classes in a single dex file (# methods: 91923 > 65536) UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':transformDexArchiveWithExternalLibsDexMergerForRelease'.

#### Evidence:
Device log files, Network log file, etc.
[error.log](https://github.com/mopub/mopub-unity-sdk/files/3657439/error.log)

**Comment by GeekyGal123** [comment]
I solved it by creating the Custom Gradle Template in the Player Setting -> Publishing settings in Unity. But the app crashes when I try to open it on Samsung Galaxy A10.

**Comment by chauduyphanvu** [comment]
@GeekyGal123, great to hear you've resolved the multidex issue! For the new crash, would you be able to provide a stack trace as well as any reproduction steps? 

Vu Chau
MoPub SDK Team

**Comment by GeekyGal123** [comment]
Hello Vu,

I am not sure how to get stacktrace but I can tell you what I have done. I imported the unity plugin (5.9.0) for Unity and installed all the network SDK I have also initialized the sdk using the MoPubmanager prefab and tried to build it. Since I do have an enabled USB right now I cannot use the Andriod profiler. Please let me know if you require more information.


Thank you,
Nandita Dhatrika
Unity Game Devloper

**Comment by chauduyphanvu** [comment]
Thanks for the information. We need to see stack traces in order to debug crashes, so when you get a chance to obtain one, feel free to post it here and we'll take a look!

**Comment by GeekyGal123** [comment]
Can you tell me how to get stack traces?

**Comment by chauduyphanvu** [comment]
It's a bit difficult to get a stack trace if your USB usage is disabled/prohibited in your office. Will you be able to speak to the administrator about that? Once you have USB enabled, you can run `adb logcat` (https://developer.android.com/studio/command-line/logcat) to start monitoring device logs. You can then get the stack trace when the crash occurs, and paste it here.

`adb` also allows for [wireless connectivity](https://stackoverflow.com/a/14357876/1267747) but that requires an initial USB setup as well.

**Comment by GeekyGal123** [comment]
Thanks I will try this out.

**Comment by chauduyphanvu** [comment]
@GeekyGal123, did you have a chance to test things out and capture a stack trace for the crash?

**Comment by GeekyGal123** [comment]
Oh no not yet I have been assigned to another task and no enabled USBs
