### ISSUE TITLE
Android build crashes with AdMob adapters in

### ISSUE THREAD

**Issue by 99upgames** [mopub/mopub-unity-sdk#86]
App crashes on launch when AdMob is added to MoPub's plugin in Unity.

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
Create blank project in Unity.
Install MoPub plugin. (build & run works).
Install AdMob adapters.
Add AdMob config script with filled in information.
Add AndroidManifest AdMob app id requirements.
Add MoPub demo scene to the build.
Build & run the app on device.
App crashes on app start.

#### Expected behavior:
App should run, load AdMob ads and display them.

#### Observed behavior:
App crashes on app start.

**Comment by chauduyphanvu** [comment]
@99upgames, could you share the stack stace for that crash you are seeing? Could also also confirm if you can reproduce this crash locally in the MoPub Unity sample app on this repository? Thank you!

Vu Chau
MoPub SDK Team

**Comment by 99upgames** [comment]
I can confirm that I have the same issue with the sample app.

I've attached the log file. It's a basic Google Mobile Ads not initialized properly error. I tried with 2 valid app ids as well as the sample app id from google ads (with the AndroidManifest updated accordingly) and nothing works.

I'm under the assumption that I don't need to do anything else than installing the adapters through MoPub's SDK Manager and adding the AndroidManifest to make AdMob work in the app, correct ? Do I need to add Google Mobile Ads to the project and initialize it manually via script ? It seems to me that Google Mobile Ads' auto initialization through MoPub scripts doesn't work. 

[Error-log.txt](https://github.com/mopub/mopub-unity-sdk/files/3690888/Error-log.txt)

**Comment by chauduyphanvu** [comment]
@99upgames, thanks for the confirmation. Could you share your Manifest content here for we can take a look?

Here's an example (modified) Manifest [from the MoPub Unity sample app](https://github.com/mopub/mopub-unity-sdk/blob/master/unity-sample-app/Assets/MoPub/Plugins/Android/MoPub.plugin/AndroidManifest.xml). I verified that this works (no crash):

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest package="com.mopub.unityplugindemo" xmlns:android="http://schemas.android.com/apk/res/android">
    <uses-sdk android:minSdkVersion="16"/>

    <application>
        <uses-library
          android:name="org.apache.http.legacy"
          android:required="false" />

        <!-- MoPub SDK activities. -->
        <activity android:name="com.mopub.mobileads.MoPubActivity"
                  android:configChanges="keyboardHidden|orientation|screenSize"/>
        <activity android:name="com.mopub.mobileads.MraidActivity"
                  android:configChanges="keyboardHidden|orientation|screenSize"/>
        <activity android:name="com.mopub.common.MoPubBrowser"
                  android:configChanges="keyboardHidden|orientation|screenSize"/>
        <activity android:name="com.mopub.mobileads.MraidVideoPlayerActivity"
                  android:configChanges="keyboardHidden|orientation|screenSize"/>
        <activity android:name="com.mopub.mobileads.RewardedMraidActivity"
                  android:configChanges="keyboardHidden|orientation|screenSize"/>
        <activity android:name="com.mopub.common.privacy.ConsentDialogActivity"
                  android:configChanges="keyboardHidden|orientation|screenSize"/>

	<!-- Sample AdMob App ID: ca-app-pub-3940256099942544~3347511713 -->
        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-3940256099942544~3347511713"/>

    </application>

    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
</manifest>
```

You do not need to do anything else besides adding the AdMob app ID to your Manifest like above.

**Comment by 99upgames** [comment]
@chauduyphanvu Still nothing different, it still crashes. It used to work though, it's not the first time I've used MoPub in Unity, I've been using it for the past 3-4 years or so.

I'm running the sample app provided in the sdk by the way, nothing else. Can you tell me which Unity version you're using to make it work ?

I've attached the AndroidManifest I'm using (as an xml file in the project).

[AndroidManifest.txt](https://github.com/mopub/mopub-unity-sdk/files/3696278/AndroidManifest.txt)

I've also tried with the AndroidManifest you provided but it still crashes.

**Comment by 99upgames** [comment]
I've tried manually adding Google Mobile Ads into the project and giving it the correct Ad Unit, while still installing the AdMob adapters through MoPub's SDK Manager, and there's no more crashes on app start. This is what I used to do, which used to work aroun MoPub's Unity Plugin 5.6 or so.

However now all my ad units fail to load ads from AdMob saying "No ads found", still after 50+ tries (while they do work in the live apps) and trying to load a test interstitial ad through AdMob's test AdUnit (ca-app-pub-3940256099942544/1033173712) results in a black screen with a close button 9 out of 10 times.

All of this with Unity updated to 2019.2.8f1.

**Comment by chauduyphanvu** [comment]
@99upgames, thanks for sending over your Manifest. I tested the MoPub Unity sample app in Unity 2019.2.8f1 just now and also did not see that app ID crash. FWIW, I previously used Unity 2017.4.30f1 so you could feel free to check out that version to ensure it's not a Unity-related setup issues. One thing you could do is reverse-engineer the exported APK and check the Manifest to see if the entry for the AdMob app ID is still in there. I assume it got removed in your build process.

This is a working MoPub Unity sample app I used with 2019.2.8f1: https://chauduyphanvu.s3.us-east-2.amazonaws.com/sample_apps/mopub-unity-sdk-2019.zip. I just integrated the AdMob adapters via our SDK Manager option, and added a sample AdMob app ID to the Manifest. Check it out and let us know if you see any crashes. 

You should not manually adding the Google Mobile Ads SDK into your project. The Jar Resolver will handle that for you by [getting this dependency](https://github.com/mopub/mopub-unity-mediation/blob/master/mopub-unity-adapters/AdMob/AdMobDependencies.xml#L4). Having two Google Mobile Ads SDKs might result in unexpected ad behaviors.

**Comment by 99upgames** [comment]
I can confirm that the project you sent me in the last message worked for me. I still have AdMob ad display issues but I'm not convinced that it's related to MoPub or AdMob. Non AdMob ads display fine.

I'm gonna try getting that configuration over to my main project and see how it goes.
