### ISSUE TITLE
Issue integrating Ironsource using Mopub Unity 2018.2.8f1

### ISSUE THREAD

**Issue by shanukp** [mopub/mopub-unity-sdk#88]
One line summary of the issue here

Receiving following error while trying to load ad using test ad slots for IronSource 

**API: init(appKey:0)
10-11 14:43:45.771 13774 13774 I ironSourceSDK: CALLBACK: onRewardedVideoAvailabilityChanged(available:false)
10-11 14:43:45.772 13774 13774 I ironSourceSDK: API: errorCode:506, errorMessage:Init Fail - appKey value 0 is not valid - length should be between 5-10 characters
10-11 14:43:45.772 13774 13774 I ironSourceSDK: API: loadISDemandOnlyRewardedVideo() instanceId=8655fa9d
10-11 14:43:45.772 13774 13774 E ironSourceSDK: API: init() had failed
10-11 14:43:45.774 13774 13774 I ironSourceSDK: API: setConsent : true**

#### Iron source version : 1.1.16

Why appKey is 0 here , How do we set it in before initializing? 

Is this the way to set the appkey?? Code reference below
var sdkConfig = new MoPub.SdkConfiguration
               {
                   AdUnitId = AdSettings.IDs[platformType][AdUnits.REWARDED_VID], //Pass any valid ad unit here
                   LogLevel = MoPubBase.LogLevel.MPLogLevelNone,
                   MediatedNetworks = new MoPub.MediatedNetwork[]
                   {
                   new MoPub.SupportedNetwork.AdMob(),
                   new MoPubBase.SupportedNetwork.Facebook(),
                    new MoPub.SupportedNetwork.IronSource()
                    {
                        NetworkConfiguration = new Dictionary<string,object>
                        {
                           { “appKey”, #appkey }
                    }    }
                   }
               };

**Comment by hmertkahraman** [comment]
Hi @shanukp ,

Thanks for reaching out. Could you please share the Ad Unit Id you're encountering this issue with?

You don't need to include ironSource App Key at this level. ironSource adapters & SDK will pull the App Key parameter dynamically during ad request lifecycle (at the very first first ad request to ironSource). And then it will cache to reuse it. So even if it's not present above, it should be able to pull it from the Networks setup. That appears not to be working. 

So could you please ensure you entered App Key parameter is set properly on the MoPub UI? Please see below steps:
- On MoPub UI, navigate to Networks > Select ironSource > App & Ad Unit Setup
- A list of all Apps and their respective ad units will appear
- Navigate down the list to find the app relating to this issue
- Ensure App Id parameter is populated with the correct value. Below is an example for an Android app:
![image](https://user-images.githubusercontent.com/47573140/66658324-2a640600-ec39-11e9-8e6e-5a6c71943573.png)

**Side Note:**
_Also make sure you've populated relevant instance IDs using your ironSource dashboard._

Could you please let us know of the status of your Network setup per the above recommendation?

Thanks,
MoPub Team
