### ISSUE TITLE
PackageManagerException

### ISSUE THREAD

**Issue by Cascade-Habib** [mopub/mopub-unity-sdk#91]
Installation of a second app fails with error.
PackageManager: com.android.server.pm.PackageManagerException: Can't install because provider name com.mopub.testing.AudienceNetworkContentProvider (in package com.ag.light.atv.quad.bike.transport.truck3ds) is already used by com.ttg.dogrun.bravedog 

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
I downloaded the latest unity Plugin and installed following adnetowrks from MOPUB MENU.

ADCOLONY
ADMOB
UNITY ADS
AUDIENCE NETWORK

It is integrated correctly, I can see ads from all four of the above networks in first application.

Problem:
Problem is, when I install the very first apk “com.ttg.dogrun.bravedog ” it is installed correctly and I can play the game.
However when I build another apk of another project, when I try to install this new apk of a different project “com.ag.light.atv.quad.bike.transport.truck3ds”, IT IS not installed. 
Here is the error log .
PackageManager: com.android.server.pm.PackageManagerException: Can't install because provider name com.mopub.testing.AudienceNetworkContentProvider (in package com.ag.light.atv.quad.bike.transport.truck3ds) is already used by com.ttg.dogrun.bravedog 

Summary, It only allows me to install only one application, and it does not allow me to install any other apk using same plugin used in first project.
so when I try to install 2nd ,3rd, 4th or any other project, it never get installed. And raises above error message in log cat.

#### Expected behavior:
second, 3rd and subsequent apps should be installed
#### Observed behavior:
Only one first app apk is installed, subsequent different apps/apks fail to install

#### Evidence:
PackageManager: com.android.server.pm.PackageManagerException: Can't install because provider name com.mopub.testing.AudienceNetworkContentProvider (in package com.ag.light.atv.quad.bike.transport.truck3ds) is already used by com.ttg.dogrun.bravedog

**Comment by chauduyphanvu** [comment]
@Cascade-Habib, thanks for letting us know! Based on the error message, it doesn't look like an SDK-related issue you are experiencing. Rather, it seems to be related to the build workflow that generates the APKs.

Specifically, we do not recognize the `com.mopub.testing.AudienceNetworkContentProvider` package (in your `com.ag.light.atv.quad.bike.transport.truck3ds` package) as it doesn't belong to MoPub. None of MoPub's SDK and adapter distributions have `com.mopub.testing` in its package names. The closest is `com.mopub.mobileads.testing`.

I recommend tracing where in your workflow you might have imported `com.mopub.testing.AudienceNetworkContentProvider`.

Vu Chau
MoPub Team,

**Comment by Cascade-Habib** [comment]
Thanks for your reply, i have figured it out, I just copied the plugins folder to another application from the first application. which caused this problem, when i resolved updated the audience network version from mopub menu in unity it fixed the error.
