### ISSUE TITLE
Audience Network ads not showing on android 9 and above

### ISSUE THREAD

**Issue by Cascade-Habib** [mopub/mopub-unity-sdk#92]
Audience network when mediated from mopub does not show ads on mobile having android version 9

- [ ] I am submitting a bug report for existing functionality
- [ ] I visited https://developers.mopub.com/ and found no answer
- [ ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ ] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.10.0
#### Unity Version:
2018
#### Steps to reproduce the behavior:
I used admob, unity and audience network as mediation networks.
All of them show ads correctly except audience network.
Audience network ONLY SHOWS ads on devices with android version 7 and lower.
On devices having android version 9 and above, audience network when mediated does not show the ads. 
First it showed an error in logcat "com.facebook.ads.redexgen.X.Mo: Error opening connection for http://127.0.0.1:34421/ping with offset 0
Caused by: java.io.IOException: Cleartext HTTP traffic to 127.0.0.1 not permitted"
I added the network_security_config as below AND it fixed the cleartext error. HOWEVER ADS FROM AUDIENCE NETWORK ON ANDROID 9 AND ABOVE STILL DOES NOT SHOW, it however shows the audience network ads on older android versions.

<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
<domain-config cleartextTrafficPermitted="true">
<domain includeSubdomains="true">127.0.0.1</domain>

</domain-config>
</network-security-config>

Could you please let me know how to fix so that ads on audience network on android 9 and above can work.
#### Expected behavior:
Audience network ads on android 9 and above should work

#### Observed behavior:
Audience network ads on android 9 and above DOES NOT work

#### Evidence:
MoPub   : [com.mopub.mobileads.MoPubInterstitial][onCustomEventInterstitialFailed] Ad failed to load: (10,000) Third-party network failed to provide an ad.

**Comment by chauduyphanvu** [comment]
@Cascade-Habib, could you show us the content of your `network_security_config.xml` file? Please make sure it matches exactly `127.0.0.1` (and not `127.0.0.1 dgtronsys.com`) per [Facebook's recommendation](https://developers.facebook.com/docs/audience-network/android-network-security-config).

Vu Chau
MoPub Team

**Comment by Cascade-Habib** [comment]
here is my network_security_config.xml

<?xml version="1.0" encoding="utf-8"?>

<network-security-config>
<domain-config cleartextTrafficPermitted="true">

<domain includeSubdomains="true">127.0.0.1</domain>


</domain-config>

</network-security-config>

**Comment by chauduyphanvu** [comment]
@Cascade-Habib, thanks for the confirmation. This does not look an expected behavior so could you try with our [Unity sample app](https://github.com/mopub/mopub-unity-sdk/tree/master/unity-sample-app) instead? 

To quickly reproduce the issue, install Facebook via the SDK Manager, add the network_security_config.xml file the way you did, reference it from the AndroidManifest, and test on an Android 9.0 phone. If you still see the issue, send us the project as-is and we can take a look.

**Comment by Cascade-Habib** [comment]
Thanks, i did but it did not work.
here is the link of the repo, this is the same unity sample app, I JUST ADDED android manifest and network config etc to get the project running.
Please note that audience network ads are NOT WORKING ON ANDROID VERSION 9, on lower version it worked
here is the project that you requested
[](https://github.com/Cascade-Habib/Mopub-Integration-November-2019)

**Comment by Cascade-Habib** [comment]
Any update on this?

**Comment by chauduyphanvu** [comment]
@Cascade-Habib, thanks for preparing our sample app to demonstrate the issue you are seeing. We will take a look and get back to you with any findings.

**Comment by chauduyphanvu** [comment]
Hello,

I tried with your app but was unable to build because I'd need a password to sign the APK.

I tried with our Unity sample app with Facebook configured and ran it on an Android 10 device. I was able to successfully request and play a Facebook rewarded video ([see logs](https://gist.githubusercontent.com/chauduyphanvu/f42187341bf187329a8db4b680d3d3a8/raw/c69f3832ef4b4a934b7ce2af9dcb059816cde95f/mopub_unity_facebook_android_10.txt) - note the `osv=10.0.0` parameter denoting Android 10).

**Comment by SebaDudzic** [comment]
Hi,

I have the same problem. Android 9 doesn't work. Old systems are ok. The Facebook-only problem. I have added an entry to `network_security_config.xml` but nothing changed. I have explored device logs but there is nothing related to this. No errors, no trace of problems. Ads get a callback with failure loading - "No ads found.". So it suggests no fill. But on other systems, it works.

Unity 2018.4.5f1, 
MoPub 5.10.0

**Comment by chauduyphanvu** [comment]
@SebaDudzic, could you enable Facebook Audience Network's test mode to confirm whether there's fill? I've confirmed in my previous response that our Unity sample app with Facebook integrated worked on an Android 10 device (albeit I did not exclusively test on Android 9). 

> We also have FacebookSDK implemented for Analytics. Maybe this is a problem?
Another used plugin is Firebase.

There's no known issue with that combination, but you have the option of modifying [our Unity sample app](https://github.com/mopub/mopub-unity-sdk/tree/master/unity-sample-app) to mimic your integration to rule out any external factors. 

What does your `network_security_config.xml` look like?

**Comment by SebaDudzic** [comment]
Ok, I have managed to get it working. The solution is strange. I had to put the app to Internal Test Track on Google Play Store and then install it through the store. Then it's working.
