### ISSUE TITLE
app is not installed ON ANDROID 9 when package id in unity inspector changed to another package name

### ISSUE THREAD

**Issue by Cascade-Habib** [mopub/mopub-unity-sdk#95]
App is not installed on phone when generated a new apk by just changing the package name in unity inspector.

- [ ] I am submitting a bug report for existing functionality
- [ ] I visited https://developers.mopub.com/ and found no answer
- [ ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ ] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.10
#### Unity Version:
2018
#### Steps to reproduce the behavior:
get the sample app of unity plugin 5.10
1. use com.packageName1 as package name in unity inspector
2. generate an apk, it will be a success and app will be installed correctly.
3. change the package name in inspector to com.packageName2
4. generate an apk, it will generate the apk BUT APK WILL NOT BE INSTALLED on phone. 
here is the reason, the provider AUTHORITIES in androidmanifest of "com.facebook.android.audience-network-sdk-5.6.0" does not get updated with com.packageName2.AudienceNetworkContentProvider, it still shows the same old name"com.packageName1.AudienceNetworkContentProvider" which does not allow the app to be installed on ANDROID 9
Below is the provider string after generating two apks, it should change everytime a package name changes in unity build settings to work correctly i think
<provider android:name="com.facebook.ads.AudienceNetworkContentProvider" android:authorities="com.packageName1.AudienceNetworkContentProvider" android:exported="false" />
#### Expected behavior:
As concisely as possible, describe the expected behavior.

#### Observed behavior:
As concisely as possible, describe the observed behavior.

#### Evidence:
Device log files, Network log file, etc.

**Comment by dravyan** [comment]
@Cascade-Habib, thanks for reporting this. I tried to replace the packageName and I notice the it is also updated in the authorities from `android:authorities="com.mopub.sample.AudienceNetworkContentProvider"` to `android:authorities="com.mycompany.sample.AudienceNetworkContentProvider"`. Could you share the exact steps to replicate the issue?. Also during the build process, try to choose the `Replace` option than using `append` when you build the updated app. Let me know how it goes.

Thanks,
Dravya Nataraj
MoPub Team

**Comment by Cascade-Habib** [comment]
what is the best way to copy/paste mopub related folders in other games without PlayServicesresolver? 
for example, i have Game1 where all dependencies are resolved and ads are working correctly.
I want to just copy/paste folders so that ads are implemented in other 50 projects without hassle.

1. Mopub including all subfolders in following Games
2. Plugins including all sub folders folders and files having Android folder and all the 3rd party ad network files

When i copy paste the above folders in other projects apps are not installed due to android:authorities, it always has the same authorities in the 50 different projects where i have copied the files from project 1.
Why the provider AUTHORITIES in androidmanifest of "com.facebook.android.audience-network-sdk-5.6.0" does not get updated with com.packageName2.AudienceNetworkContentProvider, it still shows the same old name"com.packageName1.AudienceNetworkContentProvider" of first game which does not allow rest of the 49 games to be installed on ANDROID 9

Could you please let me know the best way to copy/paste folders without playservicesresolver so that we can give update of 50 apps.
Thanks

**Comment by dravyan** [comment]
@Cascade-Habib, 
- could you let us know what version of Unity are you using?
- Are they using the gradle setting in Build Settings?
- What are the settings for Jar Resolver? Can you share the screenshot?

To copy things from one project to another you should use `Export Package` and then `Import Package`..
Let us know how that goes.

Thanks,
Dravya Nataraj
MoPub Team

**Comment by Cascade-Habib** [comment]
1. I am using Unity 2018.4.8f1
2. yes, i am using gradle build settins
3. see attached settings for jar resolver
![image](https://user-images.githubusercontent.com/17279298/69705541-9e8a3880-1117-11ea-8017-d8dcea52fff5.png)

Note: Application id is replaced when we use jar resolver folder in other 49 apps, but is not there any way to upgrade 49 applications OFFLINE without using jar resolver?

Also, as per the JAr Resolver settings, ApplicationID is replaced during build precess for androidmanifest.xml file inside the root Plugins\Android folder. However there is no manifest file there, as you guys have now moved the manifest file inside MoPub\Plugins\Android\MoPub.plugin

**Comment by dravyan** [comment]
@Cascade-Habib,
This is how my jarResolver and build settings look like
![Screen Shot 2019-12-02 at 11 26 19 AM](https://user-images.githubusercontent.com/44005959/69992844-71ff6380-14ff-11ea-8aa8-2617036f3642.png)
![Screen Shot 2019-12-02 at 11 27 22 AM](https://user-images.githubusercontent.com/44005959/69992867-7b88cb80-14ff-11ea-9a26-f3117848f75a.png)

When the apk is built, go to <Unity ProjectDir>/Temp/gradleOut - you can open that in Android Studio to see all the resolved manifests, and also the combined build.gradle file.  That's where you will check if AndroidManifest is resolved and updated correctly when the package name is updated. It works as expected in my testing.

Thanks,
Dravya Nataraj
MoPub Team

**Comment by rsatrasala** [comment]
Please open a new issue if needed
