### ISSUE TITLE
Facebook under Mopub mediation with GDPR consent

### ISSUE THREAD

**Issue by stefanivalinov** [mopub/mopub-unity-sdk#99]
How can i send GDPR consent for Facebook on initialize? There is no info under https://developers.mopub.com/publishers/mediation/networks/facebook/

I am using Mopub 5.10.0 with unity.

**Comment by chauduyphanvu** [comment]
@stefanivalinov, Facebook Audience Network does not consume consent information from the MoPub SDK (https://developers.mopub.com/publishers/mediation/supported-mediation-partners/). You will need to work directly with Facebook for GDPR instructions.

Vu Chau
MoPub Team
